"""Field allowlists for the daily research handoff."""

DAILY_RESEARCH_TABLES = (
    "research_hypotheses",
    "research_experiment_families",
    "research_trials",
    "research_experiment_manifests",
    "research_universe_manifests",
    "research_trial_results",
    "research_validation_dossiers",
    "research_validation_gates",
    "research_strategy_forecasts",
    "research_universe_observations",
    "research_strategy_revisions",
    "preopen_daily_brief",
    "daily_brief",
    "portfolio",
    "portfolio_summary",
    "portfolio_risk_cards",
    "review_actions",
    "exposure_clusters",
    "universe_screen",
    "manual_watchlist",
    "quotes",
    "fundamentals",
    "technicals",
    "analyst_estimates",
    "options_ticker_signals",
    "thesis_monitor",
    "decision_queue",
    "catalysts",
    "earnings",
    "market_environment_model",
    "market_environment_assets",
    "option_radar_opportunity",
)

DAILY_RESEARCH_QUERY_LIMITS = {
    "research_hypotheses": 100,
    "research_experiment_families": 100,
    "research_trials": 500,
    "research_experiment_manifests": 100,
    "research_universe_manifests": 500,
    "research_trial_results": 500,
    "research_validation_dossiers": 250,
    "research_validation_gates": 1250,
    "research_strategy_forecasts": 500,
    "research_universe_observations": 500,
    "research_strategy_revisions": 500,
    "preopen_daily_brief": 1,
    "daily_brief": 12,
    "portfolio_summary": 1,
    "portfolio_risk_cards": 8,
    "review_actions": 8,
    "exposure_clusters": 100,
    "decision_queue": 100,
    "market_environment_model": 12,
    "market_environment_assets": 80,
    "fundamentals": 400,
    "technicals": 100,
    "analyst_estimates": 100,
    "options_ticker_signals": 100,
    "catalysts": 200,
    "earnings": 200,
}

DAILY_RESEARCH_MACRO_SYMBOLS = frozenset(
    {
        "SPY",
        "QQQ",
        "IWM",
        "DIA",
        "VIX",
        "VXX",
        "TLT",
        "UUP",
        "GLD",
        "USO",
        "BTC-USD",
        "ETH-USD",
    }
)
