"""Shared option-chain scan parameters used by provider collectors."""

from __future__ import annotations

RADAR_MIN_DTE = 365
RADAR_MAX_DTE = 900
RADAR_MAX_EXPIRIES_PER_SYMBOL = 2
RADAR_STRIKES_AROUND_SPOT = 24
RADAR_CALL_STRIKE_OTM_LO = 1.0
RADAR_BASELINE_CALL_STRIKE_OTM_HI = 1.6
RADAR_LOTTERY_CALL_STRIKE_OTM_LO = 1.6
RADAR_CALL_STRIKE_OTM_HI = 3.0

__all__ = [
    "RADAR_BASELINE_CALL_STRIKE_OTM_HI",
    "RADAR_CALL_STRIKE_OTM_HI",
    "RADAR_CALL_STRIKE_OTM_LO",
    "RADAR_LOTTERY_CALL_STRIKE_OTM_LO",
    "RADAR_MAX_DTE",
    "RADAR_MAX_EXPIRIES_PER_SYMBOL",
    "RADAR_MIN_DTE",
    "RADAR_STRIKES_AROUND_SPOT",
]
