-- Tables: foundation objects.

CREATE TABLE analysis.agent_experiment (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    experiment_key text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    champion_provider text NOT NULL,
    champion_model text NOT NULL,
    challenger_provider text NOT NULL,
    challenger_model text NOT NULL,
    max_pairs_per_trading_day integer DEFAULT 12 NOT NULL,
    advisory_only boolean DEFAULT true NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    parameters jsonb DEFAULT '{}'::jsonb NOT NULL,
    immutable_report jsonb,
    report_sealed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agent_experiment_check CHECK (((status <> 'completed'::text) OR (immutable_report IS NOT NULL))),
    CONSTRAINT agent_experiment_max_pairs_per_trading_day_check CHECK (((max_pairs_per_trading_day >= 1) AND (max_pairs_per_trading_day <= 12))),
    CONSTRAINT agent_experiment_status_check CHECK ((status = ANY (ARRAY['active'::text, 'completed'::text, 'archived'::text]))),
    CONSTRAINT agent_experiment_experiment_key_key UNIQUE (experiment_key),
    CONSTRAINT agent_experiment_pkey PRIMARY KEY (id)
);

CREATE TABLE analysis.event_decision_packet (
    event_id text NOT NULL,
    symbol text NOT NULL,
    event_kind text NOT NULL,
    trigger_type text NOT NULL,
    as_of timestamp with time zone NOT NULL,
    publication_id text,
    headline text,
    market_tape jsonb DEFAULT '{}'::jsonb NOT NULL,
    positioning jsonb DEFAULT '{}'::jsonb NOT NULL,
    event_fundamentals jsonb DEFAULT '{}'::jsonb NOT NULL,
    platform_optionality jsonb DEFAULT '{}'::jsonb NOT NULL,
    historical_cases jsonb DEFAULT '{}'::jsonb NOT NULL,
    tactical_decision jsonb DEFAULT '{}'::jsonb NOT NULL,
    fundamental_decision jsonb DEFAULT '{}'::jsonb NOT NULL,
    decision_truth jsonb DEFAULT '{}'::jsonb NOT NULL,
    evidence_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_event_decision_packet_json_objects CHECK (((jsonb_typeof(market_tape) = 'object'::text) AND (jsonb_typeof(positioning) = 'object'::text) AND (jsonb_typeof(event_fundamentals) = 'object'::text) AND (jsonb_typeof(platform_optionality) = 'object'::text) AND (jsonb_typeof(tactical_decision) = 'object'::text) AND (jsonb_typeof(fundamental_decision) = 'object'::text) AND (jsonb_typeof(decision_truth) = 'object'::text))),
    CONSTRAINT event_decision_packet_pkey PRIMARY KEY (event_id)
);

CREATE TABLE analysis.hypothesis (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    hypothesis_key text NOT NULL,
    statement text NOT NULL,
    mechanism_class text NOT NULL,
    falsification text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    input_hash character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    available_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT hypothesis_check CHECK ((available_at >= created_at)),
    CONSTRAINT hypothesis_hypothesis_key_key UNIQUE (hypothesis_key),
    CONSTRAINT hypothesis_pkey PRIMARY KEY (id)
);

CREATE TABLE analysis.market_coverage_vector (
    vector_id text NOT NULL,
    as_of timestamp with time zone NOT NULL,
    status text NOT NULL,
    payload jsonb NOT NULL,
    ingest_run_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    input_content_hash text NOT NULL,
    parent_snapshot_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT market_coverage_vector_pkey PRIMARY KEY (vector_id)
);

CREATE TABLE analysis.market_scenario_path (
    scenario_hash text NOT NULL,
    snapshot_id text NOT NULL,
    parent_snapshot_id text NOT NULL,
    posterior_id text NOT NULL,
    model_version text NOT NULL,
    ingest_run_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    input_content_hash text NOT NULL,
    path jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT market_scenario_path_pkey PRIMARY KEY (scenario_hash)
);

CREATE TABLE analysis.market_state_posterior (
    posterior_id text NOT NULL,
    as_of timestamp with time zone NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    model_version text NOT NULL,
    status text NOT NULL,
    payload jsonb NOT NULL,
    ingest_run_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    input_content_hash text NOT NULL,
    parent_snapshot_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT market_state_posterior_pkey PRIMARY KEY (posterior_id)
);

CREATE TABLE analysis.option_history_canary (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.option_history_canary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    model_revision text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT option_history_canary_model_revision_started_at_key UNIQUE (model_revision, started_at),
    CONSTRAINT option_history_canary_pkey PRIMARY KEY (id)
);

CREATE TABLE analysis.option_recovery_cohort (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    objective_version text NOT NULL,
    code_version text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    status text DEFAULT 'collecting'::text NOT NULL,
    required_qualified_dates integer DEFAULT 5 NOT NULL,
    qualified_at timestamp with time zone,
    blockers jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_option_recovery_cohort_required_dates CHECK ((required_qualified_dates > 0)),
    CONSTRAINT ck_option_recovery_cohort_status CHECK ((status = ANY (ARRAY['collecting'::text, 'qualified'::text, 'retired'::text]))),
    CONSTRAINT option_recovery_cohort_objective_version_code_version_key UNIQUE (objective_version, code_version),
    CONSTRAINT option_recovery_cohort_pkey PRIMARY KEY (id)
);

CREATE TABLE analysis.phase4_allocation_signing_secret (
    singleton boolean DEFAULT true NOT NULL,
    secret bytea NOT NULL,
    installed_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT phase4_allocation_signing_secret_secret_check CHECK ((length(secret) >= 16)),
    CONSTRAINT phase4_allocation_signing_secret_singleton_check CHECK (singleton),
    CONSTRAINT phase4_allocation_signing_secret_pkey PRIMARY KEY (singleton)
);

CREATE TABLE analysis.portfolio_allocation_snapshot (
    allocation_id text NOT NULL,
    as_of timestamp with time zone NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    status text NOT NULL,
    cash_hurdle double precision,
    forecast_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    action_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    strategy_registry_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    input_hash character(64) NOT NULL,
    content_hash character(64) NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT portfolio_allocation_snapshot_action_ids_check CHECK ((jsonb_typeof(action_ids) = 'array'::text)),
    CONSTRAINT portfolio_allocation_snapshot_cash_hurdle_check CHECK (((cash_hurdle IS NULL) OR ((cash_hurdle < 'Infinity'::double precision) AND (cash_hurdle > '-Infinity'::double precision) AND (cash_hurdle >= (0)::double precision)))),
    CONSTRAINT portfolio_allocation_snapshot_check CHECK ((as_of = input_cutoff)),
    CONSTRAINT portfolio_allocation_snapshot_check1 CHECK (((status <> 'available'::text) OR (cash_hurdle > (0)::double precision))),
    CONSTRAINT portfolio_allocation_snapshot_check2 CHECK ((allocation_id = ('allocation:'::text || (input_hash)::text))),
    CONSTRAINT portfolio_allocation_snapshot_content_hash_check CHECK (((content_hash ~ '^[0-9a-f]{64}$'::text) AND ((content_hash)::text <> repeat('0'::text, 64)))),
    CONSTRAINT portfolio_allocation_snapshot_forecast_ids_check CHECK ((jsonb_typeof(forecast_ids) = 'array'::text)),
    CONSTRAINT portfolio_allocation_snapshot_input_hash_check CHECK (((input_hash ~ '^[0-9a-f]{64}$'::text) AND ((input_hash)::text <> repeat('0'::text, 64)))),
    CONSTRAINT portfolio_allocation_snapshot_status_check CHECK ((status = ANY (ARRAY['available'::text, 'cash_only'::text, 'unavailable'::text]))),
    CONSTRAINT portfolio_allocation_snapshot_strategy_registry_ids_check CHECK ((jsonb_typeof(strategy_registry_ids) = 'array'::text)),
    CONSTRAINT portfolio_allocation_snapshot_pkey PRIMARY KEY (allocation_id)
);

CREATE TABLE analysis.research_evaluator_signing_secret (
    singleton boolean DEFAULT true NOT NULL,
    secret bytea NOT NULL,
    installed_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT research_evaluator_signing_secret_secret_check CHECK ((length(secret) >= 16)),
    CONSTRAINT research_evaluator_signing_secret_singleton_check CHECK (singleton),
    CONSTRAINT research_evaluator_signing_secret_pkey PRIMARY KEY (singleton)
);

CREATE TABLE analysis.ticker_benchmark_snapshot (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    benchmark_key text NOT NULL,
    as_of timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    membership_hash character(64) NOT NULL,
    member_count integer NOT NULL,
    source_id text NOT NULL,
    source_version text,
    exact_membership jsonb DEFAULT '[]'::jsonb NOT NULL,
    coverage jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ticker_benchmark_snapshot_member_count_check CHECK ((member_count >= 0)),
    CONSTRAINT ticker_benchmark_snapshot_benchmark_key_as_of_key UNIQUE (benchmark_key, as_of),
    CONSTRAINT ticker_benchmark_snapshot_pkey PRIMARY KEY (id)
);

CREATE TABLE app.decision_inbox_sync_state (
    state_key text NOT NULL,
    activated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT decision_inbox_sync_state_pkey PRIMARY KEY (state_key)
);

CREATE TABLE app.manual_account_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME app.manual_account_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    account_key text DEFAULT 'manual'::text NOT NULL,
    currency text DEFAULT 'USD'::text NOT NULL,
    effective_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    cash_balance numeric(20,4) NOT NULL,
    net_liquidation numeric(20,4),
    reconciliation_state text NOT NULL,
    reconciliation_version integer NOT NULL,
    ledger_book_identity text NOT NULL,
    idempotency_key text NOT NULL,
    notes text DEFAULT ''::text NOT NULL,
    CONSTRAINT manual_account_snapshot_cash_balance_check CHECK ((cash_balance >= (0)::numeric)),
    CONSTRAINT manual_account_snapshot_currency_check CHECK ((currency = 'USD'::text)),
    CONSTRAINT manual_account_snapshot_net_liquidation_check CHECK ((net_liquidation >= (0)::numeric)),
    CONSTRAINT manual_account_snapshot_reconciliation_state_check CHECK ((reconciliation_state = ANY (ARRAY['pending'::text, 'reconciled'::text]))),
    CONSTRAINT manual_account_snapshot_reconciliation_version_check CHECK ((reconciliation_version > 0)),
    CONSTRAINT manual_account_snapshot_idempotency_key_key UNIQUE (idempotency_key),
    CONSTRAINT manual_account_snapshot_pkey PRIMARY KEY (id)
);

CREATE TABLE app.publication_bundle (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    scope text NOT NULL,
    bundle_hash character(64) NOT NULL,
    item_count integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT publication_bundle_item_count_check CHECK ((item_count >= 0)),
    CONSTRAINT publication_bundle_pkey PRIMARY KEY (id),
    CONSTRAINT publication_bundle_scope_bundle_hash_key UNIQUE (scope, bundle_hash)
);

CREATE TABLE app.publication_payload (
    content_hash character(64) NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT publication_payload_pkey PRIMARY KEY (content_hash)
);

CREATE TABLE app.setting (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT setting_pkey PRIMARY KEY (key)
);

CREATE TABLE catalog.instrument (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME catalog.instrument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    symbol text NOT NULL,
    name text,
    asset_class text NOT NULL,
    sector text,
    industry text,
    category text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    market_timezone text DEFAULT 'America/New_York'::text NOT NULL,
    delisted_at timestamp with time zone,
    delisting_price double precision,
    delisting_available_at timestamp with time zone,
    delisting_source text,
    CONSTRAINT ck_instrument_delisting_availability CHECK (((delisting_available_at IS NULL) OR (delisted_at IS NOT NULL))),
    CONSTRAINT ck_instrument_delisting_price CHECK (((delisting_price IS NULL) OR (delisting_price > (0)::double precision))),
    CONSTRAINT instrument_pkey PRIMARY KEY (id),
    CONSTRAINT instrument_symbol_key UNIQUE (symbol)
);

CREATE TABLE ingest.source (
    id text NOT NULL,
    name text NOT NULL,
    family text NOT NULL,
    kind text NOT NULL,
    origin text,
    enabled boolean DEFAULT true NOT NULL,
    ingestion_mode text,
    source_url text,
    capabilities jsonb DEFAULT '{}'::jsonb NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    operational_state text DEFAULT 'archived'::text NOT NULL,
    health_owner text,
    freshness_seconds integer,
    CONSTRAINT ck_ingest_source_active_health_contract CHECK (((operational_state <> 'active'::text) OR ((health_owner IS NOT NULL) AND (freshness_seconds IS NOT NULL)))),
    CONSTRAINT ck_ingest_source_freshness_seconds CHECK (((freshness_seconds IS NULL) OR (freshness_seconds > 0))),
    CONSTRAINT ck_ingest_source_operational_state CHECK ((operational_state = ANY (ARRAY['active'::text, 'standby'::text, 'archived'::text]))),
    CONSTRAINT source_pkey PRIMARY KEY (id)
);

CREATE TABLE ops.job_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_name text NOT NULL,
    status text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    error text,
    summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    heartbeat_at timestamp with time zone DEFAULT now() NOT NULL,
    scheduled_due_at timestamp with time zone,
    dispatched_at timestamp with time zone,
    source_status text,
    downstream_status text,
    CONSTRAINT job_run_status_check CHECK ((status = ANY (ARRAY['running'::text, 'succeeded'::text, 'partial'::text, 'failed'::text, 'skipped'::text]))),
    CONSTRAINT job_run_pkey PRIMARY KEY (id)
);

CREATE TABLE ops.option_quote_partition_policy (
    policy_key text NOT NULL,
    daily_start date NOT NULL,
    hot_retention_days integer DEFAULT 7 NOT NULL,
    archive_retention_days integer DEFAULT 730 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT option_quote_partition_policy_pkey PRIMARY KEY (policy_key)
);

CREATE TABLE ops.provider_lease (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME ops.provider_lease_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    provider text NOT NULL,
    workload text NOT NULL,
    symbol text NOT NULL,
    owner text NOT NULL,
    heartbeat_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    acquired_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT provider_lease_pkey PRIMARY KEY (id)
);

CREATE TABLE ops.storage_archive_checkpoint (
    checkpoint_key text NOT NULL,
    archive_kind text NOT NULL,
    source_relation text NOT NULL,
    cursor jsonb DEFAULT '{}'::jsonb NOT NULL,
    run_status text DEFAULT 'idle'::text NOT NULL,
    counts jsonb DEFAULT '{}'::jsonb NOT NULL,
    error_detail text,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT storage_archive_checkpoint_run_status_check CHECK ((run_status = ANY (ARRAY['idle'::text, 'running'::text, 'paused'::text, 'succeeded'::text, 'failed'::text]))),
    CONSTRAINT storage_archive_checkpoint_pkey PRIMARY KEY (checkpoint_key)
);

CREATE TABLE ops.storage_archive_manifest (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME ops.storage_archive_manifest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    archive_kind text NOT NULL,
    source_relation text NOT NULL,
    nas_uri text NOT NULL,
    sha256 character(64) NOT NULL,
    format text NOT NULL,
    row_count bigint DEFAULT 0 NOT NULL,
    range_start timestamp with time zone,
    range_end timestamp with time zone,
    schema_revision text NOT NULL,
    verification_status text DEFAULT 'pending'::text NOT NULL,
    verified_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT storage_archive_manifest_row_count_check CHECK ((row_count >= 0)),
    CONSTRAINT storage_archive_manifest_verification_status_check CHECK ((verification_status = ANY (ARRAY['pending'::text, 'written'::text, 'verified'::text, 'failed'::text, 'restored'::text]))),
    CONSTRAINT storage_archive_manifest_archive_kind_sha256_key UNIQUE (archive_kind, sha256),
    CONSTRAINT storage_archive_manifest_nas_uri_key UNIQUE (nas_uri),
    CONSTRAINT storage_archive_manifest_pkey PRIMARY KEY (id)
);

CREATE TABLE raw.price_bar_history (
    id bigint CONSTRAINT price_bar_id_not_null NOT NULL,
    instrument_id bigint CONSTRAINT price_bar_instrument_id_not_null NOT NULL,
    source_id text CONSTRAINT price_bar_source_id_not_null NOT NULL,
    ingest_run_id uuid CONSTRAINT price_bar_ingest_run_id_not_null NOT NULL,
    payload_id bigint,
    "interval" text DEFAULT '1d'::text CONSTRAINT price_bar_interval_not_null NOT NULL,
    trading_date date CONSTRAINT price_bar_trading_date_not_null NOT NULL,
    observed_at timestamp with time zone CONSTRAINT price_bar_observed_at_not_null NOT NULL,
    open double precision,
    high double precision,
    low double precision,
    close double precision CONSTRAINT price_bar_close_not_null NOT NULL,
    volume double precision,
    currency text,
    available_at timestamp with time zone DEFAULT clock_timestamp() CONSTRAINT price_bar_available_at_not_null NOT NULL
);

CREATE TABLE raw.quote_history (
    id bigint CONSTRAINT quote_id_not_null NOT NULL,
    instrument_id bigint CONSTRAINT quote_instrument_id_not_null NOT NULL,
    source_id text CONSTRAINT quote_source_id_not_null NOT NULL,
    ingest_run_id uuid CONSTRAINT quote_ingest_run_id_not_null NOT NULL,
    payload_id bigint,
    observed_at timestamp with time zone CONSTRAINT quote_observed_at_not_null NOT NULL,
    price double precision CONSTRAINT quote_price_not_null NOT NULL,
    change_abs double precision,
    change_pct double precision,
    currency text,
    available_at timestamp with time zone DEFAULT clock_timestamp() CONSTRAINT quote_available_at_not_null NOT NULL
);
