-- Tables: option and research structures.

CREATE TABLE analysis.option_event_contract (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.option_event_contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    event_id uuid NOT NULL,
    contract_id bigint,
    contract_key text NOT NULL,
    option_type text NOT NULL,
    expiration date NOT NULL,
    target_delta double precision NOT NULL,
    is_initial boolean DEFAULT false NOT NULL,
    replaces_contract_id bigint,
    initial_capture_generation_id bigint,
    added_at timestamp with time zone DEFAULT now() NOT NULL,
    retired_at timestamp with time zone,
    reason text,
    ladder_slot_key text NOT NULL,
    retired_reason text,
    CONSTRAINT ck_option_event_contract_type CHECK ((option_type = ANY (ARRAY['call'::text, 'put'::text]))),
    CONSTRAINT option_event_contract_event_id_contract_key_key UNIQUE (event_id, contract_key),
    CONSTRAINT option_event_contract_pkey PRIMARY KEY (id),
    CONSTRAINT option_event_contract_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES catalog.option_contract(id) ON DELETE RESTRICT,
    CONSTRAINT option_event_contract_event_id_fkey FOREIGN KEY (event_id) REFERENCES analysis.option_event(id) ON DELETE CASCADE,
    CONSTRAINT option_event_contract_initial_capture_generation_id_fkey FOREIGN KEY (initial_capture_generation_id) REFERENCES raw.option_capture_generation(id) ON DELETE SET NULL,
    CONSTRAINT option_event_contract_replaces_contract_id_fkey FOREIGN KEY (replaces_contract_id) REFERENCES analysis.option_event_contract(id) ON DELETE RESTRICT
);

CREATE TABLE analysis.option_liquidity_sla (
    sla_id text NOT NULL,
    as_of timestamp with time zone NOT NULL,
    source_id text NOT NULL,
    ingest_run_id uuid NOT NULL,
    payload_hash text NOT NULL,
    parent_snapshot_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    payload_id bigint NOT NULL,
    CONSTRAINT option_liquidity_sla_pkey PRIMARY KEY (sla_id),
    CONSTRAINT option_liquidity_sla_ingest_run_id_fkey FOREIGN KEY (ingest_run_id) REFERENCES ingest.run(id),
    CONSTRAINT option_liquidity_sla_payload_id_fkey FOREIGN KEY (payload_id) REFERENCES ingest.payload(id),
    CONSTRAINT option_liquidity_sla_source_id_fkey FOREIGN KEY (source_id) REFERENCES ingest.source(id)
);

CREATE TABLE analysis.run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    run_type text NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    code_version text NOT NULL,
    feature_versions jsonb DEFAULT '{}'::jsonb NOT NULL,
    strategy_revision_id bigint,
    input_hash character(64) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    status text NOT NULL,
    summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    inputs jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT run_status_check CHECK ((status = ANY (ARRAY['running'::text, 'succeeded'::text, 'partial'::text, 'failed'::text]))),
    CONSTRAINT run_pkey PRIMARY KEY (id),
    CONSTRAINT run_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id)
);

CREATE TABLE analysis.strategy_manifest (
    strategy_revision_id bigint NOT NULL,
    source_definition_version text NOT NULL,
    source_manifest jsonb NOT NULL,
    data_manifest jsonb NOT NULL,
    cost_manifest jsonb NOT NULL,
    capacity_manifest jsonb NOT NULL,
    failure_manifest jsonb NOT NULL,
    manifest_hash character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT strategy_manifest_capacity_manifest_check CHECK (((jsonb_typeof(capacity_manifest) = 'object'::text) AND (capacity_manifest <> '{}'::jsonb))),
    CONSTRAINT strategy_manifest_cost_manifest_check CHECK (((jsonb_typeof(cost_manifest) = 'object'::text) AND (cost_manifest <> '{}'::jsonb))),
    CONSTRAINT strategy_manifest_data_manifest_check CHECK (((jsonb_typeof(data_manifest) = 'object'::text) AND (data_manifest <> '{}'::jsonb))),
    CONSTRAINT strategy_manifest_failure_manifest_check CHECK (((jsonb_typeof(failure_manifest) = 'object'::text) AND (failure_manifest <> '{}'::jsonb))),
    CONSTRAINT strategy_manifest_manifest_hash_check CHECK ((manifest_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT strategy_manifest_source_manifest_check CHECK (((jsonb_typeof(source_manifest) = 'object'::text) AND (source_manifest <> '{}'::jsonb))),
    CONSTRAINT strategy_manifest_pkey PRIMARY KEY (strategy_revision_id),
    CONSTRAINT strategy_manifest_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id)
);

CREATE TABLE analysis.trial_result (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    research_trial_id uuid NOT NULL,
    result_kind text NOT NULL,
    result_version integer DEFAULT 1 NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    outcome jsonb DEFAULT '{}'::jsonb NOT NULL,
    input_hash character(64) NOT NULL,
    CONSTRAINT trial_result_check CHECK ((available_at <= observed_at)),
    CONSTRAINT trial_result_result_version_check CHECK ((result_version > 0)),
    CONSTRAINT trial_result_pkey PRIMARY KEY (id),
    CONSTRAINT trial_result_research_trial_id_result_kind_result_version_key UNIQUE (research_trial_id, result_kind, result_version),
    CONSTRAINT trial_result_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id)
);

CREATE TABLE analysis.trial_universe_manifest (
    research_trial_id uuid NOT NULL,
    cutoff timestamp with time zone NOT NULL,
    expected_member_count integer NOT NULL,
    expected_members jsonb NOT NULL,
    manifest_hash character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    available_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT trial_universe_manifest_expected_member_count_check CHECK (((expected_member_count >= 0) AND (expected_member_count <= 10000))),
    CONSTRAINT trial_universe_manifest_expected_members_check CHECK ((jsonb_typeof(expected_members) = 'array'::text)),
    CONSTRAINT trial_universe_manifest_pkey PRIMARY KEY (research_trial_id),
    CONSTRAINT trial_universe_manifest_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id)
);

CREATE TABLE analysis.universe_observation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    research_trial_id uuid NOT NULL,
    instrument_id bigint NOT NULL,
    cutoff timestamp with time zone NOT NULL,
    eligible boolean NOT NULL,
    rank integer,
    candidate_score double precision,
    exclusion_reason text,
    observed_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    input_hash character(64) NOT NULL,
    outcome jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT universe_observation_check CHECK ((eligible OR (exclusion_reason IS NOT NULL))),
    CONSTRAINT universe_observation_rank_check CHECK (((rank IS NULL) OR (rank > 0))),
    CONSTRAINT universe_observation_pkey PRIMARY KEY (id),
    CONSTRAINT universe_observation_research_trial_id_cutoff_instrument_id_key UNIQUE (research_trial_id, cutoff, instrument_id),
    CONSTRAINT universe_observation_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT universe_observation_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id)
);

CREATE TABLE analysis.validation_dossier (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    strategy_revision_id bigint NOT NULL,
    research_trial_id uuid,
    status text DEFAULT 'draft'::text NOT NULL,
    sections jsonb DEFAULT '{}'::jsonb NOT NULL,
    compiled_policy jsonb DEFAULT '{}'::jsonb NOT NULL,
    artifact_id text,
    artifact_hash character(64),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sealed_at timestamp with time zone,
    CONSTRAINT validation_dossier_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'sealed'::text, 'rejected'::text]))),
    CONSTRAINT validation_dossier_pkey PRIMARY KEY (id),
    CONSTRAINT validation_dossier_strategy_revision_id_key UNIQUE (strategy_revision_id),
    CONSTRAINT validation_dossier_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id),
    CONSTRAINT validation_dossier_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id)
);

CREATE TABLE raw.broker_position_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME raw.broker_position_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    account_snapshot_id bigint NOT NULL,
    instrument_id bigint NOT NULL,
    quantity numeric(24,8) NOT NULL,
    average_cost numeric(20,6),
    market_price numeric(20,6),
    market_value numeric(24,4),
    unrealized_pnl numeric(24,4),
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT broker_position_snapshot_account_snapshot_id_instrument_id_key UNIQUE (account_snapshot_id, instrument_id),
    CONSTRAINT broker_position_snapshot_pkey PRIMARY KEY (id),
    CONSTRAINT broker_position_snapshot_account_snapshot_id_fkey FOREIGN KEY (account_snapshot_id) REFERENCES raw.broker_account_snapshot(id) ON DELETE CASCADE,
    CONSTRAINT broker_position_snapshot_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id)
);

CREATE TABLE raw.content_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME raw.content_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    source_id text NOT NULL,
    ingest_run_id uuid NOT NULL,
    payload_id bigint,
    source_key text NOT NULL,
    kind text NOT NULL,
    title text,
    url text,
    author text,
    published_at timestamp with time zone,
    observed_at timestamp with time zone NOT NULL,
    summary text,
    content_hash character(64),
    license_status text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT content_item_pkey PRIMARY KEY (id),
    CONSTRAINT content_item_source_id_source_key_key UNIQUE (source_id, source_key),
    CONSTRAINT content_item_ingest_run_id_fkey FOREIGN KEY (ingest_run_id) REFERENCES ingest.run(id),
    CONSTRAINT content_item_payload_id_fkey FOREIGN KEY (payload_id) REFERENCES ingest.payload(id),
    CONSTRAINT content_item_source_id_fkey FOREIGN KEY (source_id) REFERENCES ingest.source(id)
);

CREATE TABLE raw.disclosure (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME raw.disclosure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    instrument_id bigint,
    source_id text NOT NULL,
    ingest_run_id uuid NOT NULL,
    payload_id bigint,
    source_key text NOT NULL,
    source_type text NOT NULL,
    trader_name text,
    filer_name text,
    event_date date,
    filed_date date,
    action text,
    amount_text text,
    source_url text,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT disclosure_pkey PRIMARY KEY (id),
    CONSTRAINT disclosure_source_id_source_key_key UNIQUE (source_id, source_key),
    CONSTRAINT disclosure_ingest_run_id_fkey FOREIGN KEY (ingest_run_id) REFERENCES ingest.run(id),
    CONSTRAINT disclosure_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT disclosure_payload_id_fkey FOREIGN KEY (payload_id) REFERENCES ingest.payload(id),
    CONSTRAINT disclosure_source_id_fkey FOREIGN KEY (source_id) REFERENCES ingest.source(id)
);

CREATE TABLE raw.fundamental_observation (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME raw.fundamental_observation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    instrument_id bigint NOT NULL,
    source_id text NOT NULL,
    ingest_run_id uuid NOT NULL,
    payload_id bigint,
    metric_set text NOT NULL,
    period_end date,
    filed_at timestamp with time zone,
    observed_at timestamp with time zone NOT NULL,
    "values" jsonb NOT NULL,
    period_start date,
    CONSTRAINT fundamental_observation_pkey PRIMARY KEY (id),
    CONSTRAINT fundamental_observation_ingest_run_id_fkey FOREIGN KEY (ingest_run_id) REFERENCES ingest.run(id),
    CONSTRAINT fundamental_observation_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT fundamental_observation_payload_id_fkey FOREIGN KEY (payload_id) REFERENCES ingest.payload(id),
    CONSTRAINT fundamental_observation_source_id_fkey FOREIGN KEY (source_id) REFERENCES ingest.source(id)
);

CREATE TABLE raw.market_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME raw.market_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    instrument_id bigint,
    source_id text NOT NULL,
    ingest_run_id uuid NOT NULL,
    payload_id bigint,
    source_key text NOT NULL,
    event_scope text NOT NULL,
    event_kind text NOT NULL,
    title text NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone,
    importance text,
    verification_status text,
    source_url text,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT market_event_pkey PRIMARY KEY (id),
    CONSTRAINT market_event_source_id_source_key_key UNIQUE (source_id, source_key),
    CONSTRAINT market_event_ingest_run_id_fkey FOREIGN KEY (ingest_run_id) REFERENCES ingest.run(id),
    CONSTRAINT market_event_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT market_event_payload_id_fkey FOREIGN KEY (payload_id) REFERENCES ingest.payload(id),
    CONSTRAINT market_event_source_id_fkey FOREIGN KEY (source_id) REFERENCES ingest.source(id)
);

CREATE TABLE raw.market_observation (
    observation_id text NOT NULL,
    field_name text NOT NULL,
    dimension text NOT NULL,
    asset_class text NOT NULL,
    source_id text NOT NULL,
    source_version text NOT NULL,
    value jsonb,
    unit text,
    ingest_run_id uuid NOT NULL,
    payload_id bigint NOT NULL,
    content_hash text NOT NULL,
    parent_snapshot_id text,
    observed_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    publication_at timestamp with time zone,
    release_at timestamp with time zone,
    vintage_at timestamp with time zone,
    actual double precision,
    consensus double precision,
    surprise double precision,
    revision double precision,
    status text NOT NULL,
    confidence double precision NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_market_observation_clocks CHECK ((available_at IS NOT NULL)),
    CONSTRAINT ck_market_observation_status CHECK ((status = ANY (ARRAY['AVAILABLE'::text, 'MISSING_SOURCE'::text, 'MISSING_HISTORY'::text, 'CONFLICTED'::text, 'FALLBACK'::text, 'UNSUPPORTED'::text, 'STALE'::text]))),
    CONSTRAINT market_observation_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision))),
    CONSTRAINT market_observation_pkey PRIMARY KEY (observation_id),
    CONSTRAINT market_observation_ingest_run_id_fkey FOREIGN KEY (ingest_run_id) REFERENCES ingest.run(id),
    CONSTRAINT market_observation_payload_id_fkey FOREIGN KEY (payload_id) REFERENCES ingest.payload(id),
    CONSTRAINT market_observation_source_id_fkey FOREIGN KEY (source_id) REFERENCES ingest.source(id)
);

CREATE TABLE raw.option_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME raw.option_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    source_id text NOT NULL,
    ingest_run_id uuid NOT NULL,
    payload_id bigint,
    observed_at timestamp with time zone NOT NULL,
    trading_date date NOT NULL,
    market_session text NOT NULL,
    universe text NOT NULL,
    completeness double precision,
    contract_count integer DEFAULT 0 NOT NULL,
    collection_profile text DEFAULT 'radar'::text NOT NULL,
    history_symbol text,
    slot_at timestamp with time zone,
    capture_started_at timestamp with time zone,
    capture_finished_at timestamp with time zone,
    expected_contract_count integer,
    received_contract_count integer,
    capture_state text DEFAULT 'complete'::text NOT NULL,
    latest_complete_generation_id bigint,
    CONSTRAINT ck_option_snapshot_capture_state CHECK ((capture_state = ANY (ARRAY['running'::text, 'complete'::text, 'partial'::text, 'failed'::text, 'deferred'::text]))),
    CONSTRAINT ck_option_snapshot_profile CHECK ((collection_profile = ANY (ARRAY['radar'::text, 'history_full'::text, 'event_strip'::text]))),
    CONSTRAINT option_snapshot_completeness_check CHECK (((completeness >= (0)::double precision) AND (completeness <= (1)::double precision))),
    CONSTRAINT option_snapshot_market_session_check CHECK ((market_session = ANY (ARRAY['premarket'::text, 'regular'::text, 'afterhours'::text, 'closed'::text, 'unknown'::text]))),
    CONSTRAINT option_snapshot_pkey PRIMARY KEY (id),
    CONSTRAINT option_snapshot_source_id_observed_at_universe_key UNIQUE (source_id, observed_at, universe),
    CONSTRAINT option_snapshot_ingest_run_id_fkey FOREIGN KEY (ingest_run_id) REFERENCES ingest.run(id),
    CONSTRAINT option_snapshot_payload_id_fkey FOREIGN KEY (payload_id) REFERENCES ingest.payload(id),
    CONSTRAINT option_snapshot_source_id_fkey FOREIGN KEY (source_id) REFERENCES ingest.source(id)
);
