-- Tables: decisions, studies, and analytical outputs.

CREATE TABLE analysis.decision (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    run_id uuid NOT NULL,
    decision_key text NOT NULL,
    kind text NOT NULL,
    instrument_id bigint NOT NULL,
    as_of timestamp with time zone NOT NULL,
    state text NOT NULL,
    rank integer,
    score double precision,
    quality_status text,
    strategy_revision_id bigint,
    reasons text[] DEFAULT '{}'::text[] NOT NULL,
    blockers text[] DEFAULT '{}'::text[] NOT NULL,
    input_hash character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    lane text,
    episode_key text,
    sample_eligible boolean DEFAULT false NOT NULL,
    quarantine_reason text,
    calibration_cohort text,
    CONSTRAINT decision_pkey PRIMARY KEY (id),
    CONSTRAINT decision_run_id_decision_key_key UNIQUE (run_id, decision_key),
    CONSTRAINT decision_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT decision_run_id_fkey FOREIGN KEY (run_id) REFERENCES analysis.run(id) ON DELETE CASCADE,
    CONSTRAINT decision_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id)
);

CREATE TABLE analysis.option_discovery_run (
    run_id uuid NOT NULL,
    universe_hash text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    provider text,
    market_session text,
    symbols_considered integer DEFAULT 0 NOT NULL,
    symbols_with_chains integer DEFAULT 0 NOT NULL,
    contracts_evaluated integer DEFAULT 0 NOT NULL,
    manifest jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT option_discovery_run_pkey PRIMARY KEY (run_id),
    CONSTRAINT option_discovery_run_run_id_fkey FOREIGN KEY (run_id) REFERENCES analysis.run(id) ON DELETE CASCADE
);

CREATE TABLE analysis.option_event_capture (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    snapshot_id bigint,
    capture_generation_id bigint,
    scheduled_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    status text NOT NULL,
    expected_contract_count integer DEFAULT 0 NOT NULL,
    received_contract_count integer DEFAULT 0 NOT NULL,
    completeness double precision,
    continuity_pct double precision,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    canonical_continuity_pct double precision,
    original_continuity_pct double precision,
    CONSTRAINT ck_option_event_capture_status CHECK ((status = ANY (ARRAY['complete'::text, 'partial'::text, 'failed'::text, 'deferred'::text]))),
    CONSTRAINT option_event_capture_event_id_scheduled_at_key UNIQUE (event_id, scheduled_at),
    CONSTRAINT option_event_capture_pkey PRIMARY KEY (id),
    CONSTRAINT option_event_capture_capture_generation_id_fkey FOREIGN KEY (capture_generation_id) REFERENCES raw.option_capture_generation(id) ON DELETE SET NULL,
    CONSTRAINT option_event_capture_event_id_fkey FOREIGN KEY (event_id) REFERENCES analysis.option_event(id) ON DELETE CASCADE,
    CONSTRAINT option_event_capture_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES raw.option_snapshot(id) ON DELETE SET NULL
);

CREATE TABLE analysis.option_feature (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.option_feature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    run_id uuid NOT NULL,
    snapshot_id bigint NOT NULL,
    contract_id bigint NOT NULL,
    quote_observed_at timestamp with time zone NOT NULL,
    feature_version text NOT NULL,
    modeled_iv double precision,
    modeled_delta double precision,
    modeled_gamma double precision,
    modeled_theta double precision,
    modeled_vega double precision,
    dte integer,
    spread_pct double precision,
    iv_rank double precision,
    iv_percentile double precision,
    liquidity_score double precision,
    flow_score double precision,
    convexity_score double precision,
    required_2x_price double precision,
    required_5x_price double precision,
    required_10x_price double precision,
    required_move_pct double precision,
    ev_inputs jsonb DEFAULT '{}'::jsonb NOT NULL,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT option_feature_pkey PRIMARY KEY (id),
    CONSTRAINT option_feature_run_id_snapshot_id_contract_id_feature_versi_key UNIQUE (run_id, snapshot_id, contract_id, feature_version),
    CONSTRAINT option_feature_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES catalog.option_contract(id),
    CONSTRAINT option_feature_run_id_fkey FOREIGN KEY (run_id) REFERENCES analysis.run(id) ON DELETE CASCADE,
    CONSTRAINT option_feature_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES raw.option_snapshot(id)
);

CREATE TABLE analysis.option_history_anomaly (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.option_history_anomaly_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    snapshot_id bigint NOT NULL,
    contract_id bigint,
    expiration date,
    option_type text,
    anomaly_type text NOT NULL,
    state text NOT NULL,
    observed_value double precision,
    expected_value double precision,
    z_score double precision,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    feature_version text DEFAULT 'history-v2'::text NOT NULL,
    CONSTRAINT option_history_anomaly_option_type_check CHECK ((option_type = ANY (ARRAY['call'::text, 'put'::text]))),
    CONSTRAINT option_history_anomaly_state_check CHECK ((state = ANY (ARRAY['active'::text, 'collecting'::text]))),
    CONSTRAINT option_history_anomaly_pkey PRIMARY KEY (id),
    CONSTRAINT option_history_anomaly_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES catalog.option_contract(id),
    CONSTRAINT option_history_anomaly_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES raw.option_snapshot(id) ON DELETE CASCADE
);

CREATE TABLE analysis.option_relative_value (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.option_relative_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    analysis_run_id uuid NOT NULL,
    capture_generation_id bigint NOT NULL,
    contract_id bigint NOT NULL,
    model_revision text NOT NULL,
    classification text NOT NULL,
    fair_low double precision,
    fair_high double precision,
    modeled_net_edge double precision,
    edge_side text,
    confidence double precision,
    quality_status text NOT NULL,
    blockers text[] DEFAULT '{}'::text[] NOT NULL,
    evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT option_relative_value_classification_check CHECK ((classification = ANY (ARRAY['relative_cheap'::text, 'relative_rich'::text, 'historical_static_arbitrage_candidate'::text, 'verified_static_arbitrage_candidate'::text, 'rejected'::text]))),
    CONSTRAINT option_relative_value_analysis_run_id_capture_generation_id_key UNIQUE (analysis_run_id, capture_generation_id, contract_id, model_revision),
    CONSTRAINT option_relative_value_pkey PRIMARY KEY (id),
    CONSTRAINT option_relative_value_capture_generation_id_fkey FOREIGN KEY (capture_generation_id) REFERENCES raw.option_capture_generation(id) ON DELETE RESTRICT,
    CONSTRAINT option_relative_value_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES catalog.option_contract(id)
);

CREATE TABLE analysis.option_surface_shift (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    instrument_id bigint NOT NULL,
    current_capture_generation_id bigint NOT NULL,
    previous_capture_generation_id bigint NOT NULL,
    current_analysis_run_id uuid NOT NULL,
    previous_analysis_run_id uuid NOT NULL,
    as_of timestamp with time zone NOT NULL,
    previous_as_of timestamp with time zone,
    feature_version text NOT NULL,
    tenors integer[] DEFAULT ARRAY[7, 14, 30, 60, 90] NOT NULL,
    w1_shift double precision,
    tail_mass_change double precision,
    skew_shift double precision,
    term_shift double precision,
    evidence_state text NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_surface_shift_evidence_state CHECK ((evidence_state = ANY (ARRAY['ready'::text, 'insufficient_surface_evidence'::text, 'unavailable'::text]))),
    CONSTRAINT option_surface_shift_current_analysis_run_id_previous_analy_key UNIQUE (current_analysis_run_id, previous_analysis_run_id, feature_version),
    CONSTRAINT option_surface_shift_pkey PRIMARY KEY (id),
    CONSTRAINT option_surface_shift_current_capture_generation_id_fkey FOREIGN KEY (current_capture_generation_id) REFERENCES raw.option_capture_generation(id),
    CONSTRAINT option_surface_shift_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id) ON DELETE RESTRICT,
    CONSTRAINT option_surface_shift_previous_capture_generation_id_fkey FOREIGN KEY (previous_capture_generation_id) REFERENCES raw.option_capture_generation(id)
);

CREATE TABLE analysis.option_surface_summary (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.option_surface_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    snapshot_id bigint NOT NULL,
    expiration date NOT NULL,
    option_type text NOT NULL,
    feature_version text NOT NULL,
    dte integer NOT NULL,
    atm_iv double precision,
    delta_25_iv double precision,
    skew_25 double precision,
    smile_slope double precision,
    smile_curvature double precision,
    term_slope double precision,
    average_spread_pct double precision,
    liquidity_score double precision,
    atm_iv_change double precision,
    skew_25_change double precision,
    term_slope_change double precision,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    analysis_run_id uuid,
    capture_generation_id bigint,
    fit_method text,
    fit_status text,
    eligible_point_count integer,
    group_duration_seconds double precision,
    max_quote_age_seconds double precision,
    fit_rmse double precision,
    candidate_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT option_surface_summary_option_type_check CHECK ((option_type = ANY (ARRAY['call'::text, 'put'::text]))),
    CONSTRAINT option_surface_summary_pkey PRIMARY KEY (id),
    CONSTRAINT option_surface_summary_capture_generation_id_fkey FOREIGN KEY (capture_generation_id) REFERENCES raw.option_capture_generation(id),
    CONSTRAINT option_surface_summary_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES raw.option_snapshot(id) ON DELETE CASCADE
);

-- PostgreSQL requires post-creation statements for NOT VALID and cyclic FKs.

CREATE TABLE analysis.reject_summary (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.reject_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    run_id uuid NOT NULL,
    strategy_revision_id bigint,
    instrument_id bigint,
    gate_code text NOT NULL,
    reject_count integer NOT NULL,
    sampled_decision_keys text[] DEFAULT '{}'::text[] NOT NULL,
    CONSTRAINT reject_summary_reject_count_check CHECK ((reject_count >= 0)),
    CONSTRAINT reject_summary_pkey PRIMARY KEY (id),
    CONSTRAINT reject_summary_run_id_strategy_revision_id_instrument_id_ga_key UNIQUE (run_id, strategy_revision_id, instrument_id, gate_code),
    CONSTRAINT reject_summary_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT reject_summary_run_id_fkey FOREIGN KEY (run_id) REFERENCES analysis.run(id) ON DELETE CASCADE,
    CONSTRAINT reject_summary_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id)
);

CREATE TABLE analysis.research_evaluator_output (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    research_trial_id uuid NOT NULL,
    trial_result_id uuid NOT NULL,
    analysis_run_id uuid NOT NULL,
    evidence_kind text NOT NULL,
    evaluator_id text NOT NULL,
    evaluator_code_version text NOT NULL,
    input_hash character(64) NOT NULL,
    universe_hash character(64) NOT NULL,
    feature_hash character(64) NOT NULL,
    sample_count integer NOT NULL,
    domain_valid boolean NOT NULL,
    raw_output jsonb NOT NULL,
    output_hash character(64) DEFAULT repeat('0'::text, 64) NOT NULL,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    signature text DEFAULT ''::text NOT NULL,
    CONSTRAINT research_evaluator_output_check CHECK ((available_at >= created_at)),
    CONSTRAINT research_evaluator_output_evidence_kind_check CHECK ((evidence_kind = ANY (ARRAY['controls'::text, 'cpcv_paths'::text, 'neutralization'::text, 'parameter_stability'::text, 'mechanism_falsification'::text, 'multiple_testing'::text]))),
    CONSTRAINT research_evaluator_output_feature_hash_check CHECK (((feature_hash ~ '^[0-9a-fA-F]{64}$'::text) AND (lower((feature_hash)::text) <> repeat('0'::text, 64)))),
    CONSTRAINT research_evaluator_output_input_hash_check CHECK (((input_hash ~ '^[0-9a-fA-F]{64}$'::text) AND (lower((input_hash)::text) <> repeat('0'::text, 64)))),
    CONSTRAINT research_evaluator_output_raw_output_check CHECK ((jsonb_typeof(raw_output) = 'object'::text)),
    CONSTRAINT research_evaluator_output_sample_count_check CHECK ((sample_count > 0)),
    CONSTRAINT research_evaluator_output_universe_hash_check CHECK (((universe_hash ~ '^[0-9a-fA-F]{64}$'::text) AND (lower((universe_hash)::text) <> repeat('0'::text, 64)))),
    CONSTRAINT research_evaluator_output_pkey PRIMARY KEY (id),
    CONSTRAINT research_evaluator_output_trial_result_id_evidence_kind_key UNIQUE (trial_result_id, evidence_kind),
    CONSTRAINT research_evaluator_output_analysis_run_id_fkey FOREIGN KEY (analysis_run_id) REFERENCES analysis.run(id),
    CONSTRAINT research_evaluator_output_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id),
    CONSTRAINT research_evaluator_output_trial_result_id_fkey FOREIGN KEY (trial_result_id) REFERENCES analysis.trial_result(id)
);

CREATE TABLE analysis.source_signal (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.source_signal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    run_id uuid NOT NULL,
    content_item_id bigint NOT NULL,
    instrument_id bigint NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    signal_type text NOT NULL,
    sentiment text,
    direction text,
    confidence double precision,
    thesis text,
    antithesis text,
    invalidation text,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    event_at timestamp with time zone,
    published_at timestamp with time zone,
    available_at timestamp with time zone,
    received_at timestamp with time zone,
    revision text,
    license text,
    evidence_state text,
    transformation text,
    CONSTRAINT source_signal_pkey PRIMARY KEY (id),
    CONSTRAINT source_signal_run_id_content_item_id_instrument_id_signal_t_key UNIQUE (run_id, content_item_id, instrument_id, signal_type),
    CONSTRAINT source_signal_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES raw.content_item(id),
    CONSTRAINT source_signal_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT source_signal_run_id_fkey FOREIGN KEY (run_id) REFERENCES analysis.run(id) ON DELETE CASCADE
);

CREATE TABLE analysis.strategy_comparison (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    champion_revision_id bigint NOT NULL,
    challenger_revision_id bigint NOT NULL,
    champion_trial_id uuid NOT NULL,
    challenger_trial_id uuid NOT NULL,
    champion_result_id uuid NOT NULL,
    challenger_result_id uuid NOT NULL,
    champion_result_hash character(64) NOT NULL,
    challenger_result_hash character(64) NOT NULL,
    champion_manifest_hash character(64) NOT NULL,
    challenger_manifest_hash character(64) NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    input_hash character(64) NOT NULL,
    distinctness text NOT NULL,
    explanation text NOT NULL,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT strategy_comparison_check CHECK ((champion_revision_id <> challenger_revision_id)),
    CONSTRAINT strategy_comparison_check1 CHECK (((available_at <= observed_at) AND (available_at <= input_cutoff))),
    CONSTRAINT strategy_comparison_distinctness_check CHECK ((distinctness = ANY (ARRAY['distinct'::text, 'replica'::text, 'exposure_sleeve'::text, 'inconclusive'::text, 'blocked'::text]))),
    CONSTRAINT strategy_comparison_input_hash_check CHECK ((input_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT strategy_comparison_champion_revision_id_challenger_revisio_key UNIQUE (champion_revision_id, challenger_revision_id, input_cutoff, input_hash),
    CONSTRAINT strategy_comparison_pkey PRIMARY KEY (id),
    CONSTRAINT strategy_comparison_challenger_result_id_fkey FOREIGN KEY (challenger_result_id) REFERENCES analysis.trial_result(id),
    CONSTRAINT strategy_comparison_challenger_revision_id_fkey FOREIGN KEY (challenger_revision_id) REFERENCES analysis.strategy_revision(id),
    CONSTRAINT strategy_comparison_challenger_trial_id_fkey FOREIGN KEY (challenger_trial_id) REFERENCES analysis.research_trial(id),
    CONSTRAINT strategy_comparison_champion_result_id_fkey FOREIGN KEY (champion_result_id) REFERENCES analysis.trial_result(id),
    CONSTRAINT strategy_comparison_champion_revision_id_fkey FOREIGN KEY (champion_revision_id) REFERENCES analysis.strategy_revision(id),
    CONSTRAINT strategy_comparison_champion_trial_id_fkey FOREIGN KEY (champion_trial_id) REFERENCES analysis.research_trial(id)
);

CREATE TABLE analysis.strategy_evaluation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    strategy_revision_id bigint NOT NULL,
    evaluation_type text NOT NULL,
    evaluated_at timestamp with time zone NOT NULL,
    period_start timestamp with time zone,
    period_end timestamp with time zone,
    verdict text,
    metrics jsonb NOT NULL,
    evidence jsonb DEFAULT '[]'::jsonb NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    hypothesis_id uuid,
    experiment_family_id uuid,
    research_trial_id uuid,
    validation_dossier_id uuid,
    artifact_id text,
    artifact_hash character(64),
    input_hash character(64),
    lineage jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT strategy_evaluation_pkey PRIMARY KEY (id),
    CONSTRAINT strategy_evaluation_experiment_family_id_fkey FOREIGN KEY (experiment_family_id) REFERENCES analysis.experiment_family(id),
    CONSTRAINT strategy_evaluation_hypothesis_id_fkey FOREIGN KEY (hypothesis_id) REFERENCES analysis.hypothesis(id),
    CONSTRAINT strategy_evaluation_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id),
    CONSTRAINT strategy_evaluation_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id),
    CONSTRAINT strategy_evaluation_validation_dossier_id_fkey FOREIGN KEY (validation_dossier_id) REFERENCES analysis.validation_dossier(id)
);

CREATE TABLE analysis.strategy_monitoring_evidence (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    strategy_revision_id bigint NOT NULL,
    research_trial_id uuid NOT NULL,
    trial_result_id uuid NOT NULL,
    universe_manifest_hash character(64) NOT NULL,
    result_hash character(64) NOT NULL,
    evidence_kind text NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    input_hash character(64) NOT NULL,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    lineage jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT strategy_monitoring_evidence_check CHECK (((available_at <= observed_at) AND (available_at <= input_cutoff))),
    CONSTRAINT strategy_monitoring_evidence_evidence_kind_check CHECK ((evidence_kind = ANY (ARRAY['correlation'::text, 'tail_correlation'::text, 'crowding'::text, 'capacity'::text, 'decay'::text, 'regime'::text]))),
    CONSTRAINT strategy_monitoring_evidence_input_hash_check CHECK ((input_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT strategy_monitoring_evidence_pkey PRIMARY KEY (id),
    CONSTRAINT strategy_monitoring_evidence_strategy_revision_id_evidence__key UNIQUE (strategy_revision_id, evidence_kind, input_cutoff, input_hash),
    CONSTRAINT strategy_monitoring_evidence_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id),
    CONSTRAINT strategy_monitoring_evidence_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id),
    CONSTRAINT strategy_monitoring_evidence_trial_result_id_fkey FOREIGN KEY (trial_result_id) REFERENCES analysis.trial_result(id)
);

CREATE TABLE analysis.symbol_feature (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.symbol_feature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    run_id uuid NOT NULL,
    instrument_id bigint NOT NULL,
    as_of timestamp with time zone NOT NULL,
    feature_set text NOT NULL,
    feature_version text NOT NULL,
    price double precision,
    ma_50 double precision,
    ma_200 double precision,
    relative_strength_20d double precision,
    atr_pct double precision,
    liquidity_score double precision,
    valuation_score double precision,
    earnings_score double precision,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    momentum_5d double precision,
    momentum_20d double precision,
    relative_strength_60d double precision,
    kaufman_er_20d double precision,
    kaufman_er_60d double precision,
    kama_fast double precision,
    kama_slow double precision,
    kama_fast_slope double precision,
    kama_slow_slope double precision,
    trend_state text DEFAULT 'unavailable'::text NOT NULL,
    trend_confidence double precision DEFAULT 0 NOT NULL,
    volatility_state text DEFAULT 'unstable'::text NOT NULL,
    data_quality_status text DEFAULT 'unavailable'::text NOT NULL,
    reason_codes text[] DEFAULT '{}'::text[] NOT NULL,
    CONSTRAINT ck_symbol_feature_trend_confidence CHECK (((trend_confidence >= (0)::double precision) AND (trend_confidence <= (1)::double precision))),
    CONSTRAINT ck_symbol_feature_trend_state CHECK ((trend_state = ANY (ARRAY['trend_up'::text, 'trend_down'::text, 'range'::text, 'transition'::text, 'unavailable'::text]))),
    CONSTRAINT ck_symbol_feature_volatility_state CHECK ((volatility_state = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'unstable'::text]))),
    CONSTRAINT symbol_feature_pkey PRIMARY KEY (id),
    CONSTRAINT symbol_feature_run_id_instrument_id_feature_set_feature_ver_key UNIQUE (run_id, instrument_id, feature_set, feature_version),
    CONSTRAINT symbol_feature_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT symbol_feature_run_id_fkey FOREIGN KEY (run_id) REFERENCES analysis.run(id) ON DELETE CASCADE
);

CREATE TABLE analysis.validation_gate_result (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    dossier_id uuid NOT NULL,
    gate_code text NOT NULL,
    verdict text NOT NULL,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    evaluated_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    CONSTRAINT validation_gate_result_check CHECK ((available_at <= evaluated_at)),
    CONSTRAINT validation_gate_result_gate_code_check CHECK ((gate_code = ANY (ARRAY['pit_integrity'::text, 'denominator_completeness'::text, 'oos_predictive_validity'::text, 'falsification_and_robustness'::text, 'economic_promotability'::text]))),
    CONSTRAINT validation_gate_result_verdict_check CHECK ((verdict = ANY (ARRAY['pass'::text, 'fail'::text, 'unavailable'::text]))),
    CONSTRAINT validation_gate_result_dossier_id_gate_code_key UNIQUE (dossier_id, gate_code),
    CONSTRAINT validation_gate_result_pkey PRIMARY KEY (id),
    CONSTRAINT validation_gate_result_dossier_id_fkey FOREIGN KEY (dossier_id) REFERENCES analysis.validation_dossier(id)
);

CREATE TABLE app.catalyst (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME app.catalyst_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    instrument_id bigint,
    market_event_id bigint,
    starts_at timestamp with time zone NOT NULL,
    title text NOT NULL,
    expected_impact text,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event_key text,
    version integer DEFAULT 1 NOT NULL,
    status text DEFAULT 'current'::text NOT NULL,
    supersedes_id bigint,
    superseded_at timestamp with time zone,
    source_id text,
    source_priority integer DEFAULT 0 NOT NULL,
    confidence double precision,
    CONSTRAINT catalyst_pkey PRIMARY KEY (id),
    CONSTRAINT catalyst_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT catalyst_market_event_id_fkey FOREIGN KEY (market_event_id) REFERENCES raw.market_event(id),
    CONSTRAINT fk_app_catalyst_supersedes FOREIGN KEY (supersedes_id) REFERENCES app.catalyst(id)
);

CREATE TABLE app.publication (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    scope text NOT NULL,
    analysis_run_id uuid NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    published_at timestamp with time zone,
    validation jsonb DEFAULT '{}'::jsonb NOT NULL,
    bundle_id uuid,
    CONSTRAINT publication_status_check CHECK ((status = ANY (ARRAY['building'::text, 'published'::text, 'failed'::text, 'superseded'::text]))),
    CONSTRAINT publication_pkey PRIMARY KEY (id),
    CONSTRAINT publication_analysis_run_id_fkey FOREIGN KEY (analysis_run_id) REFERENCES analysis.run(id),
    CONSTRAINT publication_bundle_id_fkey FOREIGN KEY (bundle_id) REFERENCES app.publication_bundle(id) ON DELETE RESTRICT
);

CREATE TABLE raw.content_item_instrument (
    content_item_id bigint NOT NULL,
    instrument_id bigint NOT NULL,
    relevance double precision,
    CONSTRAINT content_item_instrument_pkey PRIMARY KEY (content_item_id, instrument_id),
    CONSTRAINT content_item_instrument_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES raw.content_item(id) ON DELETE CASCADE,
    CONSTRAINT content_item_instrument_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id)
);

CREATE TABLE raw.market_event_version (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME raw.market_event_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    market_event_id bigint NOT NULL,
    instrument_id bigint,
    source_id text NOT NULL,
    ingest_run_id uuid NOT NULL,
    payload_id bigint,
    source_key text NOT NULL,
    event_scope text NOT NULL,
    event_kind text NOT NULL,
    title text NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone,
    importance text,
    verification_status text,
    source_url text,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT market_event_version_market_event_id_ingest_run_id_key UNIQUE (market_event_id, ingest_run_id),
    CONSTRAINT market_event_version_pkey PRIMARY KEY (id),
    CONSTRAINT market_event_version_ingest_run_id_fkey FOREIGN KEY (ingest_run_id) REFERENCES ingest.run(id),
    CONSTRAINT market_event_version_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT market_event_version_market_event_id_fkey FOREIGN KEY (market_event_id) REFERENCES raw.market_event(id) ON DELETE CASCADE,
    CONSTRAINT market_event_version_payload_id_fkey FOREIGN KEY (payload_id) REFERENCES ingest.payload(id),
    CONSTRAINT market_event_version_source_id_fkey FOREIGN KEY (source_id) REFERENCES ingest.source(id)
);

CREATE TABLE raw.option_quote (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME raw.option_quote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    snapshot_id bigint NOT NULL,
    contract_id bigint NOT NULL,
    underlying_price double precision,
    bid double precision,
    ask double precision,
    mid double precision,
    last double precision,
    volume bigint,
    open_interest bigint,
    provider_iv double precision,
    provider_delta double precision,
    provider_gamma double precision,
    provider_theta double precision,
    provider_vega double precision,
    bid_size bigint,
    ask_size bigint,
    last_trade_at timestamp with time zone,
    captured_at timestamp with time zone,
    market_data_status text,
    previous_close double precision,
    provider_rho double precision,
    chance_of_profit_long double precision,
    chance_of_profit_short double precision,
    provider_updated_at timestamp with time zone,
    provider_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    capture_generation_id bigint,
    capture_group_key text,
    group_started_at timestamp with time zone,
    group_finished_at timestamp with time zone,
    provider_observed_at timestamp with time zone,
    available_at timestamp with time zone DEFAULT now() NOT NULL,
    underlying_observed_at timestamp with time zone,
    underlying_available_at timestamp with time zone,
    contract_style text,
    contract_settlement text,
    contract_deliverable_key text,
    standard_contract_verified boolean DEFAULT false NOT NULL,
    CONSTRAINT ck_option_quote_standard_terms CHECK (((NOT standard_contract_verified) OR ((contract_style = 'american'::text) AND (contract_settlement = 'physical'::text) AND (contract_deliverable_key IS NOT NULL)))),
    CONSTRAINT option_quote_snapshot_id_contract_id_observed_at_key UNIQUE (snapshot_id, contract_id, observed_at),
    CONSTRAINT option_quote_capture_generation_id_fkey FOREIGN KEY (capture_generation_id) REFERENCES raw.option_capture_generation(id) ON DELETE RESTRICT,
    CONSTRAINT option_quote_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES catalog.option_contract(id),
    CONSTRAINT option_quote_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES raw.option_snapshot(id) ON DELETE CASCADE
)
PARTITION BY RANGE (observed_at);

CREATE TABLE analysis.agent_task (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    agent_run_id uuid,
    decision_id uuid,
    task_kind text NOT NULL,
    status text NOT NULL,
    request jsonb NOT NULL,
    result jsonb,
    validation jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    result_available_at timestamp with time zone,
    validation_available_at timestamp with time zone,
    experiment_id uuid,
    arm text,
    paired_task_id uuid,
    provider text,
    model text,
    evidence_fingerprint text,
    prompt_version text,
    schema_version text,
    baseline_version text,
    validation_status text,
    validation_detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    latency_ms integer,
    input_tokens bigint,
    output_tokens bigint,
    cost_usd numeric(14,6),
    CONSTRAINT agent_task_pkey PRIMARY KEY (id),
    CONSTRAINT agent_task_agent_run_id_fkey FOREIGN KEY (agent_run_id) REFERENCES analysis.agent_run(id) ON DELETE CASCADE,
    CONSTRAINT agent_task_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id),
    CONSTRAINT agent_task_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES analysis.agent_experiment(id) ON DELETE RESTRICT,
    CONSTRAINT agent_task_paired_task_id_fkey FOREIGN KEY (paired_task_id) REFERENCES analysis.agent_task(id) ON DELETE RESTRICT
);

CREATE TABLE analysis.decision_evidence (
    decision_id uuid NOT NULL,
    evidence_kind text NOT NULL,
    reference_key text NOT NULL,
    reference_url text,
    detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT decision_evidence_pkey PRIMARY KEY (decision_id, evidence_kind, reference_key),
    CONSTRAINT decision_evidence_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id) ON DELETE CASCADE
);

CREATE TABLE analysis.event_study_feature (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    run_id uuid NOT NULL,
    instrument_id bigint,
    market_event_id bigint NOT NULL,
    market_event_version_id bigint NOT NULL,
    as_of timestamp with time zone NOT NULL,
    event_kind text NOT NULL,
    event_session text NOT NULL,
    pre_event_regime text NOT NULL,
    horizon integer NOT NULL,
    sample_size integer NOT NULL,
    actual_move_median double precision,
    actual_move_p75 double precision,
    actual_move_p90 double precision,
    bootstrap_low double precision,
    bootstrap_high double precision,
    win_rate double precision,
    iv_crush_frequency double precision,
    atm_iv double precision,
    skew_25d double precision,
    term_slope double precision,
    implied_move double precision,
    evidence_state text NOT NULL,
    feature_version text NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_event_study_evidence_state CHECK ((evidence_state = ANY (ARRAY['ready'::text, 'insufficient_event_evidence'::text, 'unavailable'::text]))),
    CONSTRAINT event_study_feature_horizon_check CHECK ((horizon > 0)),
    CONSTRAINT event_study_feature_sample_size_check CHECK ((sample_size >= 0)),
    CONSTRAINT event_study_feature_pkey PRIMARY KEY (id),
    CONSTRAINT event_study_feature_run_id_instrument_id_market_event_versi_key UNIQUE (run_id, instrument_id, market_event_version_id, horizon, feature_version),
    CONSTRAINT event_study_feature_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id) ON DELETE RESTRICT,
    CONSTRAINT event_study_feature_market_event_id_fkey FOREIGN KEY (market_event_id) REFERENCES raw.market_event(id) ON DELETE CASCADE,
    CONSTRAINT event_study_feature_market_event_version_id_fkey FOREIGN KEY (market_event_version_id) REFERENCES raw.market_event_version(id) ON DELETE RESTRICT,
    CONSTRAINT event_study_feature_run_id_fkey FOREIGN KEY (run_id) REFERENCES analysis.run(id) ON DELETE RESTRICT
);

CREATE TABLE analysis.option_discovery_candidate (
    run_id uuid NOT NULL,
    instrument_id bigint NOT NULL,
    stage text NOT NULL,
    discovery_score double precision NOT NULL,
    surface_reason text NOT NULL,
    primary_edge text NOT NULL,
    causal_exposure text NOT NULL,
    catalyst_start date,
    catalyst_end date,
    earliest_signal_at timestamp with time zone,
    timeliness text NOT NULL,
    source_root_count integer DEFAULT 0 NOT NULL,
    evidence_completeness integer DEFAULT 0 NOT NULL,
    data_readiness text NOT NULL,
    execution_ready boolean DEFAULT false NOT NULL,
    next_evidence text NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_option_discovery_evidence CHECK (((evidence_completeness >= 0) AND (evidence_completeness <= 5))),
    CONSTRAINT ck_option_discovery_readiness CHECK ((data_readiness = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text]))),
    CONSTRAINT ck_option_discovery_stage CHECK ((stage = ANY (ARRAY['DISCOVERED'::text, 'UNDERWRITING'::text, 'STRUCTURED'::text, 'PUBLISHED'::text]))),
    CONSTRAINT option_discovery_candidate_pkey PRIMARY KEY (run_id, instrument_id),
    CONSTRAINT option_discovery_candidate_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT option_discovery_candidate_run_id_fkey FOREIGN KEY (run_id) REFERENCES analysis.option_discovery_run(run_id) ON DELETE CASCADE
);

CREATE TABLE analysis.option_event_signal (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    event_contract_id bigint,
    capture_id uuid,
    decision_id uuid,
    snapshot_id bigint,
    contract_id bigint NOT NULL,
    strategy_key text NOT NULL,
    strategy_revision_id bigint,
    objective_version text DEFAULT 'short_horizon_convex_v1'::text NOT NULL,
    status text DEFAULT 'shadow'::text NOT NULL,
    signal_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    selection_score double precision,
    lower_confidence_expectancy double precision,
    maximum_loss numeric(20,6),
    gate_result jsonb DEFAULT '{}'::jsonb NOT NULL,
    ticket jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    cohort_id uuid NOT NULL,
    CONSTRAINT ck_option_event_signal_availability CHECK ((signal_at >= available_at)),
    CONSTRAINT ck_option_event_signal_status CHECK ((status = ANY (ARRAY['shadow'::text, 'ticketed'::text, 'risk_blocked'::text, 'stale'::text, 'unfilled'::text, 'entered'::text, 'partial_exited'::text, 'exited'::text, 'invalidated'::text, 'unmeasurable'::text, 'rejected'::text]))),
    CONSTRAINT option_event_signal_event_id_event_contract_id_capture_id_s_key UNIQUE (event_id, event_contract_id, capture_id, strategy_key, strategy_revision_id),
    CONSTRAINT option_event_signal_pkey PRIMARY KEY (id),
    CONSTRAINT option_event_signal_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES analysis.option_event_capture(id) ON DELETE SET NULL,
    CONSTRAINT option_event_signal_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES analysis.option_recovery_cohort(id) ON DELETE RESTRICT,
    CONSTRAINT option_event_signal_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES catalog.option_contract(id) ON DELETE RESTRICT,
    CONSTRAINT option_event_signal_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id) ON DELETE SET NULL,
    CONSTRAINT option_event_signal_event_contract_id_fkey FOREIGN KEY (event_contract_id) REFERENCES analysis.option_event_contract(id) ON DELETE SET NULL,
    CONSTRAINT option_event_signal_event_id_fkey FOREIGN KEY (event_id) REFERENCES analysis.option_event(id) ON DELETE CASCADE,
    CONSTRAINT option_event_signal_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES raw.option_snapshot(id) ON DELETE SET NULL,
    CONSTRAINT option_event_signal_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id) ON DELETE SET NULL
);

CREATE TABLE analysis.option_relative_value_verification (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.option_relative_value_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    relative_value_id bigint NOT NULL,
    verified_at timestamp with time zone DEFAULT now() NOT NULL,
    status text NOT NULL,
    blockers text[] DEFAULT '{}'::text[] NOT NULL,
    evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT option_relative_value_verification_status_check CHECK ((status = ANY (ARRAY['verified'::text, 'rejected'::text, 'unavailable'::text]))),
    CONSTRAINT option_relative_value_verification_pkey PRIMARY KEY (id),
    CONSTRAINT option_relative_value_verification_relative_value_id_fkey FOREIGN KEY (relative_value_id) REFERENCES analysis.option_relative_value(id) ON DELETE RESTRICT
);

CREATE TABLE analysis.research_evidence_manifest (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    research_trial_id uuid NOT NULL,
    trial_result_id uuid NOT NULL,
    evidence_kind text NOT NULL,
    evaluator_id text NOT NULL,
    sample_count integer NOT NULL,
    domain_valid boolean NOT NULL,
    payload jsonb NOT NULL,
    evidence_hash character(64) DEFAULT repeat('0'::text, 64) NOT NULL,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    evaluator_output_id uuid,
    evaluator_code_version text,
    input_hash character(64),
    universe_hash character(64),
    feature_hash character(64),
    CONSTRAINT research_evidence_manifest_check CHECK ((available_at >= created_at)),
    CONSTRAINT research_evidence_manifest_evidence_kind_check CHECK ((evidence_kind = ANY (ARRAY['controls'::text, 'cpcv_paths'::text, 'neutralization'::text, 'parameter_stability'::text, 'mechanism_falsification'::text, 'multiple_testing'::text]))),
    CONSTRAINT research_evidence_manifest_payload_check CHECK ((jsonb_typeof(payload) = 'object'::text)),
    CONSTRAINT research_evidence_manifest_sample_count_check CHECK ((sample_count > 0)),
    CONSTRAINT research_evidence_manifest_pkey PRIMARY KEY (id),
    CONSTRAINT research_evidence_manifest_trial_result_id_evidence_kind_key UNIQUE (trial_result_id, evidence_kind),
    CONSTRAINT research_evidence_manifest_evaluator_output_id_fkey FOREIGN KEY (evaluator_output_id) REFERENCES analysis.research_evaluator_output(id),
    CONSTRAINT research_evidence_manifest_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id),
    CONSTRAINT research_evidence_manifest_trial_result_id_fkey FOREIGN KEY (trial_result_id) REFERENCES analysis.trial_result(id)
);
