-- Tables: execution, portfolio, and application outputs.

CREATE TABLE analysis.shadow_trade (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    decision_id uuid NOT NULL,
    entry_at timestamp with time zone,
    entry_price numeric(20,6),
    exit_at timestamp with time zone,
    exit_price numeric(20,6),
    status text NOT NULL,
    path jsonb DEFAULT '[]'::jsonb NOT NULL,
    metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
    pending_entry_reason text,
    entry_cohort_id bigint,
    structure text,
    market_regime text,
    fill_basis text,
    source_kind text DEFAULT 'system'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT shadow_trade_decision_id_key UNIQUE (decision_id),
    CONSTRAINT shadow_trade_pkey PRIMARY KEY (id),
    CONSTRAINT shadow_trade_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id),
    CONSTRAINT shadow_trade_entry_cohort_id_fkey FOREIGN KEY (entry_cohort_id) REFERENCES raw.option_capture_generation(id)
);

CREATE TABLE analysis.strategy_forecast (
    id text NOT NULL,
    strategy_revision_id bigint NOT NULL,
    strategy_evaluation_id uuid,
    instrument_id bigint NOT NULL,
    opportunity_episode_id text NOT NULL,
    target text NOT NULL,
    horizon text NOT NULL,
    forecast_value double precision,
    forecast_range jsonb,
    forecast_distribution jsonb,
    probability_semantics text,
    model_artifact_id text NOT NULL,
    artifact_hash character(64) NOT NULL,
    input_hash character(64) NOT NULL,
    as_of timestamp with time zone NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    status text DEFAULT 'available'::text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    research_trial_id uuid,
    trial_result_id uuid,
    universe_manifest_hash character(64),
    result_hash character(64),
    CONSTRAINT strategy_forecast_check CHECK ((as_of = input_cutoff)),
    CONSTRAINT strategy_forecast_check1 CHECK (((forecast_value IS NOT NULL) OR (forecast_range IS NOT NULL) OR (forecast_distribution IS NOT NULL))),
    CONSTRAINT strategy_forecast_p3_link_check CHECK ((((research_trial_id IS NULL) AND (trial_result_id IS NULL) AND (universe_manifest_hash IS NULL) AND (result_hash IS NULL)) OR ((research_trial_id IS NOT NULL) AND (trial_result_id IS NOT NULL) AND (universe_manifest_hash IS NOT NULL) AND (result_hash IS NOT NULL)))),
    CONSTRAINT strategy_forecast_p3_pit_check CHECK (((research_trial_id IS NULL) OR (available_at <= input_cutoff))),
    CONSTRAINT strategy_forecast_pkey PRIMARY KEY (id),
    CONSTRAINT strategy_forecast_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT strategy_forecast_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id),
    CONSTRAINT strategy_forecast_strategy_evaluation_id_fkey FOREIGN KEY (strategy_evaluation_id) REFERENCES analysis.strategy_evaluation(id),
    CONSTRAINT strategy_forecast_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id),
    CONSTRAINT strategy_forecast_trial_result_id_fkey FOREIGN KEY (trial_result_id) REFERENCES analysis.trial_result(id)
);

CREATE TABLE analysis.symbol_decision (
    decision_id uuid NOT NULL,
    action text,
    discovery_reasons text[] DEFAULT '{}'::text[] NOT NULL,
    freshness_status text,
    portfolio_context jsonb DEFAULT '{}'::jsonb NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT symbol_decision_pkey PRIMARY KEY (decision_id),
    CONSTRAINT symbol_decision_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id) ON DELETE CASCADE
);

CREATE TABLE analysis.symbol_decision_outcome (
    decision_id uuid NOT NULL,
    instrument_id bigint NOT NULL,
    as_of timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    outcome_version text DEFAULT 'equity-v1'::text NOT NULL,
    state text DEFAULT 'observing'::text NOT NULL,
    return_1d double precision,
    return_5d double precision,
    return_20d double precision,
    spy_adjusted_return_1d double precision,
    spy_adjusted_return_5d double precision,
    spy_adjusted_return_20d double precision,
    sector_adjusted_return_1d double precision,
    sector_adjusted_return_5d double precision,
    sector_adjusted_return_20d double precision,
    mae double precision,
    mfe double precision,
    max_drawdown double precision,
    thesis_invalidated_at timestamp with time zone,
    sample_eligible boolean DEFAULT false NOT NULL,
    quarantine_reason text,
    measured_through timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT symbol_decision_outcome_state_check CHECK ((state = ANY (ARRAY['observing'::text, 'resolved'::text, 'quarantined'::text]))),
    CONSTRAINT symbol_decision_outcome_pkey PRIMARY KEY (decision_id),
    CONSTRAINT symbol_decision_outcome_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id) ON DELETE CASCADE,
    CONSTRAINT symbol_decision_outcome_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id) ON DELETE RESTRICT
);

CREATE TABLE analysis.ticker_decision (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    instrument_id bigint NOT NULL,
    decision_revision text NOT NULL,
    contract_version text NOT NULL,
    as_of timestamp with time zone NOT NULL,
    published_at timestamp with time zone,
    input_hash character(64) NOT NULL,
    code_version text NOT NULL,
    experiment_id text NOT NULL,
    tactical jsonb NOT NULL,
    fundamental jsonb NOT NULL,
    capital_action jsonb NOT NULL,
    risk_policy jsonb NOT NULL,
    expressions jsonb DEFAULT '{}'::jsonb NOT NULL,
    selected_expression jsonb,
    data_requests jsonb DEFAULT '[]'::jsonb NOT NULL,
    learning_history jsonb DEFAULT '[]'::jsonb NOT NULL,
    input_manifest jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'published'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolution jsonb DEFAULT '{}'::jsonb NOT NULL,
    policy_version text DEFAULT 'risk-policy.v2:legacy'::text NOT NULL,
    opportunity_episode_id text,
    opportunity_cutoff timestamp with time zone,
    opportunity_episode jsonb DEFAULT '{}'::jsonb NOT NULL,
    market_state_publication_id uuid,
    market_state_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    portfolio_impacts jsonb DEFAULT '{}'::jsonb NOT NULL,
    risk_policy_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ticker_decision_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text, 'superseded'::text, 'quarantined'::text]))),
    CONSTRAINT ticker_decision_instrument_id_decision_revision_key UNIQUE (instrument_id, decision_revision),
    CONSTRAINT ticker_decision_pkey PRIMARY KEY (id),
    CONSTRAINT ticker_decision_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id) ON DELETE RESTRICT,
    CONSTRAINT ticker_decision_market_state_publication_id_fkey FOREIGN KEY (market_state_publication_id) REFERENCES app.publication(id) ON DELETE RESTRICT
);

CREATE TABLE app.alert (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    decision_id uuid,
    instrument_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    alert_type text NOT NULL,
    severity text NOT NULL,
    title text NOT NULL,
    detail text,
    acknowledged_at timestamp with time zone,
    resolution_reason text,
    CONSTRAINT alert_pkey PRIMARY KEY (id),
    CONSTRAINT alert_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id),
    CONSTRAINT alert_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id)
);

CREATE TABLE app.current_publication_item (
    scope text NOT NULL,
    publication_id uuid NOT NULL,
    model_name text NOT NULL,
    stable_key text NOT NULL,
    rank integer NOT NULL,
    instrument_id bigint,
    content_hash character(64) NOT NULL,
    CONSTRAINT current_publication_item_pkey PRIMARY KEY (scope, model_name, stable_key),
    CONSTRAINT current_publication_item_content_hash_fkey FOREIGN KEY (content_hash) REFERENCES app.publication_payload(content_hash) ON DELETE RESTRICT,
    CONSTRAINT current_publication_item_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT current_publication_item_publication_id_fkey FOREIGN KEY (publication_id) REFERENCES app.publication(id) ON DELETE CASCADE
);

CREATE TABLE app.publication_item (
    publication_id uuid NOT NULL,
    model_name text NOT NULL,
    stable_key text NOT NULL,
    rank integer NOT NULL,
    instrument_id bigint,
    payload jsonb NOT NULL,
    CONSTRAINT publication_item_pkey PRIMARY KEY (publication_id, model_name, stable_key),
    CONSTRAINT publication_item_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT publication_item_publication_id_fkey FOREIGN KEY (publication_id) REFERENCES app.publication(id) ON DELETE CASCADE
);

CREATE TABLE app.trade_journal (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    decision_id uuid,
    instrument_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    action text NOT NULL,
    quantity numeric(24,8),
    price numeric(20,6),
    rationale text,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT trade_journal_pkey PRIMARY KEY (id),
    CONSTRAINT trade_journal_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id),
    CONSTRAINT trade_journal_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id)
);

CREATE TABLE raw.option_quote_default PARTITION OF raw.option_quote DEFAULT;

CREATE TABLE analysis.option_event_agent_batch (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    capture_id uuid,
    trigger text NOT NULL,
    fingerprint_key text NOT NULL,
    fingerprint jsonb NOT NULL,
    provider text DEFAULT 'codex'::text NOT NULL,
    model text NOT NULL,
    reasoning_effort text NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    task_count integer DEFAULT 0 NOT NULL,
    agent_run_id uuid,
    telemetry jsonb DEFAULT '{}'::jsonb NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    cohort_id uuid NOT NULL,
    experiment_id uuid,
    arm text,
    paired_task_id uuid,
    evidence_fingerprint text,
    prompt_version text,
    schema_version text,
    baseline_version text,
    validation_status text,
    validation_detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    latency_ms integer,
    CONSTRAINT ck_option_event_agent_batch_status CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'failed'::text, 'skipped'::text]))),
    CONSTRAINT ck_option_event_agent_batch_task_count CHECK (((task_count >= 0) AND (task_count <= 12))),
    CONSTRAINT ck_option_event_agent_batch_trigger CHECK ((trigger = ANY (ARRAY['event_established'::text, 'underlying_move_2pct'::text, 'material_iv_change'::text, 'new_material_evidence'::text, 'signal_family_transition'::text, 'preopen_review'::text]))),
    CONSTRAINT option_event_agent_batch_event_id_fingerprint_key_key UNIQUE (event_id, fingerprint_key),
    CONSTRAINT option_event_agent_batch_pkey PRIMARY KEY (id),
    CONSTRAINT option_event_agent_batch_agent_run_id_fkey FOREIGN KEY (agent_run_id) REFERENCES analysis.agent_run(id) ON DELETE SET NULL,
    CONSTRAINT option_event_agent_batch_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES analysis.option_event_capture(id) ON DELETE SET NULL,
    CONSTRAINT option_event_agent_batch_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES analysis.option_recovery_cohort(id) ON DELETE RESTRICT,
    CONSTRAINT option_event_agent_batch_event_id_fkey FOREIGN KEY (event_id) REFERENCES analysis.option_event(id) ON DELETE CASCADE,
    CONSTRAINT option_event_agent_batch_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES analysis.agent_experiment(id) ON DELETE RESTRICT,
    CONSTRAINT option_event_agent_batch_paired_task_id_fkey FOREIGN KEY (paired_task_id) REFERENCES analysis.agent_task(id) ON DELETE RESTRICT
);

CREATE TABLE analysis.option_gate_result (
    run_id uuid NOT NULL,
    instrument_id bigint NOT NULL,
    gate_code text NOT NULL,
    passed boolean NOT NULL,
    reason text NOT NULL,
    evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT option_gate_result_pkey PRIMARY KEY (run_id, instrument_id, gate_code),
    CONSTRAINT option_gate_result_run_id_instrument_id_fkey FOREIGN KEY (run_id, instrument_id) REFERENCES analysis.option_discovery_candidate(run_id, instrument_id) ON DELETE CASCADE
);

CREATE TABLE analysis.option_outcome (
    decision_id uuid NOT NULL,
    maturity_state text NOT NULL,
    observed_through timestamp with time zone,
    return_1d double precision,
    return_5d double precision,
    return_20d double precision,
    return_60d double precision,
    peak_return double precision,
    max_drawdown double precision,
    time_to_2x_days integer,
    time_to_5x_days integer,
    time_to_10x_days integer,
    realized_exit_return double precision,
    realized_exit_basis text,
    stock_move_effect double precision,
    iv_effect double precision,
    theta_effect double precision,
    spread_effect double precision,
    unexplained_effect double precision,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    current_return double precision,
    paper_status text,
    credit_captured double precision,
    collateral_return double precision,
    assigned_basis double precision,
    strike_touched boolean,
    assignment_return_1d double precision,
    assignment_return_5d double precision,
    assignment_return_20d double precision,
    assignment_return_60d double precision,
    outcome_source text DEFAULT 'generic'::text NOT NULL,
    shadow_trade_id uuid,
    objective_version text DEFAULT 'legacy'::text NOT NULL,
    outcome_classification text DEFAULT 'legacy_non_executable'::text NOT NULL,
    promotion_eligible boolean DEFAULT false NOT NULL,
    entry_fill_at timestamp with time zone,
    entry_fill_price numeric(20,6),
    exit_fill_at timestamp with time zone,
    exit_fill_price numeric(20,6),
    exit_reason text,
    fee_total numeric(20,6),
    slippage_total numeric(20,6),
    return_3d double precision,
    return_10d double precision,
    time_to_3x_days integer,
    time_to_4x_days integer,
    executable_peak_return double precision,
    mae double precision,
    giveback double precision,
    exit_efficiency double precision,
    lane text,
    episode_key text,
    sample_eligible boolean DEFAULT false NOT NULL,
    quarantine_reason text,
    calibration_cohort text,
    CONSTRAINT ck_option_outcome_recovery_classification CHECK ((outcome_classification = ANY (ARRAY['legacy_non_executable'::text, 'captured'::text, 'missed'::text, 'unfilled'::text, 'unmeasurable'::text, 'observing'::text]))),
    CONSTRAINT ck_option_outcome_source CHECK ((outcome_source = ANY (ARRAY['generic'::text, 'options_history_v3'::text]))),
    CONSTRAINT ck_option_outcome_v3_shadow CHECK (((outcome_source <> 'options_history_v3'::text) OR (shadow_trade_id IS NOT NULL))),
    CONSTRAINT option_outcome_pkey PRIMARY KEY (decision_id),
    CONSTRAINT fk_option_outcome_shadow_trade FOREIGN KEY (shadow_trade_id) REFERENCES analysis.shadow_trade(id) ON DELETE RESTRICT,
    CONSTRAINT option_outcome_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id) ON DELETE CASCADE
);

CREATE TABLE analysis.portfolio_allocation_item (
    allocation_item_id text NOT NULL,
    allocation_id text NOT NULL,
    candidate_id text DEFAULT ''::text NOT NULL,
    ticker text NOT NULL,
    strategy_forecast_id text,
    action_id text,
    rank_id text,
    hypothesis_id uuid,
    disposition text NOT NULL,
    target_weight double precision NOT NULL,
    current_weight double precision DEFAULT 0 NOT NULL,
    marginal_book_utility double precision NOT NULL,
    trace jsonb NOT NULL,
    blockers jsonb DEFAULT '[]'::jsonb NOT NULL,
    funding_source text,
    funding_amount double precision,
    input_hash character(64) NOT NULL,
    content_hash character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    funding_sources jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT phase4_allocation_item_funding_amount_shape CHECK (((funding_amount IS NULL) OR ((funding_amount < 'Infinity'::double precision) AND (funding_amount > '-Infinity'::double precision) AND (funding_amount > (0)::double precision)))),
    CONSTRAINT phase4_allocation_item_funding_sources_shape CHECK ((jsonb_typeof(funding_sources) = 'object'::text)),
    CONSTRAINT portfolio_allocation_item_blockers_check CHECK ((jsonb_typeof(blockers) = 'array'::text)),
    CONSTRAINT portfolio_allocation_item_check CHECK (((ticker = 'CASH'::text) OR (candidate_id <> ''::text))),
    CONSTRAINT portfolio_allocation_item_check1 CHECK (((input_hash ~ '^[0-9a-f]{64}$'::text) AND ((input_hash)::text <> repeat('0'::text, 64)) AND (allocation_item_id = ('allocation-item:'::text || (input_hash)::text)))),
    CONSTRAINT portfolio_allocation_item_check2 CHECK (((ticker = 'CASH'::text) OR (disposition <> 'selected'::text) OR ((strategy_forecast_id IS NOT NULL) AND (action_id IS NOT NULL)))),
    CONSTRAINT portfolio_allocation_item_check3 CHECK (((ticker = 'CASH'::text) OR (disposition <> 'selected'::text) OR (rank_id IS NOT NULL))),
    CONSTRAINT portfolio_allocation_item_check4 CHECK (((disposition <> 'selected'::text) OR ((ticker = 'CASH'::text) AND (target_weight > (0)::double precision) AND (marginal_book_utility >= (0)::double precision)) OR ((target_weight > (0)::double precision) AND (marginal_book_utility > (0)::double precision)))),
    CONSTRAINT portfolio_allocation_item_check6 CHECK (((ticker = 'CASH'::text) OR (disposition <> 'selected'::text) OR ((funding_amount IS NOT NULL) AND (funding_amount > (0)::double precision)))),
    CONSTRAINT portfolio_allocation_item_content_hash_check CHECK (((content_hash ~ '^[0-9a-f]{64}$'::text) AND ((content_hash)::text <> repeat('0'::text, 64)))),
    CONSTRAINT portfolio_allocation_item_current_weight_check CHECK (((current_weight < 'Infinity'::double precision) AND (current_weight > '-Infinity'::double precision) AND (current_weight >= (0)::double precision) AND (current_weight <= (1)::double precision))),
    CONSTRAINT portfolio_allocation_item_disposition_check CHECK ((disposition = ANY (ARRAY['selected'::text, 'ranked_out'::text, 'rejected'::text, 'rollback'::text]))),
    CONSTRAINT portfolio_allocation_item_marginal_book_utility_check CHECK (((marginal_book_utility < 'Infinity'::double precision) AND (marginal_book_utility > '-Infinity'::double precision))),
    CONSTRAINT portfolio_allocation_item_target_weight_check CHECK (((target_weight < 'Infinity'::double precision) AND (target_weight > '-Infinity'::double precision) AND (target_weight >= (0)::double precision) AND (target_weight <= (1)::double precision))),
    CONSTRAINT portfolio_allocation_item_ticker_check CHECK ((ticker <> ''::text)),
    CONSTRAINT portfolio_allocation_item_trace_check CHECK ((jsonb_typeof(trace) = 'object'::text)),
    CONSTRAINT portfolio_allocation_item_pkey PRIMARY KEY (allocation_item_id),
    CONSTRAINT portfolio_allocation_item_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES analysis.portfolio_allocation_snapshot(allocation_id),
    CONSTRAINT portfolio_allocation_item_hypothesis_id_fkey FOREIGN KEY (hypothesis_id) REFERENCES analysis.hypothesis(id),
    CONSTRAINT portfolio_allocation_item_strategy_forecast_id_fkey FOREIGN KEY (strategy_forecast_id) REFERENCES analysis.strategy_forecast(id)
);

CREATE TABLE analysis.strategy_pnl_tape (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    strategy_revision_id bigint NOT NULL,
    instrument_id bigint NOT NULL,
    strategy_forecast_id text NOT NULL,
    research_trial_id uuid NOT NULL,
    trial_result_id uuid NOT NULL,
    universe_manifest_hash character(64) NOT NULL,
    result_hash character(64) NOT NULL,
    pnl_date date NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    gross_return double precision NOT NULL,
    cost double precision NOT NULL,
    net_return double precision NOT NULL,
    tail_return double precision,
    regime text,
    observed_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    input_hash character(64) NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT strategy_pnl_tape_check CHECK (((available_at <= observed_at) AND (available_at <= input_cutoff))),
    CONSTRAINT strategy_pnl_tape_input_hash_check CHECK ((input_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT strategy_pnl_tape_pkey PRIMARY KEY (id),
    CONSTRAINT strategy_pnl_tape_strategy_forecast_id_key UNIQUE (strategy_forecast_id),
    CONSTRAINT strategy_pnl_tape_strategy_revision_id_instrument_id_pnl_da_key UNIQUE (strategy_revision_id, instrument_id, pnl_date, input_hash),
    CONSTRAINT strategy_pnl_tape_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT strategy_pnl_tape_research_trial_id_fkey FOREIGN KEY (research_trial_id) REFERENCES analysis.research_trial(id),
    CONSTRAINT strategy_pnl_tape_strategy_forecast_id_fkey FOREIGN KEY (strategy_forecast_id) REFERENCES analysis.strategy_forecast(id),
    CONSTRAINT strategy_pnl_tape_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id),
    CONSTRAINT strategy_pnl_tape_trial_result_id_fkey FOREIGN KEY (trial_result_id) REFERENCES analysis.trial_result(id)
);

CREATE TABLE analysis.ticker_data_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    ticker_decision_id uuid NOT NULL,
    field text NOT NULL,
    ticker text NOT NULL,
    request jsonb NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT ticker_data_request_status_check CHECK ((status = ANY (ARRAY['open'::text, 'running'::text, 'complete'::text, 'failed'::text, 'superseded'::text]))),
    CONSTRAINT ticker_data_request_pkey PRIMARY KEY (id),
    CONSTRAINT ticker_data_request_ticker_decision_id_field_key UNIQUE (ticker_decision_id, field),
    CONSTRAINT ticker_data_request_ticker_decision_id_fkey FOREIGN KEY (ticker_decision_id) REFERENCES analysis.ticker_decision(id) ON DELETE CASCADE
);

CREATE TABLE analysis.ticker_input_manifest (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME analysis.ticker_input_manifest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    ticker_decision_id uuid NOT NULL,
    field text NOT NULL,
    source_id text NOT NULL,
    source_version text,
    event_at timestamp with time zone,
    published_at timestamp with time zone,
    available_at timestamp with time zone NOT NULL,
    received_at timestamp with time zone,
    revision text,
    license text,
    original_value jsonb,
    revised_value jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ticker_input_manifest_pkey PRIMARY KEY (id),
    CONSTRAINT ticker_input_manifest_ticker_decision_id_field_source_id_av_key UNIQUE (ticker_decision_id, field, source_id, available_at, revision),
    CONSTRAINT ticker_input_manifest_ticker_decision_id_fkey FOREIGN KEY (ticker_decision_id) REFERENCES analysis.ticker_decision(id) ON DELETE CASCADE
);

CREATE TABLE analysis.ticker_outcome (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    ticker_decision_id uuid NOT NULL,
    horizon text NOT NULL,
    horizon_sessions integer NOT NULL,
    state text DEFAULT 'observing'::text NOT NULL,
    measured_through timestamp with time zone,
    selected_expression text,
    selected_return double precision,
    stock_counterfactual_return double precision,
    alternate_counterfactual_return double precision,
    cash_return double precision,
    sector_return double precision,
    market_return double precision,
    error_type text,
    mistake_card jsonb DEFAULT '{}'::jsonb NOT NULL,
    available_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ticker_outcome_horizon_check CHECK ((horizon = ANY (ARRAY['TACTICAL'::text, 'FUNDAMENTAL'::text]))),
    CONSTRAINT ticker_outcome_horizon_sessions_check CHECK ((horizon_sessions = ANY (ARRAY[1, 5, 20, 63, 126, 252]))),
    CONSTRAINT ticker_outcome_state_check CHECK ((state = ANY (ARRAY['observing'::text, 'resolved'::text, 'quarantined'::text, 'unmeasurable'::text]))),
    CONSTRAINT ticker_outcome_pkey PRIMARY KEY (id),
    CONSTRAINT ticker_outcome_ticker_decision_id_horizon_horizon_sessions_key UNIQUE (ticker_decision_id, horizon, horizon_sessions),
    CONSTRAINT ticker_outcome_ticker_decision_id_fkey FOREIGN KEY (ticker_decision_id) REFERENCES analysis.ticker_decision(id) ON DELETE RESTRICT
);

CREATE TABLE app.paper_order (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    decision_id uuid,
    instrument_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    side text NOT NULL,
    quantity numeric(24,8) NOT NULL,
    limit_price numeric(20,6),
    status text NOT NULL,
    policy_result jsonb DEFAULT '{}'::jsonb NOT NULL,
    structure text,
    reserved_collateral numeric(24,4),
    idempotency_key text,
    ticket_version integer,
    ticket_snapshot jsonb,
    intended_limit_price numeric(20,6),
    actual_fill_price numeric(20,6),
    filled_at timestamp with time zone,
    event_id uuid,
    event_signal_id uuid,
    strategy_family text,
    objective_version text,
    entry_capture_count integer DEFAULT 0 NOT NULL,
    cohort_id uuid,
    lane text DEFAULT 'radar'::text NOT NULL,
    policy_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    exit_at timestamp with time zone,
    exit_price numeric(20,6),
    fees numeric(20,6) DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    submitted_at timestamp with time zone,
    filled_quantity numeric(24,8),
    exited_quantity numeric(24,8) DEFAULT 0 NOT NULL,
    entry_slippage numeric(20,6),
    exit_slippage numeric(20,6),
    unfilled_reason text,
    ticker_decision_id uuid,
    ticker_decision_revision text,
    expression_kind text,
    max_loss numeric(20,6),
    planned_loss numeric(20,6),
    expires_at timestamp with time zone,
    thesis_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    paper_only boolean DEFAULT true NOT NULL,
    execution_quote jsonb,
    fill_evidence_at timestamp with time zone,
    contract_multiplier numeric(20,6),
    entry_fees numeric(20,6) DEFAULT 0 NOT NULL,
    exit_fees numeric(20,6) DEFAULT 0 NOT NULL,
    CONSTRAINT ck_app_paper_order_lane CHECK ((lane = ANY (ARRAY['radar'::text, 'qqq'::text, 'recovery'::text, 'ticker'::text]))),
    CONSTRAINT ck_paper_order_entry_capture_count CHECK ((entry_capture_count >= 0)),
    CONSTRAINT paper_order_pkey PRIMARY KEY (id),
    CONSTRAINT uq_app_paper_order_idempotency UNIQUE (idempotency_key),
    CONSTRAINT paper_order_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES analysis.option_recovery_cohort(id) ON DELETE RESTRICT,
    CONSTRAINT paper_order_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id),
    CONSTRAINT paper_order_event_id_fkey FOREIGN KEY (event_id) REFERENCES analysis.option_event(id) ON DELETE SET NULL,
    CONSTRAINT paper_order_event_signal_id_fkey FOREIGN KEY (event_signal_id) REFERENCES analysis.option_event_signal(id) ON DELETE SET NULL,
    CONSTRAINT paper_order_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT paper_order_ticker_decision_id_fkey FOREIGN KEY (ticker_decision_id) REFERENCES analysis.ticker_decision(id) ON DELETE RESTRICT
);

CREATE TABLE app.thesis (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME app.thesis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    instrument_id bigint NOT NULL,
    revision integer NOT NULL,
    status text NOT NULL,
    thesis jsonb NOT NULL,
    source_agent_task_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    schema_version integer DEFAULT 3 NOT NULL,
    author_kind text DEFAULT 'legacy'::text NOT NULL,
    automation_run_id uuid,
    superseded_revision_id bigint,
    change_rationale text,
    last_assessed_at timestamp with time zone,
    last_human_reviewed_at timestamp with time zone,
    CONSTRAINT thesis_instrument_id_revision_key UNIQUE (instrument_id, revision),
    CONSTRAINT thesis_pkey PRIMARY KEY (id),
    CONSTRAINT thesis_automation_run_id_fkey FOREIGN KEY (automation_run_id) REFERENCES app.thesis_automation_run(id),
    CONSTRAINT thesis_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT thesis_source_agent_task_id_fkey FOREIGN KEY (source_agent_task_id) REFERENCES analysis.agent_task(id),
    CONSTRAINT thesis_superseded_revision_id_fkey FOREIGN KEY (superseded_revision_id) REFERENCES app.thesis(id)
);

CREATE TABLE analysis.option_decision (
    decision_id uuid NOT NULL,
    contract_id bigint NOT NULL,
    snapshot_id bigint NOT NULL,
    quote_observed_at timestamp with time zone NOT NULL,
    primary_decision_id uuid,
    premium_mid double precision,
    fill_assumption double precision,
    required_move_pct double precision,
    buy_under double precision,
    predicted_p2x double precision,
    predicted_p5x double precision,
    ev_multiple double precision,
    tier text,
    synthetic_legs jsonb DEFAULT '[]'::jsonb NOT NULL,
    structure text DEFAULT 'long_option'::text NOT NULL,
    entry_price double precision,
    exit_cost_estimate double precision,
    secured_cash double precision,
    max_profit double precision,
    max_loss double precision,
    break_even double precision,
    effective_assignment_price double precision,
    probability_profit double precision,
    probability_assignment double precision,
    probability_touch double precision,
    expected_value double precision,
    risk_adjusted_expectancy double precision,
    tail_cvar double precision,
    data_confidence double precision,
    execution_confidence double precision,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    paper_state text,
    discovery_lane text,
    thesis_id bigint,
    relative_value_id bigint,
    model_version text,
    market_regime text,
    fair_low double precision,
    fair_high double precision,
    modeled_net_edge double precision,
    route_version text,
    strategy_route jsonb DEFAULT '{}'::jsonb NOT NULL,
    market_regime_detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    event_state text,
    CONSTRAINT ck_option_decision_market_regime_detail_object CHECK ((jsonb_typeof(market_regime_detail) = 'object'::text)),
    CONSTRAINT ck_option_decision_paper_state CHECK (((paper_state IS NULL) OR (paper_state = ANY (ARRAY['COLLECTING'::text, 'WATCH'::text, 'PAPER_READY'::text, 'REJECT'::text])))),
    CONSTRAINT ck_option_decision_strategy_route_object CHECK ((jsonb_typeof(strategy_route) = 'object'::text)),
    CONSTRAINT option_decision_pkey PRIMARY KEY (decision_id),
    CONSTRAINT option_decision_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES catalog.option_contract(id),
    CONSTRAINT option_decision_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES analysis.decision(id) ON DELETE CASCADE,
    CONSTRAINT option_decision_primary_decision_id_fkey FOREIGN KEY (primary_decision_id) REFERENCES analysis.decision(id),
    CONSTRAINT option_decision_relative_value_id_fkey FOREIGN KEY (relative_value_id) REFERENCES analysis.option_relative_value(id),
    CONSTRAINT option_decision_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES raw.option_snapshot(id),
    CONSTRAINT option_decision_thesis_id_fkey FOREIGN KEY (thesis_id) REFERENCES app.thesis(id)
);

CREATE TABLE analysis.option_opportunity_observation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    capture_id uuid,
    capture_generation_id bigint,
    capture_generation_key text NOT NULL,
    event_contract_id bigint,
    contract_id bigint NOT NULL,
    strategy_key text NOT NULL,
    strategy_revision_id bigint,
    objective_version text DEFAULT 'short_horizon_convex_v1'::text NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone NOT NULL,
    expiration date NOT NULL,
    quote jsonb DEFAULT '{}'::jsonb NOT NULL,
    liquid boolean NOT NULL,
    data_status text DEFAULT 'ok'::text NOT NULL,
    selection_stage text DEFAULT 'observed'::text NOT NULL,
    miss_reason text,
    signal_id uuid,
    paper_order_id uuid,
    selection_score double precision,
    lower_confidence_expectancy double precision,
    entry_fill_at timestamp with time zone,
    entry_fill_price numeric(20,6),
    return_1_session double precision,
    return_3_session double precision,
    return_5_session double precision,
    return_10_session double precision,
    time_to_2x_sessions integer,
    time_to_3x_sessions integer,
    time_to_4x_sessions integer,
    executable_peak_return double precision,
    realized_return double precision,
    mae double precision,
    giveback double precision,
    exit_efficiency double precision,
    exit_fill_at timestamp with time zone,
    exit_fill_price numeric(20,6),
    outcome_classification text DEFAULT 'observing'::text NOT NULL,
    measured_through timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    cohort_id uuid NOT NULL,
    lane text DEFAULT 'recovery'::text NOT NULL,
    episode_key text NOT NULL,
    sample_eligible boolean DEFAULT false NOT NULL,
    quarantine_reason text,
    calibration_cohort text,
    CONSTRAINT ck_option_opportunity_availability CHECK ((available_at IS NOT NULL)),
    CONSTRAINT ck_option_opportunity_classification CHECK ((outcome_classification = ANY (ARRAY['observing'::text, 'captured'::text, 'missed'::text, 'unfilled'::text, 'unmeasurable'::text]))),
    CONSTRAINT ck_option_opportunity_data_status CHECK ((data_status = ANY (ARRAY['ok'::text, 'stale_quote'::text, 'continuity_missing'::text, 'lookahead_blocked'::text, 'invalid_event_reference'::text]))),
    CONSTRAINT ck_option_opportunity_miss_reason CHECK (((miss_reason IS NULL) OR (miss_reason = ANY (ARRAY['not_featured'::text, 'gate_reject'::text, 'ranked_out'::text, 'not_published'::text, 'unfilled'::text, 'risk_blocked'::text, 'captured'::text, 'unmeasurable'::text])))),
    CONSTRAINT ck_option_opportunity_selection_stage CHECK ((selection_stage = ANY (ARRAY['observed'::text, 'eligible'::text, 'ranked_out'::text, 'published'::text, 'ticketed'::text, 'filled'::text, 'exited'::text]))),
    CONSTRAINT option_opportunity_observatio_event_id_capture_generation_k_key UNIQUE (event_id, capture_generation_key, contract_id, strategy_key, strategy_revision_id),
    CONSTRAINT option_opportunity_observation_pkey PRIMARY KEY (id),
    CONSTRAINT option_opportunity_observation_capture_generation_id_fkey FOREIGN KEY (capture_generation_id) REFERENCES raw.option_capture_generation(id) ON DELETE SET NULL,
    CONSTRAINT option_opportunity_observation_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES analysis.option_event_capture(id) ON DELETE SET NULL,
    CONSTRAINT option_opportunity_observation_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES analysis.option_recovery_cohort(id) ON DELETE RESTRICT,
    CONSTRAINT option_opportunity_observation_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES catalog.option_contract(id) ON DELETE RESTRICT,
    CONSTRAINT option_opportunity_observation_event_contract_id_fkey FOREIGN KEY (event_contract_id) REFERENCES analysis.option_event_contract(id) ON DELETE SET NULL,
    CONSTRAINT option_opportunity_observation_event_id_fkey FOREIGN KEY (event_id) REFERENCES analysis.option_event(id) ON DELETE CASCADE,
    CONSTRAINT option_opportunity_observation_paper_order_id_fkey FOREIGN KEY (paper_order_id) REFERENCES app.paper_order(id) ON DELETE SET NULL,
    CONSTRAINT option_opportunity_observation_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES analysis.option_event_signal(id) ON DELETE SET NULL,
    CONSTRAINT option_opportunity_observation_strategy_revision_id_fkey FOREIGN KEY (strategy_revision_id) REFERENCES analysis.strategy_revision(id) ON DELETE SET NULL
);

CREATE TABLE analysis.portfolio_drift_evidence (
    decision_id text NOT NULL,
    allocation_id text NOT NULL,
    allocation_item_id text NOT NULL,
    drift_score double precision NOT NULL,
    rollback_threshold double precision NOT NULL,
    proposed_weight double precision NOT NULL,
    action text NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    input_hash character(64) NOT NULL,
    content_hash character(64) NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT portfolio_drift_evidence_action_check CHECK ((action = ANY (ARRAY['hold'::text, 'reduce'::text, 'rollback'::text, 'unavailable'::text]))),
    CONSTRAINT portfolio_drift_evidence_check CHECK (((action <> 'reduce'::text) OR ((drift_score < rollback_threshold) AND (drift_score >= (rollback_threshold / (2)::double precision))))),
    CONSTRAINT portfolio_drift_evidence_check1 CHECK (((action <> 'rollback'::text) OR (drift_score >= rollback_threshold))),
    CONSTRAINT portfolio_drift_evidence_check2 CHECK (((action <> 'hold'::text) OR (drift_score < (rollback_threshold / (2)::double precision)))),
    CONSTRAINT portfolio_drift_evidence_check3 CHECK ((decision_id = ('drift:'::text || (input_hash)::text))),
    CONSTRAINT portfolio_drift_evidence_content_hash_check CHECK ((content_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT portfolio_drift_evidence_drift_score_check CHECK (((drift_score < 'Infinity'::double precision) AND (drift_score > '-Infinity'::double precision) AND (drift_score >= (0)::double precision))),
    CONSTRAINT portfolio_drift_evidence_input_hash_check CHECK ((input_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT portfolio_drift_evidence_metadata_check CHECK ((jsonb_typeof(metadata) = 'object'::text)),
    CONSTRAINT portfolio_drift_evidence_proposed_weight_check CHECK (((proposed_weight < 'Infinity'::double precision) AND (proposed_weight >= (0)::double precision) AND (proposed_weight <= (1)::double precision))),
    CONSTRAINT portfolio_drift_evidence_rollback_threshold_check CHECK (((rollback_threshold < 'Infinity'::double precision) AND (rollback_threshold > (0)::double precision))),
    CONSTRAINT portfolio_drift_evidence_pkey PRIMARY KEY (decision_id),
    CONSTRAINT portfolio_drift_evidence_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES analysis.portfolio_allocation_snapshot(allocation_id),
    CONSTRAINT portfolio_drift_evidence_allocation_item_id_fkey FOREIGN KEY (allocation_item_id) REFERENCES analysis.portfolio_allocation_item(allocation_item_id)
);

CREATE TABLE app.decision_inbox_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    dedupe_key text NOT NULL,
    event_type text NOT NULL,
    opportunity_id uuid,
    ticket_version integer,
    paper_order_id uuid,
    lane text,
    severity text DEFAULT 'info'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    user_state text DEFAULT 'open'::text NOT NULL,
    snoozed_until timestamp with time zone,
    dismiss_reason text,
    user_state_updated_at timestamp with time zone,
    reviewed_at timestamp with time zone,
    useful boolean,
    usefulness_updated_at timestamp with time zone,
    CONSTRAINT ck_app_decision_inbox_event_type CHECK ((event_type = ANY (ARRAY['ready'::text, 'revoked'::text, 'expired'::text, 'paper_filled'::text, 'paper_exited'::text, 'portfolio_critical'::text, 'paper_engine_halt'::text, 'high_priority_research'::text]))),
    CONSTRAINT ck_decision_inbox_dismiss_reason CHECK (((user_state <> 'dismissed'::text) OR (NULLIF(btrim(dismiss_reason), ''::text) IS NOT NULL))),
    CONSTRAINT ck_decision_inbox_snooze_state CHECK (((user_state <> 'snoozed'::text) OR (snoozed_until IS NOT NULL))),
    CONSTRAINT ck_decision_inbox_user_state CHECK ((user_state = ANY (ARRAY['open'::text, 'acknowledged'::text, 'snoozed'::text, 'dismissed'::text, 'review_complete'::text]))),
    CONSTRAINT decision_inbox_item_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text]))),
    CONSTRAINT decision_inbox_item_status_check CHECK ((status = ANY (ARRAY['active'::text, 'resolved'::text]))),
    CONSTRAINT decision_inbox_usefulness_timestamp CHECK (((useful IS NULL) = (usefulness_updated_at IS NULL))),
    CONSTRAINT decision_inbox_item_dedupe_key_key UNIQUE (dedupe_key),
    CONSTRAINT decision_inbox_item_pkey PRIMARY KEY (id),
    CONSTRAINT decision_inbox_item_paper_order_id_fkey FOREIGN KEY (paper_order_id) REFERENCES app.paper_order(id) ON DELETE RESTRICT
);

CREATE TABLE app.paper_execution_observation (
    paper_execution_observation_id text CONSTRAINT paper_execution_observation_paper_execution_observatio_not_null NOT NULL,
    allocation_item_id text NOT NULL,
    action_id text NOT NULL,
    paper_order_id uuid NOT NULL,
    execution_mode text DEFAULT 'paper'::text NOT NULL,
    paper_only boolean DEFAULT true NOT NULL,
    status text NOT NULL,
    requested_quantity double precision NOT NULL,
    filled_quantity double precision NOT NULL,
    requested_price double precision,
    fill_price double precision,
    spread_bps double precision,
    latency_ms double precision,
    impact_bps double precision,
    side text DEFAULT 'buy'::text NOT NULL,
    exit_price double precision,
    observed_at timestamp with time zone NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    event_fee double precision,
    contract_multiplier double precision,
    CONSTRAINT paper_execution_observation_check CHECK (((filled_quantity < 'Infinity'::double precision) AND (filled_quantity > '-Infinity'::double precision) AND (filled_quantity >= (0)::double precision) AND (filled_quantity <= requested_quantity))),
    CONSTRAINT paper_execution_observation_check1 CHECK (((status <> ALL (ARRAY['filled'::text, 'exited'::text])) OR (filled_quantity > (0)::double precision))),
    CONSTRAINT paper_execution_observation_check2 CHECK (((fill_price IS NOT NULL) OR (filled_quantity = (0)::double precision))),
    CONSTRAINT paper_execution_observation_check3 CHECK ((available_at >= observed_at)),
    CONSTRAINT paper_execution_observation_execution_mode_check CHECK ((execution_mode = 'paper'::text)),
    CONSTRAINT paper_execution_observation_exit_price_check CHECK (((exit_price IS NULL) OR ((exit_price < 'Infinity'::double precision) AND (exit_price >= (0)::double precision)))),
    CONSTRAINT paper_execution_observation_fill_price_check CHECK (((fill_price IS NULL) OR ((fill_price < 'Infinity'::double precision) AND (fill_price > '-Infinity'::double precision) AND (fill_price > (0)::double precision)))),
    CONSTRAINT paper_execution_observation_impact_bps_check CHECK (((impact_bps IS NULL) OR ((impact_bps < 'Infinity'::double precision) AND (impact_bps > '-Infinity'::double precision) AND (impact_bps >= (0)::double precision)))),
    CONSTRAINT paper_execution_observation_latency_ms_check CHECK (((latency_ms IS NULL) OR ((latency_ms < 'Infinity'::double precision) AND (latency_ms > '-Infinity'::double precision) AND (latency_ms >= (0)::double precision)))),
    CONSTRAINT paper_execution_observation_paper_only_check CHECK (paper_only),
    CONSTRAINT paper_execution_observation_requested_price_check CHECK (((requested_price IS NULL) OR ((requested_price < 'Infinity'::double precision) AND (requested_price > '-Infinity'::double precision) AND (requested_price > (0)::double precision)))),
    CONSTRAINT paper_execution_observation_requested_quantity_check CHECK (((requested_quantity < 'Infinity'::double precision) AND (requested_quantity > '-Infinity'::double precision) AND (requested_quantity >= (0)::double precision))),
    CONSTRAINT paper_execution_observation_side_check CHECK ((side = ANY (ARRAY['buy'::text, 'sell'::text]))),
    CONSTRAINT paper_execution_observation_spread_bps_check CHECK (((spread_bps IS NULL) OR ((spread_bps < 'Infinity'::double precision) AND (spread_bps > '-Infinity'::double precision) AND (spread_bps >= (0)::double precision)))),
    CONSTRAINT phase4_paper_observation_status CHECK ((status = ANY (ARRAY['planned'::text, 'submitted'::text, 'partial'::text, 'filled'::text, 'partial_exited'::text, 'exited'::text, 'cancelled'::text, 'unavailable'::text]))),
    CONSTRAINT paper_execution_observation_pkey PRIMARY KEY (paper_execution_observation_id),
    CONSTRAINT paper_execution_observation_allocation_item_id_fkey FOREIGN KEY (allocation_item_id) REFERENCES analysis.portfolio_allocation_item(allocation_item_id),
    CONSTRAINT paper_execution_observation_paper_order_id_fkey FOREIGN KEY (paper_order_id) REFERENCES app.paper_order(id)
);

CREATE TABLE app.paper_order_leg (
    paper_order_id uuid NOT NULL,
    leg_index integer NOT NULL,
    contract_id bigint NOT NULL,
    option_type text NOT NULL,
    side text NOT NULL,
    strike numeric(20,6) NOT NULL,
    bid numeric(20,6) NOT NULL,
    ask numeric(20,6) NOT NULL,
    bid_size integer NOT NULL,
    ask_size integer NOT NULL,
    quote_time timestamp with time zone NOT NULL,
    open_interest integer,
    volume integer,
    CONSTRAINT paper_order_leg_pkey PRIMARY KEY (paper_order_id, leg_index),
    CONSTRAINT paper_order_leg_paper_order_id_fkey FOREIGN KEY (paper_order_id) REFERENCES app.paper_order(id) ON DELETE CASCADE
);

CREATE TABLE app.thesis_evidence_assessment (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME app.thesis_evidence_assessment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    thesis_revision_id bigint,
    automation_run_id uuid,
    instrument_id bigint NOT NULL,
    evidence_reference text NOT NULL,
    evidence_title text,
    evidence_date timestamp with time zone,
    stance text NOT NULL,
    materiality text DEFAULT 'low'::text NOT NULL,
    affected_pillar_ids text[] DEFAULT ARRAY[]::text[] NOT NULL,
    confidence numeric(5,4) DEFAULT 0 NOT NULL,
    rationale text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT thesis_evidence_assessment_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))),
    CONSTRAINT thesis_evidence_assessment_materiality_check CHECK ((materiality = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text]))),
    CONSTRAINT thesis_evidence_assessment_stance_check CHECK ((stance = ANY (ARRAY['support'::text, 'contradict'::text, 'neutral'::text, 'insufficient'::text]))),
    CONSTRAINT thesis_evidence_assessment_pkey PRIMARY KEY (id),
    CONSTRAINT thesis_evidence_assessment_automation_run_id_fkey FOREIGN KEY (automation_run_id) REFERENCES app.thesis_automation_run(id),
    CONSTRAINT thesis_evidence_assessment_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT thesis_evidence_assessment_thesis_revision_id_fkey FOREIGN KEY (thesis_revision_id) REFERENCES app.thesis(id) ON DELETE CASCADE
);

CREATE TABLE app.thesis_expression (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME app.thesis_expression_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    instrument_id bigint NOT NULL,
    thesis_revision_id bigint NOT NULL,
    expression_kind text NOT NULL,
    structure jsonb DEFAULT '{}'::jsonb NOT NULL,
    entry_logic jsonb DEFAULT '{}'::jsonb NOT NULL,
    max_loss numeric(20,6),
    risk_budget numeric(20,6),
    horizon_date date,
    invalidation_rules jsonb DEFAULT '[]'::jsonb NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT thesis_expression_expression_kind_check CHECK ((expression_kind = ANY (ARRAY['equity'::text, 'option'::text]))),
    CONSTRAINT thesis_expression_pkey PRIMARY KEY (id),
    CONSTRAINT thesis_expression_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT thesis_expression_thesis_revision_id_fkey FOREIGN KEY (thesis_revision_id) REFERENCES app.thesis(id) ON DELETE CASCADE
);

CREATE TABLE app.thesis_review_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY (

    SEQUENCE NAME app.thesis_review_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1

    ) NOT NULL,
    instrument_id bigint NOT NULL,
    thesis_revision_id bigint,
    outcome text NOT NULL,
    notes text,
    reviewed_evidence_cutoff timestamp with time zone,
    reviewed_by text DEFAULT 'joe'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT thesis_review_event_outcome_check CHECK ((outcome = ANY (ARRAY['unchanged'::text, 'updated'::text, 'invalidated'::text, 'closed'::text, 'legacy_acknowledgement'::text]))),
    CONSTRAINT thesis_review_event_pkey PRIMARY KEY (id),
    CONSTRAINT thesis_review_event_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES catalog.instrument(id),
    CONSTRAINT thesis_review_event_thesis_revision_id_fkey FOREIGN KEY (thesis_revision_id) REFERENCES app.thesis(id)
);

CREATE TABLE analysis.book_attribution (
    book_attribution_id text NOT NULL,
    allocation_id text NOT NULL,
    allocation_item_id text NOT NULL,
    strategy_forecast_id text NOT NULL,
    hypothesis_id uuid NOT NULL,
    action_id text NOT NULL,
    rank_id text NOT NULL,
    expression jsonb NOT NULL,
    experiment_id text NOT NULL,
    trial_id uuid NOT NULL,
    result_id uuid NOT NULL,
    paper_execution_observation_id text NOT NULL,
    pnl_status text NOT NULL,
    realized_pnl double precision,
    attribution jsonb NOT NULL,
    input_cutoff timestamp with time zone NOT NULL,
    input_hash character(64) NOT NULL,
    content_hash character(64) NOT NULL,
    available_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT book_attribution_check CHECK (((jsonb_typeof(attribution) = 'object'::text) AND (jsonb_typeof(expression) = 'object'::text) AND (expression <> '{}'::jsonb))),
    CONSTRAINT book_attribution_check1 CHECK (((pnl_status <> 'realized'::text) OR (realized_pnl IS NOT NULL))),
    CONSTRAINT book_attribution_check2 CHECK (((input_hash ~ '^[0-9a-f]{64}$'::text) AND ((input_hash)::text <> repeat('0'::text, 64)) AND (book_attribution_id = ('attribution:'::text || (input_hash)::text)))),
    CONSTRAINT book_attribution_content_hash_check CHECK (((content_hash ~ '^[0-9a-f]{64}$'::text) AND ((content_hash)::text <> repeat('0'::text, 64)))),
    CONSTRAINT book_attribution_pnl_status_check CHECK ((pnl_status = ANY (ARRAY['pending_fill'::text, 'realized'::text, 'unavailable'::text]))),
    CONSTRAINT book_attribution_realized_pnl_check CHECK (((realized_pnl IS NULL) OR ((realized_pnl < 'Infinity'::double precision) AND (realized_pnl > '-Infinity'::double precision)))),
    CONSTRAINT book_attribution_pkey PRIMARY KEY (book_attribution_id),
    CONSTRAINT book_attribution_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES analysis.portfolio_allocation_snapshot(allocation_id),
    CONSTRAINT book_attribution_allocation_item_id_fkey FOREIGN KEY (allocation_item_id) REFERENCES analysis.portfolio_allocation_item(allocation_item_id),
    CONSTRAINT book_attribution_hypothesis_id_fkey FOREIGN KEY (hypothesis_id) REFERENCES analysis.hypothesis(id),
    CONSTRAINT book_attribution_paper_execution_observation_id_fkey FOREIGN KEY (paper_execution_observation_id) REFERENCES app.paper_execution_observation(paper_execution_observation_id),
    CONSTRAINT book_attribution_result_id_fkey FOREIGN KEY (result_id) REFERENCES analysis.trial_result(id),
    CONSTRAINT book_attribution_strategy_forecast_id_fkey FOREIGN KEY (strategy_forecast_id) REFERENCES analysis.strategy_forecast(id),
    CONSTRAINT book_attribution_trial_id_fkey FOREIGN KEY (trial_id) REFERENCES analysis.research_trial(id)
);

CREATE TABLE app.notification_outbox (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    dedupe_key text NOT NULL,
    inbox_item_id uuid NOT NULL,
    channel text DEFAULT 'telegram_owner'::text NOT NULL,
    event_type text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    next_attempt_at timestamp with time zone DEFAULT now() NOT NULL,
    last_error text,
    sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT notification_outbox_attempts_check CHECK ((attempts >= 0)),
    CONSTRAINT notification_outbox_channel_check CHECK ((channel = 'telegram_owner'::text)),
    CONSTRAINT notification_outbox_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'sending'::text, 'sent'::text, 'failed'::text, 'dry_run'::text, 'suppressed'::text, 'uncertain'::text]))),
    CONSTRAINT notification_outbox_dedupe_key_key UNIQUE (dedupe_key),
    CONSTRAINT notification_outbox_pkey PRIMARY KEY (id),
    CONSTRAINT notification_outbox_inbox_item_id_fkey FOREIGN KEY (inbox_item_id) REFERENCES app.decision_inbox_item(id) ON DELETE RESTRICT
);
