"""Canonical panel contracts and pure payload adapters."""

from investment_panel.core.panel.contracts import (
    DECISION_REPAIR_TABLES,
    ENDPOINT_TABLES,
    FRONTEND_ADDITIONAL_TABLES,
    FRONTEND_TABLE_KEY_OVERRIDES,
    PANEL_SCOPE_TABLES,
    SOURCE_REPAIR_TABLES,
    TICKER_INITIAL_TABLES,
    TICKER_TABLES,
    WATCHLIST_SECTION_OUTPUT_TABLES,
    WATCHLIST_SECTION_TABLES,
    frontend_key_for_table,
    frontend_table_names,
    panel_contract_payload,
    panel_snapshot_table_names,
    table_for_endpoint,
    tables_for_scope,
)
from investment_panel.core.panel.payloads import (
    SCOPED_TABLE_COMPACT_FIELDS,
    SCOPED_TABLE_ROW_LIMITS,
    dashboard_payload,
    panel_snapshot_payload,
    row_symbols,
    watchlist_section_payload,
    watchlist_universe_rows,
)
from investment_panel.core.panel.ticker_sections import build_ticker_dossier

__all__ = [
    "DECISION_REPAIR_TABLES",
    "ENDPOINT_TABLES",
    "FRONTEND_ADDITIONAL_TABLES",
    "FRONTEND_TABLE_KEY_OVERRIDES",
    "PANEL_SCOPE_TABLES",
    "SOURCE_REPAIR_TABLES",
    "TICKER_INITIAL_TABLES",
    "TICKER_TABLES",
    "WATCHLIST_SECTION_OUTPUT_TABLES",
    "WATCHLIST_SECTION_TABLES",
    "SCOPED_TABLE_COMPACT_FIELDS",
    "SCOPED_TABLE_ROW_LIMITS",
    "build_ticker_dossier",
    "dashboard_payload",
    "frontend_key_for_table",
    "frontend_table_names",
    "panel_contract_payload",
    "panel_snapshot_payload",
    "panel_snapshot_table_names",
    "row_symbols",
    "table_for_endpoint",
    "tables_for_scope",
    "watchlist_section_payload",
    "watchlist_universe_rows",
]
