"""Read models for the FastAPI app (package facade)."""

from __future__ import annotations

from investment_panel.core.sources import source_ticker_ranking_rows
from investment_panel.core.panel.coerce import decode_fields, decode_json_value, first_heading
from investment_panel.core.panel.sources import source_rows
from investment_panel.core.panel.technicals import average_true_range_pct, one_month_bar_points, one_month_volume_bar_points, period_bar_points, period_return, relative_volume, sampled_price_points, technical_price_history, technicals, trailing_return, true_range_pct_points
from investment_panel.core.panel.disclosures import disclosures, enrich_13f_disclosure_rows, holding_key, sorted_13f_holdings
from investment_panel.core.panel.market_environment import MarketDisplayContext, market_context, market_display_context, market_environment_assets, market_environment_model, market_valuation_charts, market_valuation_reference_charts
from investment_panel.core.panel.feed import feed_signals, ownership_consensus, source_consensus, universe_screen
from investment_panel.core.panel.read_equity import analyst_estimates, candidate_source_evidence, candidates, catalysts, confidence_to_number, correlations, decision_queue, decision_readiness, discovered_universe, earnings, earnings_setups, etf_premiums, fundamentals, liquidity, news, opportunities_ranked, opportunity_source_counts, opportunity_sources, portfolio, provider_runs, quotes, reports, research_packets, screener, sepa, source_freshness, source_health, symbol_decision_snapshots, theses, top_source_label, trader_profiles, tradingview_alerts, tradingview_chart_state, tradingview_symbol_search, tradingview_watchlists, valuations
from investment_panel.core.panel.read_options import option_features, option_radar_opportunity, option_radar_summary, option_snapshot, option_strategy_versions, options_chain, options_expiries, options_expiry_signals, options_payoff_scenarios, options_provider_capabilities, options_ticker_signals, stock_features
from investment_panel.core.panel.read_learning import agent_postmortem, agent_postmortem_request, agent_thesis, agent_thesis_request, agent_thesis_validation, candidate_event, candidate_event_attribution, candidate_event_mark, conviction_calibration, missed_winner_event, option_attribution, radar_alert, radar_state_transition, shadow_trade, shadow_trade_mark, strategy_backtest_result, strategy_cohort_result, strategy_forward_test_result, strategy_mutation_proposal, trade_journal, vol_surface_features
from investment_panel.core.panel.registry import READ_MODELS, ReadContext, load_read_models, read_model_names
from investment_panel.core.panel.snapshot import DECISION_READ_MODEL_TABLES, DECISION_REFRESH_LOCK, decision_readiness_snapshot, ensure_decision_read_models, get_panel_snapshot, load_panel_data, load_ticker_dossier_data

__all__ = [
    "DECISION_READ_MODEL_TABLES",
    "DECISION_REFRESH_LOCK",
    "MarketDisplayContext",
    "READ_MODELS",
    "ReadContext",
    "load_read_models",
    "read_model_names",
    "agent_postmortem",
    "agent_postmortem_request",
    "agent_thesis",
    "agent_thesis_request",
    "agent_thesis_validation",
    "analyst_estimates",
    "average_true_range_pct",
    "candidate_event",
    "candidate_event_attribution",
    "candidate_event_mark",
    "candidate_source_evidence",
    "candidates",
    "catalysts",
    "confidence_to_number",
    "conviction_calibration",
    "correlations",
    "decision_queue",
    "decision_readiness",
    "decision_readiness_snapshot",
    "decode_fields",
    "decode_json_value",
    "disclosures",
    "discovered_universe",
    "earnings",
    "earnings_setups",
    "enrich_13f_disclosure_rows",
    "ensure_decision_read_models",
    "etf_premiums",
    "feed_signals",
    "first_heading",
    "fundamentals",
    "get_panel_snapshot",
    "holding_key",
    "liquidity",
    "load_panel_data",
    "load_ticker_dossier_data",
    "market_context",
    "market_display_context",
    "market_environment_assets",
    "market_environment_model",
    "market_valuation_charts",
    "market_valuation_reference_charts",
    "missed_winner_event",
    "news",
    "one_month_bar_points",
    "one_month_volume_bar_points",
    "opportunities_ranked",
    "opportunity_source_counts",
    "opportunity_sources",
    "option_attribution",
    "option_features",
    "option_radar_opportunity",
    "option_radar_summary",
    "option_snapshot",
    "option_strategy_versions",
    "options_chain",
    "options_expiries",
    "options_expiry_signals",
    "options_payoff_scenarios",
    "options_provider_capabilities",
    "options_ticker_signals",
    "ownership_consensus",
    "period_bar_points",
    "period_return",
    "portfolio",
    "provider_runs",
    "quotes",
    "radar_alert",
    "radar_state_transition",
    "relative_volume",
    "reports",
    "research_packets",
    "sampled_price_points",
    "screener",
    "sepa",
    "shadow_trade",
    "shadow_trade_mark",
    "sorted_13f_holdings",
    "source_consensus",
    "source_freshness",
    "source_health",
    "source_rows",
    "source_ticker_ranking_rows",
    "stock_features",
    "strategy_backtest_result",
    "strategy_cohort_result",
    "strategy_forward_test_result",
    "strategy_mutation_proposal",
    "symbol_decision_snapshots",
    "technical_price_history",
    "technicals",
    "theses",
    "top_source_label",
    "trade_journal",
    "trader_profiles",
    "tradingview_alerts",
    "tradingview_chart_state",
    "tradingview_symbol_search",
    "tradingview_watchlists",
    "trailing_return",
    "true_range_pct_points",
    "universe_screen",
    "valuations",
    "vol_surface_features",
]
