"""Panel route/table contracts shared by API loaders and tests."""

from __future__ import annotations

from typing import Any


PANEL_SCOPE_TABLES: dict[str, tuple[str, ...]] = {
    "feed": ("feed_signals",),
    "today": (
        "feed_signals",
        "decision_queue",
        "discovered_universe",
        "quotes",
        "portfolio",
        "catalysts",
        "earnings",
        "earnings_setups",
        "analyst_estimates",
        "fundamentals",
        "liquidity",
        "correlations",
        "technicals",
        "sepa",
        "valuations",
        "options_payoff_scenarios",
        "options_ticker_signals",
        "candidate_event",
        "radar_alert",
        "option_radar_opportunity",
        "candidate_event_mark",
        "candidate_event_attribution",
        "shadow_trade",
        "shadow_trade_mark",
        "radar_state_transition",
        "trade_journal",
        "vol_surface_features",
        "conviction_calibration",
        "option_attribution",
        "missed_winner_event",
        "strategy_mutation_proposal",
        "strategy_backtest_result",
        "strategy_forward_test_result",
        "strategy_cohort_result",
        "disclosures",
        "theses",
        "thesis_monitor",
        "research_packets",
        "agent_thesis",
        "agent_thesis_request",
        "agent_thesis_validation",
        "ticker_memos",
        "opportunity_sources",
        "daily_brief",
        "exposure_clusters",
        "correlation_edges",
        "portfolio_risk_cards",
        "review_actions",
    ),
    "watchlist": (
        "universe_screen",
        "manual_watchlist",
        "discovered_universe",
        "decision_queue",
        "quotes",
        "portfolio",
        "screener",
        "technicals",
        "valuations",
        "tradingview_watchlists",
        "options_ticker_signals",
    ),
    "sources": (
        "source_ticker_rankings",
        "ticker_source_signals",
        "source_items",
        "source_consensus",
        "feed_signals",
        "opportunity_sources",
        "theses",
        "news",
        "sources",
    ),
    "superinvestors": ("ownership_consensus", "disclosures"),
    "market": ("market_valuation_reference_charts", "market_environment_assets", "market_environment_model"),
    "dashboard": (
        "decision_queue",
        "discovered_universe",
        "quotes",
        "screener",
        "portfolio",
        "catalysts",
        "earnings",
        "earnings_setups",
        "analyst_estimates",
        "fundamentals",
        "etf_premiums",
        "liquidity",
        "correlations",
        "technicals",
        "sepa",
        "valuations",
        "options_expiries",
        "options_payoff_scenarios",
        "options_provider_capabilities",
        "options_expiry_signals",
        "options_ticker_signals",
        "option_strategy_versions",
        "option_radar_opportunity",
        "option_snapshot",
        "option_features",
        "stock_features",
        "agent_thesis",
        "agent_thesis_request",
        "agent_thesis_validation",
        "candidate_event",
        "radar_alert",
        "candidate_event_mark",
        "candidate_event_attribution",
        "shadow_trade",
        "shadow_trade_mark",
        "radar_state_transition",
        "trade_journal",
        "vol_surface_features",
        "conviction_calibration",
        "option_attribution",
        "missed_winner_event",
        "strategy_mutation_proposal",
        "strategy_backtest_result",
        "strategy_forward_test_result",
        "strategy_cohort_result",
        "disclosures",
        "theses",
        "thesis_monitor",
        "research_packets",
        "tradingview_symbol_search",
        "tradingview_watchlists",
        "tradingview_alerts",
        "tradingview_chart_state",
        "opportunity_sources",
        "ticker_source_signals",
        "exposure_clusters",
        "correlation_edges",
        "portfolio_risk_cards",
        "review_actions",
    ),
    "opportunities": (
        "decision_queue",
        "opportunities_ranked",
        "opportunity_sources",
        "signals",
        "candidates",
        "quotes",
        "catalysts",
        "earnings",
        "earnings_setups",
        "analyst_estimates",
        "liquidity",
        "technicals",
        "sepa",
        "valuations",
        "options_expiries",
        "options_payoff_scenarios",
        "options_expiry_signals",
        "options_ticker_signals",
        "candidate_event",
        "radar_alert",
        "option_radar_opportunity",
        "candidate_event_mark",
        "candidate_event_attribution",
        "shadow_trade",
        "shadow_trade_mark",
        "radar_state_transition",
        "trade_journal",
        "vol_surface_features",
        "conviction_calibration",
        "option_attribution",
        "missed_winner_event",
        "strategy_mutation_proposal",
        "strategy_backtest_result",
        "strategy_forward_test_result",
        "strategy_cohort_result",
        "agent_thesis_request",
        "agent_thesis_validation",
        "screener",
        "tradingview_symbol_search",
        "tradingview_watchlists",
        "tradingview_alerts",
        "tradingview_chart_state",
        "portfolio",
        "discovered_universe",
        "exposure_clusters",
        "correlation_edges",
        "portfolio_risk_cards",
        "review_actions",
    ),
    "portfolio": (
        "portfolio",
        "decision_queue",
        "quotes",
        "liquidity",
        "correlations",
        "valuations",
        "technicals",
        "sepa",
        "earnings_setups",
        "theses",
        "thesis_monitor",
        "catalysts",
        "disclosures",
        "exposure_clusters",
        "correlation_edges",
        "portfolio_risk_cards",
        "review_actions",
    ),
    "research": (
        "decision_queue",
        "research_packets",
        "ticker_memos",
        "theses",
        "thesis_monitor",
        "news",
        "fundamentals",
        "signals",
        "quotes",
        "earnings",
        "earnings_setups",
        "analyst_estimates",
        "valuations",
        "options_payoff_scenarios",
        "options_ticker_signals",
        "candidate_event",
        "radar_alert",
        "option_radar_opportunity",
        "candidate_event_mark",
        "candidate_event_attribution",
        "shadow_trade",
        "shadow_trade_mark",
        "radar_state_transition",
        "trade_journal",
        "vol_surface_features",
        "conviction_calibration",
        "option_attribution",
        "missed_winner_event",
        "strategy_mutation_proposal",
        "strategy_backtest_result",
        "strategy_forward_test_result",
        "strategy_cohort_result",
        "agent_thesis_request",
        "agent_thesis_validation",
        "agent_postmortem_request",
        "agent_postmortem",
        "tradingview_alerts",
        "tradingview_chart_state",
    ),
    "options-radar": (
        "option_strategy_versions",
        "option_radar_summary",
        "option_radar_opportunity",
        "radar_alert",
        "candidate_event",
        "candidate_event_mark",
        "candidate_event_attribution",
        "conviction_calibration",
        "vol_surface_features",
        "trade_journal",
        "missed_winner_event",
        "strategy_mutation_proposal",
        "strategy_backtest_result",
        "strategy_forward_test_result",
        "strategy_cohort_result",
        "agent_thesis",
        "agent_thesis_request",
        "agent_thesis_validation",
        "agent_postmortem_request",
        "agent_postmortem",
    ),
    "filings": ("ownership_consensus", "disclosures"),
    "calendar": ("catalysts", "earnings"),
    "health": (
        "sources",
        "source_freshness",
        "source_health",
        "provider_runs",
        "broker_status",
        "broker_accounts",
        "broker_positions",
        "agent_recommendations",
        "agent_thesis",
        "agent_thesis_request",
        "agent_thesis_validation",
        "agent_postmortem_request",
        "agent_postmortem",
        "paper_orders",
    ),
    "settings": (),
}

WATCHLIST_SECTION_TABLES = (
    "universe_screen",
    "manual_watchlist",
    "quotes",
    "fundamentals",
    "technicals",
    "valuations",
    "screener",
    "decision_queue",
    "portfolio",
    "options_ticker_signals",
)

TICKER_TABLES = (
    "candidates",
    "decision_queue",
    "discovered_universe",
    "universe_screen",
    "symbol_decision_snapshot",
    "symbol_decision_snapshots",
    "opportunities_ranked",
    "opportunity_sources",
    "feed_signals",
    "source_consensus",
    "ticker_source_signals",
    "ownership_consensus",
    "portfolio",
    "theses",
    "thesis_monitor",
    "catalysts",
    "signals",
    "fundamentals",
    "disclosures",
    "quotes",
    "options_expiries",
    "options_chain",
    "options_payoff_scenarios",
    "options_provider_capabilities",
    "options_expiry_signals",
    "options_ticker_signals",
    "news",
    "tradingview_symbol_search",
    "tradingview_watchlists",
    "tradingview_alerts",
    "tradingview_chart_state",
    "sepa",
    "liquidity",
    "correlations",
    "etf_premiums",
    "analyst_estimates",
    "earnings",
    "earnings_setups",
    "valuations",
    "technicals",
    "research_packets",
    "exposure_clusters",
    "correlation_edges",
    "portfolio_risk_cards",
    "review_actions",
    "ticker_memos",
)

ENDPOINT_TABLES: dict[str, str] = {
    "decision-readiness": "decision_readiness",
    "candidates": "candidates",
    "opportunities-ranked": "opportunities_ranked",
    "opportunity-sources": "opportunity_sources",
    "discovered-universe": "discovered_universe",
    "decision-queue": "decision_queue",
    "source-freshness": "source_freshness",
    "symbol-decision-snapshots": "symbol_decision_snapshots",
    "portfolio": "portfolio",
    "theses": "theses",
    "thesis-monitor": "thesis_monitor",
    "trader-twins": "trader_twins",
    "catalysts": "catalysts",
    "fundamentals": "fundamentals",
    "disclosures": "disclosures",
    "source-health": "source_health",
    "sources": "sources",
    "source-items": "source_items",
    "source-ticker-rankings": "source_ticker_rankings",
    "source-runs": "source_runs",
    "ticker-source-signals": "ticker_source_signals",
    "quotes": "quotes",
    "screener": "screener",
    "options-expiries": "options_expiries",
    "options-chain": "options_chain",
    "options-payoff-scenarios": "options_payoff_scenarios",
    "options-provider-capabilities": "options_provider_capabilities",
    "options-expiry-signals": "options_expiry_signals",
    "options-ticker-signals": "options_ticker_signals",
    "option-strategy-versions": "option_strategy_versions",
    "option-radar-opportunities": "option_radar_opportunity",
    "radar-alerts": "radar_alert",
    "option-snapshot": "option_snapshot",
    "option-features": "option_features",
    "stock-features": "stock_features",
    "agent-thesis": "agent_thesis",
    "agent-thesis-requests": "agent_thesis_request",
    "agent-thesis-validations": "agent_thesis_validation",
    "agent-postmortem-requests": "agent_postmortem_request",
    "agent-postmortems": "agent_postmortem",
    "candidate-events": "candidate_event",
    "candidate-event-marks": "candidate_event_mark",
    "candidate-event-attributions": "candidate_event_attribution",
    "shadow-trades": "shadow_trade",
    "shadow-trade-marks": "shadow_trade_mark",
    "radar-state-transitions": "radar_state_transition",
    "option-attributions": "option_attribution",
    "missed-winner-events": "missed_winner_event",
    "strategy-mutation-proposals": "strategy_mutation_proposal",
    "strategy-backtests": "strategy_backtest_result",
    "strategy-forward-tests": "strategy_forward_test_result",
    "strategy-cohorts": "strategy_cohort_result",
    "news": "news",
    "tradingview-symbol-search": "tradingview_symbol_search",
    "tradingview-watchlists": "tradingview_watchlists",
    "tradingview-alerts": "tradingview_alerts",
    "tradingview-chart-state": "tradingview_chart_state",
    "sepa": "sepa",
    "liquidity": "liquidity",
    "correlations": "correlations",
    "etf-premiums": "etf_premiums",
    "analyst-estimates": "analyst_estimates",
    "earnings": "earnings",
    "earnings-setups": "earnings_setups",
    "valuations": "valuations",
    "technicals": "technicals",
    "research-packets": "research_packets",
    "memos": "ticker_memos",
    "provider-runs": "provider_runs",
    "broker/status": "broker_status",
    "broker/accounts": "broker_accounts",
    "broker/positions": "broker_positions",
    "agent/recommendations": "agent_recommendations",
    "paper-orders": "paper_orders",
    "daily-brief": "daily_brief",
    "feed": "feed_signals",
    "watchlist-screen": "universe_screen",
    "watchlist/symbols": "manual_watchlist",
    "source-consensus": "source_consensus",
    "ownership-consensus": "ownership_consensus",
    "market-context": "market_context",
    "portfolio-risk/exposure-clusters": "exposure_clusters",
    "portfolio-risk/correlation-edges": "correlation_edges",
    "portfolio-risk/cards": "portfolio_risk_cards",
    "portfolio-risk/review-actions": "review_actions",
}

DECISION_REPAIR_TABLES = {
    "decision_readiness",
    "decision_queue",
    "discovered_universe",
    "feed_signals",
    "source_freshness",
    "symbol_decision_snapshot",
    "symbol_decision_snapshots",
    "thesis_monitor",
    "universe_screen",
}

SOURCE_REPAIR_TABLES = {
    "feed_signals",
    "news",
    "opportunity_sources",
    "source_consensus",
    "source_items",
    "source_runs",
    "source_ticker_rankings",
    "sources",
    "ticker_source_signals",
}

FRONTEND_TABLE_KEY_OVERRIDES = {
    "ticker_memos": "memos",
}

WATCHLIST_SECTION_OUTPUT_TABLES = (
    "watchlist_watched",
    "watchlist_unwatched",
    "watchlist_watched_quotes",
    "watchlist_unwatched_quotes",
    "watchlist_watched_fundamentals",
    "watchlist_unwatched_fundamentals",
    "watchlist_watched_technicals",
    "watchlist_unwatched_technicals",
    "watchlist_watched_valuations",
    "watchlist_unwatched_valuations",
    "watchlist_watched_screener",
    "watchlist_unwatched_screener",
    "watchlist_watched_decision_queue",
    "watchlist_unwatched_decision_queue",
    "watchlist_watched_portfolio",
    "watchlist_unwatched_portfolio",
    "watchlist_watched_options",
    "watchlist_unwatched_options",
)


def tables_for_scope(scope: str) -> tuple[str, ...]:
    if scope in {"watchlist-watched", "watchlist-unwatched"}:
        return WATCHLIST_SECTION_TABLES
    return PANEL_SCOPE_TABLES.get(scope, PANEL_SCOPE_TABLES["dashboard"])


def table_for_endpoint(endpoint_key: str) -> str:
    return ENDPOINT_TABLES[endpoint_key]


def panel_snapshot_table_names() -> frozenset[str]:
    names: set[str] = set()
    for scope, tables in PANEL_SCOPE_TABLES.items():
        if scope != "settings":
            names.update(tables)
    names.update(WATCHLIST_SECTION_OUTPUT_TABLES)
    return frozenset(names)


def frontend_key_for_table(table_name: str) -> str:
    if table_name in FRONTEND_TABLE_KEY_OVERRIDES:
        return FRONTEND_TABLE_KEY_OVERRIDES[table_name]
    head, *tail = table_name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in tail)


def panel_contract_payload() -> dict[str, Any]:
    return {
        "scopes": {scope: list(tables) for scope, tables in PANEL_SCOPE_TABLES.items()},
        "watchlist_section_tables": list(WATCHLIST_SECTION_TABLES),
        "watchlist_section_output_tables": list(WATCHLIST_SECTION_OUTPUT_TABLES),
        "ticker_tables": list(TICKER_TABLES),
        "endpoint_tables": dict(ENDPOINT_TABLES),
        "frontend_table_keys": {
            table_name: frontend_key_for_table(table_name)
            for table_name in sorted(panel_snapshot_table_names())
        },
    }
