"""Add immutable manual account reconciliation snapshots."""

from __future__ import annotations

from alembic import op


revision = "20260905_0092"
down_revision = "20260905_0091"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE app.manual_account_snapshot (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          account_key TEXT NOT NULL DEFAULT 'manual',
          currency TEXT NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
          effective_at TIMESTAMPTZ NOT NULL,
          recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          cash_balance NUMERIC(20, 4) NOT NULL CHECK (cash_balance >= 0),
          net_liquidation NUMERIC(20, 4) CHECK (net_liquidation >= 0),
          reconciliation_state TEXT NOT NULL CHECK (reconciliation_state IN ('pending', 'reconciled')),
          reconciliation_version INTEGER NOT NULL CHECK (reconciliation_version > 0),
          ledger_book_identity TEXT NOT NULL,
          idempotency_key TEXT NOT NULL UNIQUE,
          notes TEXT NOT NULL DEFAULT ''
        );
        CREATE INDEX ix_manual_account_snapshot_effective
          ON app.manual_account_snapshot (account_key, effective_at DESC, id DESC);
        CREATE OR REPLACE FUNCTION app.prevent_manual_account_snapshot_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'manual account snapshots are append-only';
        END;
        $$;
        CREATE TRIGGER manual_account_snapshot_immutable
          BEFORE UPDATE OR DELETE ON app.manual_account_snapshot
          FOR EACH ROW EXECUTE FUNCTION app.prevent_manual_account_snapshot_mutation();
        GRANT SELECT, INSERT ON app.manual_account_snapshot TO market_app;
        GRANT USAGE, SELECT ON SEQUENCE app.manual_account_snapshot_id_seq TO market_app;
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS manual_account_snapshot_immutable ON app.manual_account_snapshot;")
    op.execute("DROP FUNCTION IF EXISTS app.prevent_manual_account_snapshot_mutation();")
    op.execute("DROP TABLE IF EXISTS app.manual_account_snapshot;")
