"""Version post-fix option-history canaries by model revision and start time.

Revision ID: 20260721_0013
Revises: 20260720_0012
"""

from __future__ import annotations

from alembic import op


revision = "20260721_0013"
down_revision = "20260720_0012"
branch_labels = None
depends_on = None

MODEL_REVISION = "history-v3-price-shape-r2"


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE analysis.option_history_canary (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            model_revision TEXT NOT NULL,
            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (model_revision, started_at)
        )
        """
    )
    # A capture must finish after this record to advance the new live canary.
    # Historical generations remain replayable but can never become canary days.
    op.execute(
        "INSERT INTO analysis.option_history_canary (model_revision) VALUES ('%s')" % MODEL_REVISION
    )


def downgrade() -> None:
    op.execute("DROP TABLE analysis.option_history_canary")
