"""Add durable, source-faithful historical option-chain storage.

Revision ID: 20260718_0010
Revises: 20260716_0009
"""

from __future__ import annotations

from alembic import op


revision = "20260718_0010"
down_revision = "20260716_0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN collection_profile TEXT NOT NULL DEFAULT 'radar'")
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN history_symbol TEXT")
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN slot_at TIMESTAMPTZ")
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN capture_started_at TIMESTAMPTZ")
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN capture_finished_at TIMESTAMPTZ")
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN expected_contract_count INTEGER")
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN received_contract_count INTEGER")
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN capture_state TEXT NOT NULL DEFAULT 'complete'")
    op.execute("ALTER TABLE raw.option_snapshot ADD CONSTRAINT ck_option_snapshot_profile CHECK (collection_profile IN ('radar', 'history_full'))")
    op.execute("ALTER TABLE raw.option_snapshot ADD CONSTRAINT ck_option_snapshot_capture_state CHECK (capture_state IN ('running', 'complete', 'partial', 'failed'))")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN previous_close DOUBLE PRECISION")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN provider_rho DOUBLE PRECISION")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN chance_of_profit_long DOUBLE PRECISION")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN chance_of_profit_short DOUBLE PRECISION")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN provider_updated_at TIMESTAMPTZ")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN provider_payload JSONB NOT NULL DEFAULT '{}'::jsonb")
    op.execute("CREATE UNIQUE INDEX ux_raw_option_snapshot_history_slot ON raw.option_snapshot (source_id, collection_profile, history_symbol, slot_at) WHERE collection_profile = 'history_full'")
    op.execute("CREATE INDEX ix_raw_option_snapshot_history_lookup ON raw.option_snapshot (history_symbol, collection_profile, capture_state, slot_at DESC)")
    op.execute("CREATE INDEX ix_raw_option_quote_history_chain ON raw.option_quote (snapshot_id, contract_id) INCLUDE (provider_iv, bid, ask, volume, open_interest)")
    op.execute(
        """
        CREATE TABLE analysis.option_surface_summary (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_id BIGINT NOT NULL REFERENCES raw.option_snapshot(id) ON DELETE CASCADE,
            expiration DATE NOT NULL,
            option_type TEXT NOT NULL CHECK (option_type IN ('call', 'put')),
            feature_version TEXT NOT NULL,
            dte INTEGER NOT NULL,
            atm_iv DOUBLE PRECISION,
            delta_25_iv DOUBLE PRECISION,
            skew_25 DOUBLE PRECISION,
            smile_slope DOUBLE PRECISION,
            smile_curvature DOUBLE PRECISION,
            term_slope DOUBLE PRECISION,
            average_spread_pct DOUBLE PRECISION,
            liquidity_score DOUBLE PRECISION,
            atm_iv_change DOUBLE PRECISION,
            skew_25_change DOUBLE PRECISION,
            term_slope_change DOUBLE PRECISION,
            metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (snapshot_id, expiration, option_type, feature_version)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE analysis.option_history_anomaly (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_id BIGINT NOT NULL REFERENCES raw.option_snapshot(id) ON DELETE CASCADE,
            contract_id BIGINT REFERENCES catalog.option_contract(id),
            expiration DATE,
            option_type TEXT CHECK (option_type IN ('call', 'put')),
            anomaly_type TEXT NOT NULL,
            state TEXT NOT NULL CHECK (state IN ('active', 'collecting')),
            observed_value DOUBLE PRECISION,
            expected_value DOUBLE PRECISION,
            z_score DOUBLE PRECISION,
            details JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_analysis_option_surface_history ON analysis.option_surface_summary (snapshot_id, expiration, option_type)")
    op.execute("CREATE INDEX ix_analysis_option_anomaly_snapshot ON analysis.option_history_anomaly (snapshot_id, state, anomaly_type)")


def downgrade() -> None:
    op.execute("DROP TABLE analysis.option_history_anomaly")
    op.execute("DROP TABLE analysis.option_surface_summary")
    op.execute("DROP INDEX raw.ix_raw_option_quote_history_chain")
    op.execute("DROP INDEX raw.ix_raw_option_snapshot_history_lookup")
    op.execute("DROP INDEX raw.ux_raw_option_snapshot_history_slot")
    op.execute("ALTER TABLE raw.option_quote DROP COLUMN provider_payload")
    op.execute("ALTER TABLE raw.option_quote DROP COLUMN provider_updated_at")
    op.execute("ALTER TABLE raw.option_quote DROP COLUMN chance_of_profit_short")
    op.execute("ALTER TABLE raw.option_quote DROP COLUMN chance_of_profit_long")
    op.execute("ALTER TABLE raw.option_quote DROP COLUMN provider_rho")
    op.execute("ALTER TABLE raw.option_quote DROP COLUMN previous_close")
    op.execute("ALTER TABLE raw.option_snapshot DROP CONSTRAINT ck_option_snapshot_capture_state")
    op.execute("ALTER TABLE raw.option_snapshot DROP CONSTRAINT ck_option_snapshot_profile")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN capture_state")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN received_contract_count")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN expected_contract_count")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN capture_finished_at")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN capture_started_at")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN slot_at")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN history_symbol")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN collection_profile")
