"""Add option-history symbol policy and provider leases.

Revision ID: 20260722_0015
Revises: 20260722_0014
"""

from __future__ import annotations

from alembic import op


revision = "20260722_0015"
down_revision = "20260722_0014"
branch_labels = None
depends_on = None

POLICY_REVISION = "options-chain-reliability-20260722"


def upgrade() -> None:
    op.execute("ALTER TABLE raw.option_snapshot DROP CONSTRAINT IF EXISTS ck_option_snapshot_capture_state")
    op.execute(
        """
        ALTER TABLE raw.option_snapshot
        ADD CONSTRAINT ck_option_snapshot_capture_state
        CHECK (capture_state IN ('running', 'complete', 'partial', 'failed', 'deferred'))
        """
    )
    op.execute("ALTER TABLE raw.option_capture_generation DROP CONSTRAINT IF EXISTS option_capture_generation_capture_state_check")
    op.execute(
        """
        ALTER TABLE raw.option_capture_generation
        ADD CONSTRAINT option_capture_generation_capture_state_check
        CHECK (capture_state IN ('running', 'complete', 'partial', 'failed', 'deferred'))
        """
    )
    op.execute(
        """
        CREATE TABLE app.option_history_policy (
            instrument_id BIGINT PRIMARY KEY REFERENCES catalog.instrument(id) ON DELETE RESTRICT,
            requested_state TEXT NOT NULL DEFAULT 'off',
            effective_state TEXT NOT NULL DEFAULT 'disabled',
            collection_tier TEXT NOT NULL DEFAULT 'standard',
            cadence_minutes INTEGER NOT NULL DEFAULT 60,
            publication_cap TEXT NOT NULL DEFAULT 'WATCH',
            provider TEXT NOT NULL DEFAULT 'robinhood',
            normalized_retention_days INTEGER NOT NULL DEFAULT 730,
            derived_retention_days INTEGER NOT NULL DEFAULT 730,
            provider_payload_retention_days INTEGER NOT NULL DEFAULT 90,
            policy_revision TEXT NOT NULL DEFAULT 'options-chain-reliability-20260722',
            lock_version INTEGER NOT NULL DEFAULT 0,
            reason TEXT,
            activated_at TIMESTAMPTZ,
            paused_at TIMESTAMPTZ,
            requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_option_history_policy_requested CHECK (requested_state IN ('on', 'off')),
            CONSTRAINT ck_option_history_policy_effective CHECK (effective_state IN ('disabled', 'pending_gate', 'shadow', 'active', 'paused')),
            CONSTRAINT ck_option_history_policy_tier CHECK (collection_tier IN ('core', 'standard')),
            CONSTRAINT ck_option_history_policy_cadence CHECK (cadence_minutes IN (15, 60)),
            CONSTRAINT ck_option_history_policy_cap CHECK (publication_cap IN ('WATCH', 'PAPER_READY')),
            CONSTRAINT ck_option_history_policy_retention CHECK (
                normalized_retention_days = 730
                AND derived_retention_days = 730
                AND provider_payload_retention_days = 90
            )
        )
        """
    )
    op.execute("CREATE INDEX ix_option_history_policy_state ON app.option_history_policy (requested_state, effective_state, collection_tier)")
    op.execute(
        """
        CREATE TABLE ops.provider_lease (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider TEXT NOT NULL,
            workload TEXT NOT NULL,
            symbol TEXT NOT NULL,
            owner TEXT NOT NULL,
            heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at TIMESTAMPTZ NOT NULL,
            acquired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            metadata JSONB NOT NULL DEFAULT '{}'::jsonb
        )
        """
    )
    op.execute("CREATE INDEX ix_provider_lease_active ON ops.provider_lease (provider, expires_at DESC, workload, symbol)")
    _seed_symbol("QQQ", "active", "core", 15, "PAPER_READY", "core 15-minute QQQ history")
    _seed_symbol("NVDA", "shadow", "standard", 60, "WATCH", "early NVDA hourly shadow exception")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ops.ix_provider_lease_active")
    op.execute("DROP TABLE IF EXISTS ops.provider_lease")
    op.execute("DROP INDEX IF EXISTS app.ix_option_history_policy_state")
    op.execute("DROP TABLE IF EXISTS app.option_history_policy")
    op.execute("ALTER TABLE raw.option_capture_generation DROP CONSTRAINT IF EXISTS option_capture_generation_capture_state_check")
    op.execute(
        """
        ALTER TABLE raw.option_capture_generation
        ADD CONSTRAINT option_capture_generation_capture_state_check
        CHECK (capture_state IN ('running', 'complete', 'partial', 'failed'))
        """
    )
    op.execute("ALTER TABLE raw.option_snapshot DROP CONSTRAINT IF EXISTS ck_option_snapshot_capture_state")
    op.execute(
        """
        ALTER TABLE raw.option_snapshot
        ADD CONSTRAINT ck_option_snapshot_capture_state
        CHECK (capture_state IN ('running', 'complete', 'partial', 'failed'))
        """
    )


def _seed_symbol(symbol: str, state: str, tier: str, cadence: int, cap: str, reason: str) -> None:
    op.execute(
        f"""
        WITH instrument_row AS (
            INSERT INTO catalog.instrument (symbol, name, asset_class, category, market_timezone)
            VALUES ('{symbol}', '{symbol}', 'equity', 'option-history', 'America/New_York')
            ON CONFLICT (symbol) DO UPDATE
            SET market_timezone = EXCLUDED.market_timezone,
                category = COALESCE(catalog.instrument.category, EXCLUDED.category),
                updated_at = now()
            RETURNING id
        )
        INSERT INTO app.option_history_policy
            (instrument_id, requested_state, effective_state, collection_tier, cadence_minutes,
             publication_cap, provider, normalized_retention_days, derived_retention_days,
             provider_payload_retention_days, policy_revision, reason, activated_at)
        SELECT id, 'on', '{state}', '{tier}', {cadence}, '{cap}', 'robinhood',
               730, 730, 90, '{POLICY_REVISION}', '{reason}',
               CASE WHEN '{state}' IN ('active', 'shadow') THEN now() ELSE NULL END
        FROM instrument_row
        ON CONFLICT (instrument_id) DO UPDATE
        SET requested_state = EXCLUDED.requested_state,
            effective_state = EXCLUDED.effective_state,
            collection_tier = EXCLUDED.collection_tier,
            cadence_minutes = EXCLUDED.cadence_minutes,
            publication_cap = EXCLUDED.publication_cap,
            provider = EXCLUDED.provider,
            normalized_retention_days = EXCLUDED.normalized_retention_days,
            derived_retention_days = EXCLUDED.derived_retention_days,
            provider_payload_retention_days = EXCLUDED.provider_payload_retention_days,
            policy_revision = EXCLUDED.policy_revision,
            reason = EXCLUDED.reason,
            activated_at = COALESCE(app.option_history_policy.activated_at, EXCLUDED.activated_at),
            updated_at = now()
        """
    )
