"""Add verified NAS archive metadata without moving live data.

Revision ID: 20260815_0037
Revises: 20260813_0036

Archive and compaction work is intentionally performed by resumable jobs.  An
Alembic transaction must never copy, rewrite, or delete a large Market table.
"""

from __future__ import annotations

from alembic import op


revision = "20260815_0037"
down_revision = "20260813_0036"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE ops.storage_archive_manifest (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            archive_kind TEXT NOT NULL,
            source_relation TEXT NOT NULL,
            nas_uri TEXT NOT NULL,
            sha256 CHAR(64) NOT NULL,
            format TEXT NOT NULL,
            row_count BIGINT NOT NULL DEFAULT 0 CHECK (row_count >= 0),
            range_start TIMESTAMPTZ,
            range_end TIMESTAMPTZ,
            schema_revision TEXT NOT NULL,
            verification_status TEXT NOT NULL DEFAULT 'pending'
                CHECK (verification_status IN ('pending', 'written', 'verified', 'failed', 'restored')),
            verified_at TIMESTAMPTZ,
            metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (nas_uri),
            UNIQUE (archive_kind, sha256)
        );

        CREATE INDEX ix_storage_archive_manifest_status
            ON ops.storage_archive_manifest (verification_status, archive_kind, created_at DESC);

        CREATE TABLE ops.storage_archive_checkpoint (
            checkpoint_key TEXT PRIMARY KEY,
            archive_kind TEXT NOT NULL,
            source_relation TEXT NOT NULL,
            cursor JSONB NOT NULL DEFAULT '{}'::jsonb,
            run_status TEXT NOT NULL DEFAULT 'idle'
                CHECK (run_status IN ('idle', 'running', 'paused', 'succeeded', 'failed')),
            counts JSONB NOT NULL DEFAULT '{}'::jsonb,
            error_detail TEXT,
            started_at TIMESTAMPTZ,
            finished_at TIMESTAMPTZ,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        ALTER TABLE app.option_history_policy
            ADD COLUMN hot_retention_days INTEGER NOT NULL DEFAULT 7
                CHECK (hot_retention_days >= 0),
            ADD COLUMN archive_retention_days INTEGER NOT NULL DEFAULT 730
                CHECK (archive_retention_days >= 0);

        """
    )
    # This raw relation can be large and active.  Do not block ingestion while
    # PostgreSQL scans it to build the payload lookup index.
    with op.get_context().autocommit_block():
        op.execute(
            "CREATE INDEX CONCURRENTLY ix_raw_fundamental_observation_payload "
            "ON raw.fundamental_observation (payload_id) WHERE payload_id IS NOT NULL"
        )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS raw.ix_raw_fundamental_observation_payload")
    op.execute("ALTER TABLE app.option_history_policy DROP COLUMN IF EXISTS archive_retention_days")
    op.execute("ALTER TABLE app.option_history_policy DROP COLUMN IF EXISTS hot_retention_days")
    op.execute("DROP TABLE IF EXISTS ops.storage_archive_checkpoint")
    op.execute("DROP TABLE IF EXISTS ops.storage_archive_manifest")
