"""Add the versioned ticker-first decision and shared-expression ledger.

Revision ID: 20260822_0049
Revises: 20260822_0048
"""

from __future__ import annotations

from alembic import op


revision = "20260822_0049"
down_revision = "20260822_0048"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analysis.ticker_decision (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id) ON DELETE RESTRICT,
            decision_revision TEXT NOT NULL,
            contract_version TEXT NOT NULL,
            as_of TIMESTAMPTZ NOT NULL,
            published_at TIMESTAMPTZ,
            input_hash CHAR(64) NOT NULL,
            code_version TEXT NOT NULL,
            experiment_id TEXT NOT NULL,
            tactical JSONB NOT NULL,
            fundamental JSONB NOT NULL,
            capital_action JSONB NOT NULL,
            risk_policy JSONB NOT NULL,
            expressions JSONB NOT NULL DEFAULT '{}'::jsonb,
            selected_expression JSONB,
            data_requests JSONB NOT NULL DEFAULT '[]'::jsonb,
            learning_history JSONB NOT NULL DEFAULT '[]'::jsonb,
            input_manifest JSONB NOT NULL DEFAULT '{}'::jsonb,
            status TEXT NOT NULL DEFAULT 'published'
                CHECK (status IN ('draft', 'published', 'superseded', 'quarantined')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (instrument_id, decision_revision)
        );

        CREATE INDEX IF NOT EXISTS ix_ticker_decision_latest
            ON analysis.ticker_decision (instrument_id, as_of DESC, created_at DESC);
        CREATE INDEX IF NOT EXISTS ix_ticker_decision_revision
            ON analysis.ticker_decision (input_hash, code_version, experiment_id);

        CREATE TABLE IF NOT EXISTS analysis.ticker_benchmark_snapshot (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            benchmark_key TEXT NOT NULL,
            as_of TIMESTAMPTZ NOT NULL,
            available_at TIMESTAMPTZ NOT NULL,
            membership_hash CHAR(64) NOT NULL,
            member_count INTEGER NOT NULL CHECK (member_count >= 0),
            source_id TEXT NOT NULL,
            source_version TEXT,
            exact_membership JSONB NOT NULL DEFAULT '[]'::jsonb,
            coverage JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (benchmark_key, as_of)
        );
        CREATE INDEX IF NOT EXISTS ix_ticker_benchmark_latest
            ON analysis.ticker_benchmark_snapshot (benchmark_key, as_of DESC);

        CREATE TABLE IF NOT EXISTS analysis.ticker_input_manifest (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ticker_decision_id UUID NOT NULL REFERENCES analysis.ticker_decision(id) ON DELETE CASCADE,
            field TEXT NOT NULL,
            source_id TEXT NOT NULL,
            source_version TEXT,
            event_at TIMESTAMPTZ,
            published_at TIMESTAMPTZ,
            available_at TIMESTAMPTZ NOT NULL,
            received_at TIMESTAMPTZ,
            revision TEXT,
            license TEXT,
            original_value JSONB,
            revised_value JSONB,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (ticker_decision_id, field, source_id, available_at, revision)
        );
        CREATE INDEX IF NOT EXISTS ix_ticker_input_manifest_pit
            ON analysis.ticker_input_manifest (field, available_at, ticker_decision_id);

        CREATE TABLE IF NOT EXISTS analysis.ticker_data_request (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            ticker_decision_id UUID NOT NULL REFERENCES analysis.ticker_decision(id) ON DELETE CASCADE,
            field TEXT NOT NULL,
            ticker TEXT NOT NULL,
            request JSONB NOT NULL,
            status TEXT NOT NULL DEFAULT 'open'
                CHECK (status IN ('open', 'running', 'complete', 'failed', 'superseded')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            completed_at TIMESTAMPTZ,
            UNIQUE (ticker_decision_id, field)
        );
        CREATE INDEX IF NOT EXISTS ix_ticker_data_request_status
            ON analysis.ticker_data_request (status, created_at DESC);

        CREATE TABLE IF NOT EXISTS analysis.ticker_outcome (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            ticker_decision_id UUID NOT NULL REFERENCES analysis.ticker_decision(id) ON DELETE RESTRICT,
            horizon TEXT NOT NULL CHECK (horizon IN ('TACTICAL', 'FUNDAMENTAL')),
            horizon_sessions INTEGER NOT NULL CHECK (horizon_sessions IN (1, 5, 20, 63, 126, 252)),
            state TEXT NOT NULL DEFAULT 'observing'
                CHECK (state IN ('observing', 'resolved', 'quarantined', 'unmeasurable')),
            measured_through TIMESTAMPTZ,
            selected_expression TEXT,
            selected_return DOUBLE PRECISION,
            stock_counterfactual_return DOUBLE PRECISION,
            alternate_counterfactual_return DOUBLE PRECISION,
            cash_return DOUBLE PRECISION,
            sector_return DOUBLE PRECISION,
            market_return DOUBLE PRECISION,
            error_type TEXT,
            mistake_card JSONB NOT NULL DEFAULT '{}'::jsonb,
            available_at TIMESTAMPTZ,
            metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (ticker_decision_id, horizon, horizon_sessions)
        );
        CREATE INDEX IF NOT EXISTS ix_ticker_outcome_learning
            ON analysis.ticker_outcome (horizon, state, horizon_sessions, measured_through);

        ALTER TABLE app.paper_order
            ADD COLUMN IF NOT EXISTS ticker_decision_id UUID REFERENCES analysis.ticker_decision(id) ON DELETE RESTRICT,
            ADD COLUMN IF NOT EXISTS ticker_decision_revision TEXT,
            ADD COLUMN IF NOT EXISTS expression_kind TEXT,
            ADD COLUMN IF NOT EXISTS max_loss NUMERIC(20, 6),
            ADD COLUMN IF NOT EXISTS planned_loss NUMERIC(20, 6),
            ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ,
            ADD COLUMN IF NOT EXISTS thesis_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
            ADD COLUMN IF NOT EXISTS paper_only BOOLEAN NOT NULL DEFAULT TRUE;
        ALTER TABLE app.paper_order DROP CONSTRAINT IF EXISTS ck_app_paper_order_lane;
        ALTER TABLE app.paper_order
            ADD CONSTRAINT ck_app_paper_order_lane
            CHECK (lane IN ('radar', 'qqq', 'recovery', 'ticker'));
        CREATE INDEX IF NOT EXISTS ix_app_paper_order_ticker_revision
            ON app.paper_order (ticker_decision_revision, expression_kind, status, created_at DESC);
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS app.ix_app_paper_order_ticker_revision")
    op.execute("ALTER TABLE app.paper_order DROP CONSTRAINT IF EXISTS ck_app_paper_order_lane")
    op.execute(
        "ALTER TABLE app.paper_order ADD CONSTRAINT ck_app_paper_order_lane CHECK (lane IN ('radar', 'qqq', 'recovery'))"
    )
    for column in (
        "paper_only", "thesis_snapshot", "expires_at", "planned_loss", "max_loss",
        "expression_kind", "ticker_decision_revision", "ticker_decision_id",
    ):
        op.execute(f"ALTER TABLE app.paper_order DROP COLUMN IF EXISTS {column}")
    op.execute("DROP INDEX IF EXISTS analysis.ix_ticker_outcome_learning")
    op.execute("DROP TABLE IF EXISTS analysis.ticker_outcome")
    op.execute("DROP INDEX IF EXISTS analysis.ix_ticker_data_request_status")
    op.execute("DROP TABLE IF EXISTS analysis.ticker_data_request")
    op.execute("DROP INDEX IF EXISTS analysis.ix_ticker_input_manifest_pit")
    op.execute("DROP TABLE IF EXISTS analysis.ticker_input_manifest")
    op.execute("DROP INDEX IF EXISTS analysis.ix_ticker_decision_revision")
    op.execute("DROP INDEX IF EXISTS analysis.ix_ticker_decision_latest")
    op.execute("DROP INDEX IF EXISTS analysis.ix_ticker_benchmark_latest")
    op.execute("DROP TABLE IF EXISTS analysis.ticker_benchmark_snapshot")
    op.execute("DROP TABLE IF EXISTS analysis.ticker_decision")
