"""Create the PostgreSQL authority schemas.

Revision ID: 20260711_0001
Revises: None
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "20260711_0001"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA_DDL = [
    "CREATE EXTENSION IF NOT EXISTS pgcrypto",
    "CREATE SCHEMA catalog",
    "CREATE SCHEMA ingest",
    "CREATE SCHEMA raw",
    "CREATE SCHEMA analysis",
    "CREATE SCHEMA app",
    "CREATE SCHEMA ops",
    """
    CREATE TABLE catalog.instrument (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        symbol TEXT NOT NULL UNIQUE,
        name TEXT,
        asset_class TEXT NOT NULL,
        sector TEXT,
        industry TEXT,
        category TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE catalog.instrument_alias (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id) ON DELETE CASCADE,
        provider TEXT NOT NULL,
        external_symbol TEXT NOT NULL,
        exchange TEXT NOT NULL DEFAULT '',
        currency TEXT,
        metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (provider, external_symbol, exchange)
    )
    """,
    """
    CREATE TABLE catalog.option_contract (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        underlying_instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        expiration DATE NOT NULL,
        strike NUMERIC(20, 6) NOT NULL,
        option_type TEXT NOT NULL CHECK (option_type IN ('call', 'put')),
        multiplier INTEGER NOT NULL DEFAULT 100 CHECK (multiplier > 0),
        style TEXT,
        settlement TEXT,
        provider_symbols JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (underlying_instrument_id, expiration, strike, option_type, multiplier)
    )
    """,
    """
    CREATE TABLE ingest.source (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        family TEXT NOT NULL,
        kind TEXT NOT NULL,
        origin TEXT,
        enabled BOOLEAN NOT NULL DEFAULT true,
        ingestion_mode TEXT,
        source_url TEXT,
        capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
        config JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE ingest.run (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        source_run_key TEXT,
        capability TEXT NOT NULL,
        started_at TIMESTAMPTZ NOT NULL,
        finished_at TIMESTAMPTZ,
        status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'partial', 'failed', 'skipped')),
        item_count INTEGER NOT NULL DEFAULT 0,
        instrument_count INTEGER NOT NULL DEFAULT 0,
        failure_detail TEXT,
        summary JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (source_id, source_run_key)
    )
    """,
    """
    CREATE TABLE ingest.payload (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id UUID NOT NULL REFERENCES ingest.run(id) ON DELETE CASCADE,
        archive_uri TEXT NOT NULL,
        sha256 CHAR(64) NOT NULL,
        encoding TEXT NOT NULL,
        byte_count BIGINT NOT NULL CHECK (byte_count >= 0),
        schema_version TEXT,
        metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (sha256)
    )
    """,
    """
    CREATE TABLE raw.content_item (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        payload_id BIGINT REFERENCES ingest.payload(id),
        source_key TEXT NOT NULL,
        kind TEXT NOT NULL,
        title TEXT,
        url TEXT,
        author TEXT,
        published_at TIMESTAMPTZ,
        observed_at TIMESTAMPTZ NOT NULL,
        summary TEXT,
        content_hash CHAR(64),
        license_status TEXT,
        metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (source_id, source_key)
    )
    """,
    """
    CREATE TABLE raw.content_item_instrument (
        content_item_id BIGINT NOT NULL REFERENCES raw.content_item(id) ON DELETE CASCADE,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        relevance DOUBLE PRECISION,
        PRIMARY KEY (content_item_id, instrument_id)
    )
    """,
    """
    CREATE TABLE raw.price_bar (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        payload_id BIGINT REFERENCES ingest.payload(id),
        interval TEXT NOT NULL DEFAULT '1d',
        trading_date DATE NOT NULL,
        observed_at TIMESTAMPTZ NOT NULL,
        open DOUBLE PRECISION,
        high DOUBLE PRECISION,
        low DOUBLE PRECISION,
        close DOUBLE PRECISION NOT NULL,
        volume DOUBLE PRECISION,
        currency TEXT,
        UNIQUE (instrument_id, source_id, interval, observed_at)
    )
    """,
    """
    CREATE TABLE raw.quote (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        payload_id BIGINT REFERENCES ingest.payload(id),
        observed_at TIMESTAMPTZ NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        change_abs DOUBLE PRECISION,
        change_pct DOUBLE PRECISION,
        currency TEXT,
        UNIQUE (instrument_id, source_id, observed_at)
    )
    """,
    """
    CREATE TABLE raw.fundamental_observation (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        payload_id BIGINT REFERENCES ingest.payload(id),
        metric_set TEXT NOT NULL,
        period_end DATE,
        filed_at TIMESTAMPTZ,
        observed_at TIMESTAMPTZ NOT NULL,
        values JSONB NOT NULL,
        UNIQUE (instrument_id, source_id, metric_set, period_end, observed_at)
    )
    """,
    """
    CREATE TABLE raw.market_event (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT REFERENCES catalog.instrument(id),
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        payload_id BIGINT REFERENCES ingest.payload(id),
        source_key TEXT NOT NULL,
        event_scope TEXT NOT NULL,
        event_kind TEXT NOT NULL,
        title TEXT NOT NULL,
        starts_at TIMESTAMPTZ NOT NULL,
        ends_at TIMESTAMPTZ,
        importance TEXT,
        verification_status TEXT,
        source_url TEXT,
        details JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (source_id, source_key)
    )
    """,
    """
    CREATE TABLE raw.disclosure (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT REFERENCES catalog.instrument(id),
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        payload_id BIGINT REFERENCES ingest.payload(id),
        source_key TEXT NOT NULL,
        source_type TEXT NOT NULL,
        trader_name TEXT,
        filer_name TEXT,
        event_date DATE,
        filed_date DATE,
        action TEXT,
        amount_text TEXT,
        source_url TEXT,
        details JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (source_id, source_key)
    )
    """,
    """
    CREATE TABLE raw.option_snapshot (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        payload_id BIGINT REFERENCES ingest.payload(id),
        observed_at TIMESTAMPTZ NOT NULL,
        trading_date DATE NOT NULL,
        market_session TEXT NOT NULL CHECK (market_session IN ('premarket', 'regular', 'afterhours', 'closed', 'unknown')),
        universe TEXT NOT NULL,
        completeness DOUBLE PRECISION CHECK (completeness BETWEEN 0 AND 1),
        contract_count INTEGER NOT NULL DEFAULT 0,
        UNIQUE (source_id, observed_at, universe)
    )
    """,
    """
    CREATE TABLE raw.option_quote (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        observed_at TIMESTAMPTZ NOT NULL,
        snapshot_id BIGINT NOT NULL REFERENCES raw.option_snapshot(id) ON DELETE CASCADE,
        contract_id BIGINT NOT NULL REFERENCES catalog.option_contract(id),
        underlying_price DOUBLE PRECISION,
        bid DOUBLE PRECISION,
        ask DOUBLE PRECISION,
        mid DOUBLE PRECISION,
        last DOUBLE PRECISION,
        volume BIGINT,
        open_interest BIGINT,
        provider_iv DOUBLE PRECISION,
        provider_delta DOUBLE PRECISION,
        provider_gamma DOUBLE PRECISION,
        provider_theta DOUBLE PRECISION,
        provider_vega DOUBLE PRECISION,
        UNIQUE (snapshot_id, contract_id, observed_at)
    ) PARTITION BY RANGE (observed_at)
    """,
    "CREATE TABLE raw.option_quote_default PARTITION OF raw.option_quote DEFAULT",
    """
    CREATE TABLE raw.broker_account_snapshot (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        account_key TEXT NOT NULL,
        observed_at TIMESTAMPTZ NOT NULL,
        currency TEXT,
        net_liquidation NUMERIC(20, 4),
        buying_power NUMERIC(20, 4),
        cash_balance NUMERIC(20, 4),
        details JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (source_id, account_key, observed_at)
    )
    """,
    """
    CREATE TABLE raw.broker_position_snapshot (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_snapshot_id BIGINT NOT NULL REFERENCES raw.broker_account_snapshot(id) ON DELETE CASCADE,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        quantity NUMERIC(24, 8) NOT NULL,
        average_cost NUMERIC(20, 6),
        market_price NUMERIC(20, 6),
        market_value NUMERIC(24, 4),
        unrealized_pnl NUMERIC(24, 4),
        details JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (account_snapshot_id, instrument_id)
    )
    """,
    """
    CREATE TABLE raw.broker_activity (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_id TEXT NOT NULL REFERENCES ingest.source(id),
        ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
        account_key TEXT NOT NULL,
        activity_key TEXT NOT NULL,
        activity_type TEXT NOT NULL CHECK (activity_type IN ('order', 'fill')),
        instrument_id BIGINT REFERENCES catalog.instrument(id),
        occurred_at TIMESTAMPTZ NOT NULL,
        side TEXT,
        quantity NUMERIC(24, 8),
        price NUMERIC(20, 6),
        status TEXT,
        details JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (source_id, activity_key, activity_type)
    )
    """,
    """
    CREATE TABLE analysis.strategy_revision (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        strategy_key TEXT NOT NULL,
        revision INTEGER NOT NULL,
        name TEXT NOT NULL,
        status TEXT NOT NULL,
        parameters JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        promoted_at TIMESTAMPTZ,
        supersedes_id BIGINT REFERENCES analysis.strategy_revision(id),
        UNIQUE (strategy_key, revision)
    )
    """,
    """
    CREATE TABLE analysis.run (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        run_type TEXT NOT NULL,
        input_cutoff TIMESTAMPTZ NOT NULL,
        code_version TEXT NOT NULL,
        feature_versions JSONB NOT NULL DEFAULT '{}'::jsonb,
        strategy_revision_id BIGINT REFERENCES analysis.strategy_revision(id),
        input_hash CHAR(64) NOT NULL,
        started_at TIMESTAMPTZ NOT NULL,
        finished_at TIMESTAMPTZ,
        status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'partial', 'failed')),
        summary JSONB NOT NULL DEFAULT '{}'::jsonb
    )
    """,
    """
    CREATE TABLE analysis.source_signal (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id UUID NOT NULL REFERENCES analysis.run(id) ON DELETE CASCADE,
        content_item_id BIGINT NOT NULL REFERENCES raw.content_item(id),
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        observed_at TIMESTAMPTZ NOT NULL,
        signal_type TEXT NOT NULL,
        sentiment TEXT,
        direction TEXT,
        confidence DOUBLE PRECISION,
        thesis TEXT,
        antithesis TEXT,
        invalidation TEXT,
        details JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (run_id, content_item_id, instrument_id, signal_type)
    )
    """,
    """
    CREATE TABLE analysis.symbol_feature (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id UUID NOT NULL REFERENCES analysis.run(id) ON DELETE CASCADE,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        as_of TIMESTAMPTZ NOT NULL,
        feature_set TEXT NOT NULL,
        feature_version TEXT NOT NULL,
        price DOUBLE PRECISION,
        ma_50 DOUBLE PRECISION,
        ma_200 DOUBLE PRECISION,
        relative_strength_20d DOUBLE PRECISION,
        atr_pct DOUBLE PRECISION,
        liquidity_score DOUBLE PRECISION,
        valuation_score DOUBLE PRECISION,
        earnings_score DOUBLE PRECISION,
        metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (run_id, instrument_id, feature_set, feature_version)
    )
    """,
    """
    CREATE TABLE analysis.option_feature (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id UUID NOT NULL REFERENCES analysis.run(id) ON DELETE CASCADE,
        snapshot_id BIGINT NOT NULL REFERENCES raw.option_snapshot(id),
        contract_id BIGINT NOT NULL REFERENCES catalog.option_contract(id),
        quote_observed_at TIMESTAMPTZ NOT NULL,
        feature_version TEXT NOT NULL,
        modeled_iv DOUBLE PRECISION,
        modeled_delta DOUBLE PRECISION,
        modeled_gamma DOUBLE PRECISION,
        modeled_theta DOUBLE PRECISION,
        modeled_vega DOUBLE PRECISION,
        dte INTEGER,
        spread_pct DOUBLE PRECISION,
        iv_rank DOUBLE PRECISION,
        iv_percentile DOUBLE PRECISION,
        liquidity_score DOUBLE PRECISION,
        flow_score DOUBLE PRECISION,
        convexity_score DOUBLE PRECISION,
        required_2x_price DOUBLE PRECISION,
        required_5x_price DOUBLE PRECISION,
        required_10x_price DOUBLE PRECISION,
        required_move_pct DOUBLE PRECISION,
        ev_inputs JSONB NOT NULL DEFAULT '{}'::jsonb,
        metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
        FOREIGN KEY (snapshot_id, contract_id, quote_observed_at)
            REFERENCES raw.option_quote (snapshot_id, contract_id, observed_at),
        UNIQUE (run_id, snapshot_id, contract_id, feature_version)
    )
    """,
    """
    CREATE TABLE analysis.decision (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        run_id UUID NOT NULL REFERENCES analysis.run(id) ON DELETE CASCADE,
        decision_key TEXT NOT NULL,
        kind TEXT NOT NULL,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        as_of TIMESTAMPTZ NOT NULL,
        state TEXT NOT NULL,
        rank INTEGER,
        score DOUBLE PRECISION,
        quality_status TEXT,
        strategy_revision_id BIGINT REFERENCES analysis.strategy_revision(id),
        reasons TEXT[] NOT NULL DEFAULT '{}',
        blockers TEXT[] NOT NULL DEFAULT '{}',
        input_hash CHAR(64) NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (run_id, decision_key)
    )
    """,
    """
    CREATE TABLE analysis.symbol_decision (
        decision_id UUID PRIMARY KEY REFERENCES analysis.decision(id) ON DELETE CASCADE,
        action TEXT,
        discovery_reasons TEXT[] NOT NULL DEFAULT '{}',
        freshness_status TEXT,
        portfolio_context JSONB NOT NULL DEFAULT '{}'::jsonb,
        details JSONB NOT NULL DEFAULT '{}'::jsonb
    )
    """,
    """
    CREATE TABLE analysis.option_decision (
        decision_id UUID PRIMARY KEY REFERENCES analysis.decision(id) ON DELETE CASCADE,
        contract_id BIGINT NOT NULL REFERENCES catalog.option_contract(id),
        snapshot_id BIGINT NOT NULL REFERENCES raw.option_snapshot(id),
        quote_observed_at TIMESTAMPTZ NOT NULL,
        primary_decision_id UUID REFERENCES analysis.decision(id),
        premium_mid DOUBLE PRECISION,
        fill_assumption DOUBLE PRECISION,
        required_move_pct DOUBLE PRECISION,
        buy_under DOUBLE PRECISION,
        predicted_p2x DOUBLE PRECISION,
        predicted_p5x DOUBLE PRECISION,
        ev_multiple DOUBLE PRECISION,
        tier TEXT,
        synthetic_legs JSONB NOT NULL DEFAULT '[]'::jsonb,
        FOREIGN KEY (snapshot_id, contract_id, quote_observed_at)
            REFERENCES raw.option_quote (snapshot_id, contract_id, observed_at)
    )
    """,
    """
    CREATE TABLE analysis.decision_evidence (
        decision_id UUID NOT NULL REFERENCES analysis.decision(id) ON DELETE CASCADE,
        evidence_kind TEXT NOT NULL,
        reference_key TEXT NOT NULL,
        reference_url TEXT,
        detail JSONB NOT NULL DEFAULT '{}'::jsonb,
        PRIMARY KEY (decision_id, evidence_kind, reference_key)
    )
    """,
    """
    CREATE TABLE analysis.reject_summary (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id UUID NOT NULL REFERENCES analysis.run(id) ON DELETE CASCADE,
        strategy_revision_id BIGINT REFERENCES analysis.strategy_revision(id),
        instrument_id BIGINT REFERENCES catalog.instrument(id),
        gate_code TEXT NOT NULL,
        reject_count INTEGER NOT NULL CHECK (reject_count >= 0),
        sampled_decision_keys TEXT[] NOT NULL DEFAULT '{}',
        UNIQUE (run_id, strategy_revision_id, instrument_id, gate_code)
    )
    """,
    """
    CREATE TABLE analysis.option_outcome (
        decision_id UUID PRIMARY KEY REFERENCES analysis.decision(id) ON DELETE CASCADE,
        maturity_state TEXT NOT NULL,
        observed_through TIMESTAMPTZ,
        current_return DOUBLE PRECISION,
        return_1d DOUBLE PRECISION,
        return_5d DOUBLE PRECISION,
        return_20d DOUBLE PRECISION,
        return_60d DOUBLE PRECISION,
        peak_return DOUBLE PRECISION,
        max_drawdown DOUBLE PRECISION,
        time_to_2x_days INTEGER,
        time_to_5x_days INTEGER,
        time_to_10x_days INTEGER,
        realized_exit_return DOUBLE PRECISION,
        realized_exit_basis TEXT,
        stock_move_effect DOUBLE PRECISION,
        iv_effect DOUBLE PRECISION,
        theta_effect DOUBLE PRECISION,
        spread_effect DOUBLE PRECISION,
        unexplained_effect DOUBLE PRECISION,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE analysis.shadow_trade (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        decision_id UUID NOT NULL REFERENCES analysis.decision(id),
        entry_at TIMESTAMPTZ NOT NULL,
        entry_price NUMERIC(20, 6) NOT NULL,
        exit_at TIMESTAMPTZ,
        exit_price NUMERIC(20, 6),
        status TEXT NOT NULL,
        path JSONB NOT NULL DEFAULT '[]'::jsonb,
        metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
        UNIQUE (decision_id)
    )
    """,
    """
    CREATE TABLE analysis.strategy_evaluation (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        strategy_revision_id BIGINT NOT NULL REFERENCES analysis.strategy_revision(id),
        evaluation_type TEXT NOT NULL,
        evaluated_at TIMESTAMPTZ NOT NULL,
        period_start TIMESTAMPTZ,
        period_end TIMESTAMPTZ,
        verdict TEXT,
        metrics JSONB NOT NULL,
        evidence JSONB NOT NULL DEFAULT '[]'::jsonb
    )
    """,
    """
    CREATE TABLE analysis.agent_run (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        provider TEXT NOT NULL,
        model TEXT NOT NULL,
        trigger TEXT NOT NULL,
        started_at TIMESTAMPTZ NOT NULL,
        finished_at TIMESTAMPTZ,
        input_tokens BIGINT,
        output_tokens BIGINT,
        cost_usd NUMERIC(14, 6),
        status TEXT NOT NULL,
        summary JSONB NOT NULL DEFAULT '{}'::jsonb
    )
    """,
    """
    CREATE TABLE analysis.agent_task (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        agent_run_id UUID REFERENCES analysis.agent_run(id) ON DELETE CASCADE,
        decision_id UUID REFERENCES analysis.decision(id),
        task_kind TEXT NOT NULL,
        status TEXT NOT NULL,
        request JSONB NOT NULL,
        result JSONB,
        validation JSONB,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE app.watchlist_item (
        instrument_id BIGINT PRIMARY KEY REFERENCES catalog.instrument(id),
        watch_state TEXT NOT NULL,
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE app.portfolio_position (
        instrument_id BIGINT PRIMARY KEY REFERENCES catalog.instrument(id),
        quantity NUMERIC(24, 8) NOT NULL,
        average_cost NUMERIC(20, 6),
        purchase_date DATE,
        notes TEXT,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE app.thesis (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        revision INTEGER NOT NULL,
        status TEXT NOT NULL,
        thesis JSONB NOT NULL,
        source_agent_task_id UUID REFERENCES analysis.agent_task(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (instrument_id, revision)
    )
    """,
    """
    CREATE TABLE app.catalyst (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT REFERENCES catalog.instrument(id),
        market_event_id BIGINT REFERENCES raw.market_event(id),
        starts_at TIMESTAMPTZ NOT NULL,
        title TEXT NOT NULL,
        expected_impact TEXT,
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (market_event_id)
    )
    """,
    """
    CREATE TABLE app.trade_journal (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        decision_id UUID REFERENCES analysis.decision(id),
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        action TEXT NOT NULL,
        quantity NUMERIC(24, 8),
        price NUMERIC(20, 6),
        rationale TEXT,
        details JSONB NOT NULL DEFAULT '{}'::jsonb
    )
    """,
    """
    CREATE TABLE app.research_report (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        report_type TEXT NOT NULL,
        markdown TEXT,
        report JSONB NOT NULL,
        evidence JSONB NOT NULL DEFAULT '[]'::jsonb
    )
    """,
    """
    CREATE TABLE app.paper_order (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        decision_id UUID REFERENCES analysis.decision(id),
        instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        side TEXT NOT NULL,
        quantity NUMERIC(24, 8) NOT NULL,
        limit_price NUMERIC(20, 6),
        status TEXT NOT NULL,
        policy_result JSONB NOT NULL DEFAULT '{}'::jsonb
    )
    """,
    """
    CREATE TABLE app.alert (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        decision_id UUID REFERENCES analysis.decision(id),
        instrument_id BIGINT REFERENCES catalog.instrument(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        alert_type TEXT NOT NULL,
        severity TEXT NOT NULL,
        title TEXT NOT NULL,
        detail TEXT,
        acknowledged_at TIMESTAMPTZ,
        resolution_reason TEXT
    )
    """,
    """
    CREATE TABLE app.publication (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        scope TEXT NOT NULL,
        analysis_run_id UUID NOT NULL REFERENCES analysis.run(id),
        status TEXT NOT NULL CHECK (status IN ('building', 'published', 'failed', 'superseded')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        published_at TIMESTAMPTZ,
        validation JSONB NOT NULL DEFAULT '{}'::jsonb
    )
    """,
    """
    CREATE TABLE app.publication_item (
        publication_id UUID NOT NULL REFERENCES app.publication(id) ON DELETE CASCADE,
        model_name TEXT NOT NULL,
        stable_key TEXT NOT NULL,
        rank INTEGER NOT NULL,
        instrument_id BIGINT REFERENCES catalog.instrument(id),
        payload JSONB NOT NULL,
        PRIMARY KEY (publication_id, model_name, stable_key)
    )
    """,
    """
    CREATE TABLE app.setting (
        key TEXT PRIMARY KEY,
        value JSONB NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE ops.job_run (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        job_name TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'partial', 'failed', 'skipped')),
        started_at TIMESTAMPTZ NOT NULL,
        finished_at TIMESTAMPTZ,
        error TEXT,
        summary JSONB NOT NULL DEFAULT '{}'::jsonb
    )
    """,
    "CREATE UNIQUE INDEX uq_ops_job_run_running ON ops.job_run (job_name) WHERE status = 'running'",
    "CREATE INDEX ix_ingest_run_latest ON ingest.run (source_id, finished_at DESC)",
    "CREATE INDEX ix_raw_content_item_observed ON raw.content_item (observed_at DESC)",
    "CREATE INDEX ix_raw_price_bar_lookup ON raw.price_bar (instrument_id, trading_date DESC) INCLUDE (close, volume)",
    "CREATE INDEX ix_raw_quote_lookup ON raw.quote (instrument_id, observed_at DESC) INCLUDE (price, source_id)",
    "CREATE INDEX ix_raw_option_quote_contract ON raw.option_quote (contract_id, observed_at DESC) INCLUDE (mid, provider_iv, underlying_price)",
    "CREATE INDEX ix_analysis_source_signal_instrument ON analysis.source_signal (instrument_id, observed_at DESC)",
    "CREATE INDEX ix_analysis_symbol_feature_lookup ON analysis.symbol_feature (instrument_id, as_of DESC, feature_set)",
    "CREATE INDEX ix_analysis_option_feature_lookup ON analysis.option_feature (snapshot_id, contract_id, feature_version)",
    "CREATE INDEX ix_analysis_decision_run ON analysis.decision (run_id, kind, state, rank)",
    "CREATE INDEX ix_analysis_decision_instrument ON analysis.decision (instrument_id, as_of DESC)",
    "CREATE INDEX ix_analysis_decision_actionable ON analysis.decision (run_id, kind, score DESC) WHERE state <> 'REJECT'",
    "CREATE INDEX ix_analysis_outcome_maturity ON analysis.option_outcome (maturity_state, observed_through)",
    "CREATE INDEX ix_app_publication_latest ON app.publication (scope, published_at DESC) WHERE status = 'published'",
    "CREATE INDEX ix_app_publication_item_rank ON app.publication_item (publication_id, model_name, rank)",
    "CREATE UNIQUE INDEX uq_app_thesis_current ON app.thesis (instrument_id) WHERE status = 'current'",
]


def upgrade() -> None:
    for statement in SCHEMA_DDL:
        op.execute(sa.text(statement))


def downgrade() -> None:
    for schema in ("ops", "app", "analysis", "raw", "ingest", "catalog"):
        op.execute(sa.text(f"DROP SCHEMA IF EXISTS {schema} CASCADE"))
