"""Add append-only QQQ option evidence and decision-system contracts.

Revision ID: 20260720_0011
Revises: 20260718_0010
"""

from __future__ import annotations

from alembic import op


revision = "20260720_0011"
down_revision = "20260718_0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE raw.option_capture_generation (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_id BIGINT NOT NULL REFERENCES raw.option_snapshot(id) ON DELETE RESTRICT,
            ingest_run_id UUID NOT NULL REFERENCES ingest.run(id),
            generation INTEGER NOT NULL,
            capture_state TEXT NOT NULL CHECK (capture_state IN ('running', 'complete', 'partial', 'failed')),
            expected_contract_count INTEGER NOT NULL DEFAULT 0,
            received_contract_count INTEGER NOT NULL DEFAULT 0,
            completeness DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (completeness BETWEEN 0 AND 1),
            capture_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            capture_finished_at TIMESTAMPTZ,
            terminal_error TEXT,
            diagnostics JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (snapshot_id, generation),
            UNIQUE (snapshot_id, ingest_run_id)
        )
        """
    )
    op.execute("ALTER TABLE raw.option_snapshot ADD COLUMN latest_complete_generation_id BIGINT")
    op.execute(
        "ALTER TABLE raw.option_snapshot ADD CONSTRAINT fk_option_snapshot_latest_generation "
        "FOREIGN KEY (latest_complete_generation_id) REFERENCES raw.option_capture_generation(id) ON DELETE RESTRICT"
    )
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN capture_generation_id BIGINT REFERENCES raw.option_capture_generation(id) ON DELETE RESTRICT")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN capture_group_key TEXT")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN group_started_at TIMESTAMPTZ")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN group_finished_at TIMESTAMPTZ")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN provider_observed_at TIMESTAMPTZ")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN available_at TIMESTAMPTZ NOT NULL DEFAULT now()")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN underlying_observed_at TIMESTAMPTZ")
    op.execute("ALTER TABLE raw.option_quote ADD COLUMN underlying_available_at TIMESTAMPTZ")
    op.execute("CREATE UNIQUE INDEX ux_raw_option_quote_generation_contract_observed ON raw.option_quote (capture_generation_id, contract_id, observed_at) WHERE capture_generation_id IS NOT NULL")
    op.execute("CREATE INDEX ix_raw_option_capture_generation_snapshot_state ON raw.option_capture_generation (snapshot_id, capture_state, generation DESC)")
    op.execute("CREATE INDEX ix_raw_option_quote_generation_group ON raw.option_quote (capture_generation_id, capture_group_key, contract_id)")

    # Preserve every existing historical capture as generation one. Radar rows intentionally
    # remain generation-less because the history collector is the append-only authority.
    op.execute(
        """
        INSERT INTO raw.option_capture_generation
            (snapshot_id, ingest_run_id, generation, capture_state, expected_contract_count,
             received_contract_count, completeness, capture_started_at, capture_finished_at, diagnostics)
        SELECT id, ingest_run_id, 1,
               CASE WHEN capture_state = 'running' THEN 'failed' ELSE capture_state END,
               coalesce(expected_contract_count, contract_count, 0),
               coalesce(received_contract_count, contract_count, 0),
               coalesce(completeness, CASE WHEN contract_count > 0 THEN 1.0 ELSE 0.0 END),
               coalesce(capture_started_at, observed_at),
               coalesce(capture_finished_at, observed_at),
               jsonb_build_object('migrated_from_snapshot', true)
        FROM raw.option_snapshot
        WHERE collection_profile = 'history_full'
        """
    )
    op.execute(
        """
        UPDATE raw.option_quote quote
        SET capture_generation_id = generation.id,
            available_at = coalesce(quote.captured_at, quote.observed_at),
            provider_observed_at = coalesce(quote.provider_updated_at, quote.observed_at),
            underlying_observed_at = coalesce(quote.provider_updated_at, quote.observed_at),
            underlying_available_at = coalesce(quote.captured_at, quote.observed_at),
            capture_group_key = contract.expiration::text || ':' || contract.option_type,
            group_started_at = coalesce(snapshot.capture_started_at, quote.observed_at),
            group_finished_at = coalesce(snapshot.capture_finished_at, quote.observed_at)
        FROM raw.option_capture_generation generation,
             raw.option_snapshot snapshot,
             catalog.option_contract contract
        WHERE snapshot.id = generation.snapshot_id
          AND contract.id = quote.contract_id
          AND quote.snapshot_id = generation.snapshot_id
          AND generation.generation = 1
          AND snapshot.collection_profile = 'history_full'
        """
    )
    op.execute(
        """
        UPDATE raw.option_snapshot snapshot
        SET latest_complete_generation_id = generation.id
        FROM raw.option_capture_generation generation
        WHERE generation.snapshot_id = snapshot.id AND generation.capture_state = 'complete'
        """
    )

    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN analysis_run_id UUID REFERENCES analysis.run(id)")
    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN capture_generation_id BIGINT REFERENCES raw.option_capture_generation(id)")
    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN fit_method TEXT")
    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN fit_status TEXT")
    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN eligible_point_count INTEGER")
    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN group_duration_seconds DOUBLE PRECISION")
    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN max_quote_age_seconds DOUBLE PRECISION")
    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN fit_rmse DOUBLE PRECISION")
    op.execute("ALTER TABLE analysis.option_surface_summary ADD COLUMN candidate_count INTEGER NOT NULL DEFAULT 0")
    op.execute(
        """
        DO $$ DECLARE constraint_name text;
        BEGIN
          SELECT conname INTO constraint_name
          FROM pg_constraint
          WHERE conrelid = 'analysis.option_surface_summary'::regclass
            AND contype = 'u'
            AND pg_get_constraintdef(oid) LIKE '%snapshot_id, expiration, option_type, feature_version%';
          IF constraint_name IS NOT NULL THEN
            EXECUTE format('ALTER TABLE analysis.option_surface_summary DROP CONSTRAINT %I', constraint_name);
          END IF;
        END $$;
        """
    )
    op.execute("CREATE UNIQUE INDEX ux_option_surface_summary_legacy_group ON analysis.option_surface_summary (snapshot_id, expiration, option_type, feature_version) WHERE analysis_run_id IS NULL")
    op.execute("CREATE UNIQUE INDEX ux_option_surface_summary_v3_run_group ON analysis.option_surface_summary (analysis_run_id, expiration, option_type) WHERE analysis_run_id IS NOT NULL")
    op.execute("ALTER TABLE analysis.option_history_anomaly ADD COLUMN feature_version TEXT NOT NULL DEFAULT 'history-v2'")
    op.execute("UPDATE analysis.option_history_anomaly SET feature_version = 'history-v2' WHERE feature_version IS NULL")
    op.execute(
        """
        CREATE TABLE analysis.option_relative_value (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            analysis_run_id UUID NOT NULL REFERENCES analysis.run(id) ON DELETE RESTRICT,
            capture_generation_id BIGINT NOT NULL REFERENCES raw.option_capture_generation(id) ON DELETE RESTRICT,
            contract_id BIGINT NOT NULL REFERENCES catalog.option_contract(id),
            model_revision TEXT NOT NULL,
            classification TEXT NOT NULL CHECK (classification IN ('relative_cheap', 'relative_rich', 'historical_static_arbitrage_candidate', 'verified_static_arbitrage_candidate', 'rejected')),
            fair_low DOUBLE PRECISION,
            fair_high DOUBLE PRECISION,
            modeled_net_edge DOUBLE PRECISION,
            edge_side TEXT,
            confidence DOUBLE PRECISION,
            quality_status TEXT NOT NULL,
            blockers TEXT[] NOT NULL DEFAULT '{}',
            evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (analysis_run_id, capture_generation_id, contract_id, model_revision)
        )
        """
    )
    op.execute("CREATE INDEX ix_option_relative_value_run_classification_edge ON analysis.option_relative_value (analysis_run_id, classification, modeled_net_edge DESC)")

    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN paper_state TEXT")
    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN discovery_lane TEXT")
    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN thesis_id BIGINT REFERENCES app.thesis(id)")
    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN relative_value_id BIGINT REFERENCES analysis.option_relative_value(id)")
    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN model_version TEXT")
    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN market_regime TEXT")
    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN fair_low DOUBLE PRECISION")
    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN fair_high DOUBLE PRECISION")
    op.execute("ALTER TABLE analysis.option_decision ADD COLUMN modeled_net_edge DOUBLE PRECISION")
    op.execute("ALTER TABLE analysis.option_decision ADD CONSTRAINT ck_option_decision_paper_state CHECK (paper_state IS NULL OR paper_state IN ('COLLECTING', 'WATCH', 'PAPER_READY', 'REJECT'))")

    op.execute("ALTER TABLE analysis.shadow_trade ALTER COLUMN entry_at DROP NOT NULL")
    op.execute("ALTER TABLE analysis.shadow_trade ALTER COLUMN entry_price DROP NOT NULL")
    op.execute("ALTER TABLE analysis.shadow_trade ADD COLUMN pending_entry_reason TEXT")
    op.execute("ALTER TABLE analysis.shadow_trade ADD COLUMN entry_cohort_id BIGINT REFERENCES raw.option_capture_generation(id)")
    op.execute("ALTER TABLE analysis.shadow_trade ADD COLUMN structure TEXT")
    op.execute("ALTER TABLE analysis.shadow_trade ADD COLUMN market_regime TEXT")
    op.execute("ALTER TABLE analysis.shadow_trade ADD COLUMN fill_basis TEXT")
    op.execute("ALTER TABLE analysis.shadow_trade ADD COLUMN source_kind TEXT NOT NULL DEFAULT 'system'")
    op.execute("ALTER TABLE analysis.shadow_trade ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now()")


def downgrade() -> None:
    op.execute("ALTER TABLE analysis.shadow_trade DROP COLUMN created_at")
    op.execute("ALTER TABLE analysis.shadow_trade DROP COLUMN source_kind")
    op.execute("ALTER TABLE analysis.shadow_trade DROP COLUMN fill_basis")
    op.execute("ALTER TABLE analysis.shadow_trade DROP COLUMN market_regime")
    op.execute("ALTER TABLE analysis.shadow_trade DROP COLUMN structure")
    op.execute("ALTER TABLE analysis.shadow_trade DROP COLUMN entry_cohort_id")
    op.execute("ALTER TABLE analysis.shadow_trade DROP COLUMN pending_entry_reason")
    op.execute("ALTER TABLE analysis.shadow_trade ALTER COLUMN entry_price SET NOT NULL")
    op.execute("ALTER TABLE analysis.shadow_trade ALTER COLUMN entry_at SET NOT NULL")
    op.execute("ALTER TABLE analysis.option_decision DROP CONSTRAINT ck_option_decision_paper_state")
    for column in ('modeled_net_edge', 'fair_high', 'fair_low', 'market_regime', 'model_version', 'relative_value_id', 'thesis_id', 'discovery_lane', 'paper_state'):
        op.execute(f"ALTER TABLE analysis.option_decision DROP COLUMN {column}")
    op.execute("DROP INDEX analysis.ix_option_relative_value_run_classification_edge")
    op.execute("DROP TABLE analysis.option_relative_value")
    op.execute("ALTER TABLE analysis.option_history_anomaly DROP COLUMN feature_version")
    op.execute("DROP INDEX analysis.ux_option_surface_summary_v3_run_group")
    op.execute("DROP INDEX analysis.ux_option_surface_summary_legacy_group")
    for column in ('candidate_count', 'fit_rmse', 'max_quote_age_seconds', 'group_duration_seconds', 'eligible_point_count', 'fit_status', 'fit_method', 'capture_generation_id', 'analysis_run_id'):
        op.execute(f"ALTER TABLE analysis.option_surface_summary DROP COLUMN {column}")
    op.execute("DROP INDEX raw.ix_raw_option_quote_generation_group")
    op.execute("DROP INDEX raw.ix_raw_option_capture_generation_snapshot_state")
    op.execute("DROP INDEX raw.ux_raw_option_quote_generation_contract_observed")
    for column in ('underlying_available_at', 'underlying_observed_at', 'available_at', 'provider_observed_at', 'group_finished_at', 'group_started_at', 'capture_group_key', 'capture_generation_id'):
        op.execute(f"ALTER TABLE raw.option_quote DROP COLUMN {column}")
    op.execute("ALTER TABLE raw.option_snapshot DROP CONSTRAINT fk_option_snapshot_latest_generation")
    op.execute("ALTER TABLE raw.option_snapshot DROP COLUMN latest_complete_generation_id")
    op.execute("DROP TABLE raw.option_capture_generation")
