"""Professional thesis monitor v3 schema.

Revision ID: 20260725_0017
Revises: 20260724_0016
"""

from alembic import op


revision = "20260725_0017"
down_revision = "20260724_0016"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app.thesis_automation_run (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            instrument_id BIGINT REFERENCES catalog.instrument(id),
            run_kind TEXT NOT NULL DEFAULT 'assessment',
            trigger TEXT NOT NULL DEFAULT 'manual',
            model TEXT,
            reasoning_effort TEXT,
            prompt_version TEXT NOT NULL DEFAULT 'thesis_v3_20260725',
            evidence_fingerprint TEXT,
            evidence_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
            input_symbol TEXT,
            input_tokens INTEGER,
            output_tokens INTEGER,
            cost_usd NUMERIC(12, 6),
            status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'timeout', 'skipped')),
            error TEXT,
            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            finished_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        """
        ALTER TABLE app.thesis
            ADD COLUMN IF NOT EXISTS schema_version INTEGER NOT NULL DEFAULT 3,
            ADD COLUMN IF NOT EXISTS author_kind TEXT NOT NULL DEFAULT 'legacy',
            ADD COLUMN IF NOT EXISTS automation_run_id UUID REFERENCES app.thesis_automation_run(id),
            ADD COLUMN IF NOT EXISTS superseded_revision_id BIGINT REFERENCES app.thesis(id),
            ADD COLUMN IF NOT EXISTS change_rationale TEXT,
            ADD COLUMN IF NOT EXISTS last_assessed_at TIMESTAMPTZ,
            ADD COLUMN IF NOT EXISTS last_human_reviewed_at TIMESTAMPTZ
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app.thesis_review_event (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
            thesis_revision_id BIGINT REFERENCES app.thesis(id),
            outcome TEXT NOT NULL CHECK (outcome IN ('unchanged', 'updated', 'invalidated', 'closed', 'legacy_acknowledgement')),
            notes TEXT,
            reviewed_evidence_cutoff TIMESTAMPTZ,
            reviewed_by TEXT NOT NULL DEFAULT 'joe',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app.thesis_evidence_assessment (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            thesis_revision_id BIGINT REFERENCES app.thesis(id) ON DELETE CASCADE,
            automation_run_id UUID REFERENCES app.thesis_automation_run(id),
            instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
            evidence_reference TEXT NOT NULL,
            evidence_title TEXT,
            evidence_date TIMESTAMPTZ,
            stance TEXT NOT NULL CHECK (stance IN ('support', 'contradict', 'neutral', 'insufficient')),
            materiality TEXT NOT NULL DEFAULT 'low' CHECK (materiality IN ('low', 'medium', 'high')),
            affected_pillar_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
            confidence NUMERIC(5, 4) NOT NULL DEFAULT 0 CHECK (confidence >= 0 AND confidence <= 1),
            rationale TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app.thesis_expression (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id),
            thesis_revision_id BIGINT NOT NULL REFERENCES app.thesis(id) ON DELETE CASCADE,
            expression_kind TEXT NOT NULL CHECK (expression_kind IN ('equity', 'option')),
            structure JSONB NOT NULL DEFAULT '{}'::jsonb,
            entry_logic JSONB NOT NULL DEFAULT '{}'::jsonb,
            max_loss NUMERIC(20, 6),
            risk_budget NUMERIC(20, 6),
            horizon_date DATE,
            invalidation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        """
        UPDATE app.thesis
        SET schema_version = 3,
            thesis = jsonb_strip_nulls(
                jsonb_build_object(
                    'schema_version', 3,
                    'core_thesis', COALESCE(NULLIF(thesis->>'core_thesis', ''), NULLIF(thesis->>'thesis', '')),
                    'why_owned_watched', COALESCE(NULLIF(thesis->>'why_owned_watched', ''), NULLIF(thesis->>'why_owned', ''), NULLIF(thesis->>'why', '')),
                    'direction', NULLIF(thesis->>'direction', ''),
                    'timeframe', NULLIF(thesis->>'timeframe', ''),
                    'horizon_date', NULLIF(thesis->>'horizon_date', ''),
                    'conviction', COALESCE(NULLIF(thesis->>'conviction', ''), 'unknown'),
                    'confidence', COALESCE(NULLIF(thesis->>'confidence', ''), 'low'),
                    'pillars', CASE WHEN jsonb_typeof(thesis->'pillars') = 'array' THEN thesis->'pillars' ELSE '[]'::jsonb END,
                    'scenarios', jsonb_build_object('base', thesis->'base_case', 'bull', thesis->'bull_case', 'bear', thesis->'bear_case'),
                    'catalysts', CASE
                        WHEN jsonb_typeof(thesis->'catalysts') = 'array' THEN thesis->'catalysts'
                        WHEN thesis ? 'catalyst' THEN jsonb_build_array(thesis->'catalyst')
                        ELSE '[]'::jsonb
                    END,
                    'invalidation_rules', CASE
                        WHEN jsonb_typeof(thesis->'invalidation_rules') = 'array' THEN thesis->'invalidation_rules'
                        WHEN thesis ? 'invalidation' THEN jsonb_build_array(
                            jsonb_strip_nulls(jsonb_build_object(
                                'type', 'price',
                                'operator', '<=',
                                'text', thesis->>'invalidation',
                                'price', thesis->'invalidation_price'
                            ))
                        )
                        ELSE '[]'::jsonb
                    END,
                    'review_cadence_days', COALESCE(NULLIF(thesis->>'review_cadence_days', '')::int, 45),
                    'next_review_date', NULLIF(thesis->>'next_review_date', ''),
                    'lifecycle_status', COALESCE(NULLIF(thesis->>'status', ''), NULLIF(thesis->>'position_status', ''), 'active'),
                    'evidence_coverage_status', COALESCE(NULLIF(thesis->>'evidence_coverage_status', ''), 'unknown'),
                    'automation_policy', COALESCE(NULLIF(thesis->>'automation_policy', ''), 'auto'),
                    'provenance', COALESCE(thesis->'provenance', '{}'::jsonb),
                    'evidence_links', COALESCE(thesis->'evidence_links', '[]'::jsonb),
                    'last_reviewed', thesis->>'last_reviewed',
                    'legacy', thesis
                )
            ),
            last_human_reviewed_at = CASE
                WHEN thesis ? 'last_reviewed' AND NULLIF(thesis->>'last_reviewed', '') IS NOT NULL
                    THEN NULLIF(thesis->>'last_reviewed', '')::timestamptz
                ELSE last_human_reviewed_at
            END
        WHERE schema_version <> 3 OR NOT (thesis ? 'schema_version')
        """
    )
    op.execute(
        """
        INSERT INTO app.thesis_review_event (
            instrument_id, thesis_revision_id, outcome, notes, reviewed_evidence_cutoff, reviewed_by, created_at
        )
        SELECT thesis.instrument_id, thesis.id, 'legacy_acknowledgement',
               'Converted from a legacy blank reviewed record.',
               thesis.last_human_reviewed_at, 'legacy', thesis.last_human_reviewed_at
        FROM app.thesis thesis
        WHERE thesis.last_human_reviewed_at IS NOT NULL
          AND COALESCE(NULLIF(thesis.thesis->>'core_thesis', ''), '') = ''
          AND NOT EXISTS (
              SELECT 1 FROM app.thesis_review_event event
              WHERE event.thesis_revision_id = thesis.id
                AND event.outcome = 'legacy_acknowledgement'
          )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_thesis_instrument_revision ON app.thesis (instrument_id, revision DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_thesis_review_event_symbol ON app.thesis_review_event (instrument_id, created_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_thesis_assessment_revision ON app.thesis_evidence_assessment (thesis_revision_id, stance, materiality)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_thesis_automation_run_symbol ON app.thesis_automation_run (instrument_id, started_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_thesis_expression_revision ON app.thesis_expression (thesis_revision_id, expression_kind)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS app.ix_app_thesis_expression_revision")
    op.execute("DROP INDEX IF EXISTS app.ix_app_thesis_automation_run_symbol")
    op.execute("DROP INDEX IF EXISTS app.ix_app_thesis_assessment_revision")
    op.execute("DROP INDEX IF EXISTS app.ix_app_thesis_review_event_symbol")
    op.execute("DROP INDEX IF EXISTS app.ix_app_thesis_instrument_revision")
    op.execute("DROP TABLE IF EXISTS app.thesis_expression")
    op.execute("DROP TABLE IF EXISTS app.thesis_evidence_assessment")
    op.execute("DROP TABLE IF EXISTS app.thesis_review_event")
    op.execute("ALTER TABLE app.thesis DROP COLUMN IF EXISTS last_human_reviewed_at")
    op.execute("ALTER TABLE app.thesis DROP COLUMN IF EXISTS last_assessed_at")
    op.execute("ALTER TABLE app.thesis DROP COLUMN IF EXISTS change_rationale")
    op.execute("ALTER TABLE app.thesis DROP COLUMN IF EXISTS superseded_revision_id")
    op.execute("ALTER TABLE app.thesis DROP COLUMN IF EXISTS automation_run_id")
    op.execute("ALTER TABLE app.thesis DROP COLUMN IF EXISTS author_kind")
    op.execute("ALTER TABLE app.thesis DROP COLUMN IF EXISTS schema_version")
    op.execute("DROP TABLE IF EXISTS app.thesis_automation_run")
