"""Add forward-only sell-off event evidence tape and event-strip policies.

Revision ID: 20260803_0021
Revises: 20260803_0020
"""

from __future__ import annotations

from alembic import op


revision = "20260803_0021"
down_revision = "20260803_0020"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE raw.option_snapshot DROP CONSTRAINT IF EXISTS ck_option_snapshot_profile")
    op.execute(
        """
        ALTER TABLE raw.option_snapshot
          ADD CONSTRAINT ck_option_snapshot_profile
          CHECK (collection_profile IN ('radar', 'history_full', 'event_strip'))
        """
    )
    op.execute(
        """
        CREATE TABLE analysis.option_event (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            instrument_id BIGINT NOT NULL REFERENCES catalog.instrument(id) ON DELETE RESTRICT,
            objective_version TEXT NOT NULL DEFAULT 'short_horizon_convex_v1',
            event_type TEXT NOT NULL DEFAULT 'selloff',
            status TEXT NOT NULL DEFAULT 'active',
            detected_at TIMESTAMPTZ NOT NULL,
            started_at TIMESTAMPTZ NOT NULL,
            reference_price DOUBLE PRECISION NOT NULL,
            event_low DOUBLE PRECISION NOT NULL,
            trigger_intraday_pct DOUBLE PRECISION,
            trigger_one_day_pct DOUBLE PRECISION,
            trigger_three_session_pct DOUBLE PRECISION,
            severity_score DOUBLE PRECISION NOT NULL,
            event_rank INTEGER,
            material_evidence_count INTEGER NOT NULL DEFAULT 0,
            enrolled_at TIMESTAMPTZ,
            last_signal_at TIMESTAMPTZ,
            no_active_signal_sessions INTEGER NOT NULL DEFAULT 0,
            closed_at TIMESTAMPTZ,
            close_reason TEXT,
            provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_option_event_type CHECK (event_type = 'selloff'),
            CONSTRAINT ck_option_event_status CHECK (status IN ('active', 'deferred_capacity', 'closed')),
            CONSTRAINT ck_option_event_low CHECK (event_low > 0 AND reference_price > 0)
        );
        CREATE UNIQUE INDEX uq_option_event_open_symbol
        ON analysis.option_event (instrument_id)
        WHERE status IN ('active', 'deferred_capacity');
        CREATE INDEX ix_option_event_status_detected
        ON analysis.option_event (status, detected_at DESC);

        CREATE TABLE analysis.option_event_spot (
            event_id UUID NOT NULL REFERENCES analysis.option_event(id) ON DELETE CASCADE,
            observed_at TIMESTAMPTZ NOT NULL,
            available_at TIMESTAMPTZ NOT NULL,
            price DOUBLE PRECISION NOT NULL,
            source_id TEXT,
            one_day_pct DOUBLE PRECISION,
            three_session_pct DOUBLE PRECISION,
            PRIMARY KEY (event_id, observed_at)
        );
        CREATE INDEX ix_option_event_spot_event_available
        ON analysis.option_event_spot (event_id, available_at DESC);

        CREATE TABLE analysis.option_event_contract (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_id UUID NOT NULL REFERENCES analysis.option_event(id) ON DELETE CASCADE,
            contract_id BIGINT REFERENCES catalog.option_contract(id) ON DELETE RESTRICT,
            contract_key TEXT NOT NULL,
            option_type TEXT NOT NULL,
            expiration DATE NOT NULL,
            target_delta DOUBLE PRECISION NOT NULL,
            is_initial BOOLEAN NOT NULL DEFAULT false,
            replaces_contract_id BIGINT REFERENCES analysis.option_event_contract(id) ON DELETE RESTRICT,
            initial_capture_generation_id BIGINT REFERENCES raw.option_capture_generation(id) ON DELETE SET NULL,
            added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            retired_at TIMESTAMPTZ,
            reason TEXT,
            UNIQUE (event_id, contract_key),
            CONSTRAINT ck_option_event_contract_type CHECK (option_type IN ('call', 'put'))
        );
        CREATE INDEX ix_option_event_contract_event_initial
        ON analysis.option_event_contract (event_id, is_initial, retired_at);

        CREATE TABLE analysis.option_event_capture (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            event_id UUID NOT NULL REFERENCES analysis.option_event(id) ON DELETE CASCADE,
            snapshot_id BIGINT REFERENCES raw.option_snapshot(id) ON DELETE SET NULL,
            capture_generation_id BIGINT REFERENCES raw.option_capture_generation(id) ON DELETE SET NULL,
            scheduled_at TIMESTAMPTZ NOT NULL,
            started_at TIMESTAMPTZ,
            finished_at TIMESTAMPTZ,
            status TEXT NOT NULL,
            expected_contract_count INTEGER NOT NULL DEFAULT 0,
            received_contract_count INTEGER NOT NULL DEFAULT 0,
            completeness DOUBLE PRECISION,
            continuity_pct DOUBLE PRECISION,
            details JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (event_id, scheduled_at),
            CONSTRAINT ck_option_event_capture_status CHECK (status IN ('complete', 'partial', 'failed', 'deferred'))
        );
        CREATE INDEX ix_option_event_capture_event_slot
        ON analysis.option_event_capture (event_id, scheduled_at DESC);
        """
    )
    op.execute(
        """
        ALTER TABLE app.option_history_policy
          ADD COLUMN IF NOT EXISTS profile TEXT NOT NULL DEFAULT 'history_full',
          ADD COLUMN IF NOT EXISTS activation_reason TEXT,
          ADD COLUMN IF NOT EXISTS event_id UUID,
          ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
        ALTER TABLE app.option_history_policy
          DROP CONSTRAINT IF EXISTS option_history_policy_pkey;
        ALTER TABLE app.option_history_policy
          ADD PRIMARY KEY (instrument_id, profile);
        ALTER TABLE app.option_history_policy
          ADD CONSTRAINT fk_option_history_policy_event
          FOREIGN KEY (event_id) REFERENCES analysis.option_event(id) ON DELETE SET NULL;
        ALTER TABLE app.option_history_policy
          DROP CONSTRAINT IF EXISTS ck_option_history_policy_tier;
        ALTER TABLE app.option_history_policy
          ADD CONSTRAINT ck_option_history_policy_tier
          CHECK (collection_tier IN ('core', 'standard', 'event'));
        ALTER TABLE app.option_history_policy
          DROP CONSTRAINT IF EXISTS ck_option_history_policy_retention;
        ALTER TABLE app.option_history_policy
          ADD CONSTRAINT ck_option_history_policy_retention
          CHECK (
            (profile = 'history_full'
             AND normalized_retention_days = 730
             AND derived_retention_days = 730
             AND provider_payload_retention_days = 90
             AND event_id IS NULL)
            OR
            (profile = 'event_strip'
             AND normalized_retention_days = 365
             AND derived_retention_days = 730
             AND provider_payload_retention_days = 30
             AND event_id IS NOT NULL)
          );
        ALTER TABLE app.option_history_policy
          ADD CONSTRAINT ck_option_history_policy_profile
          CHECK (profile IN ('history_full', 'event_strip'));
        CREATE INDEX ix_option_history_policy_event_active
        ON app.option_history_policy (profile, event_id, effective_state, expires_at);
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM raw.option_snapshot WHERE collection_profile = 'event_strip'")
    op.execute("ALTER TABLE raw.option_snapshot DROP CONSTRAINT IF EXISTS ck_option_snapshot_profile")
    op.execute(
        """
        ALTER TABLE raw.option_snapshot
          ADD CONSTRAINT ck_option_snapshot_profile
          CHECK (collection_profile IN ('radar', 'history_full'))
        """
    )
    op.execute("DROP INDEX IF EXISTS app.ix_option_history_policy_event_active")
    op.execute("DELETE FROM app.option_history_policy WHERE profile = 'event_strip'")
    op.execute("ALTER TABLE app.option_history_policy DROP CONSTRAINT IF EXISTS ck_option_history_policy_profile")
    op.execute("ALTER TABLE app.option_history_policy DROP CONSTRAINT IF EXISTS ck_option_history_policy_retention")
    op.execute("ALTER TABLE app.option_history_policy DROP CONSTRAINT IF EXISTS ck_option_history_policy_tier")
    op.execute("ALTER TABLE app.option_history_policy DROP CONSTRAINT IF EXISTS fk_option_history_policy_event")
    op.execute("ALTER TABLE app.option_history_policy DROP CONSTRAINT IF EXISTS option_history_policy_pkey")
    op.execute("ALTER TABLE app.option_history_policy DROP COLUMN IF EXISTS expires_at")
    op.execute("ALTER TABLE app.option_history_policy DROP COLUMN IF EXISTS event_id")
    op.execute("ALTER TABLE app.option_history_policy DROP COLUMN IF EXISTS activation_reason")
    op.execute("ALTER TABLE app.option_history_policy DROP COLUMN IF EXISTS profile")
    op.execute("ALTER TABLE app.option_history_policy ADD PRIMARY KEY (instrument_id)")
    op.execute(
        """
        ALTER TABLE app.option_history_policy
          ADD CONSTRAINT ck_option_history_policy_tier CHECK (collection_tier IN ('core', 'standard')),
          ADD CONSTRAINT ck_option_history_policy_retention CHECK (
            normalized_retention_days = 730
            AND derived_retention_days = 730
            AND provider_payload_retention_days = 90
          );
        """
    )
    op.execute("DROP INDEX IF EXISTS analysis.ix_option_event_capture_event_slot")
    op.execute("DROP TABLE IF EXISTS analysis.option_event_capture")
    op.execute("DROP INDEX IF EXISTS analysis.ix_option_event_contract_event_initial")
    op.execute("DROP TABLE IF EXISTS analysis.option_event_contract")
    op.execute("DROP INDEX IF EXISTS analysis.ix_option_event_spot_event_available")
    op.execute("DROP TABLE IF EXISTS analysis.option_event_spot")
    op.execute("DROP INDEX IF EXISTS analysis.ix_option_event_status_detected")
    op.execute("DROP INDEX IF EXISTS analysis.uq_option_event_open_symbol")
    op.execute("DROP TABLE IF EXISTS analysis.option_event")
