"""Persist immutable live static-arbitrage verification attempts.

Revision ID: 20260720_0012
Revises: 20260720_0011
"""

from __future__ import annotations

from alembic import op


revision = "20260720_0012"
down_revision = "20260720_0011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analysis.option_relative_value_verification (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            relative_value_id BIGINT NOT NULL REFERENCES analysis.option_relative_value(id) ON DELETE RESTRICT,
            verified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            status TEXT NOT NULL CHECK (status IN ('verified', 'rejected', 'unavailable')),
            blockers TEXT[] NOT NULL DEFAULT '{}',
            evidence JSONB NOT NULL DEFAULT '{}'::jsonb
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_option_relative_value_verification_candidate "
        "ON analysis.option_relative_value_verification (relative_value_id, verified_at DESC)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX analysis.ix_option_relative_value_verification_candidate")
    op.execute("DROP TABLE analysis.option_relative_value_verification")
