"""Static source registry definitions and verified documentation rows."""

from __future__ import annotations

VERIFIED_SOURCES = [
    {
        "source": "sec_edgar",
        "source_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "detail": "Free server-side JSON APIs; use declared user-agent; SEC fair-access max is 10 requests/sec total.",
    },
    {
        "source": "sec_13f",
        "source_url": "https://www.sec.gov/files/form_13f.pdf",
        "detail": "Quarterly official ZIP datasets from May 2013 forward; tab-delimited flat files; as-filed caveats apply.",
    },
    {
        "source": "coingecko",
        "source_url": "https://docs.coingecko.com/reference/coins-markets",
        "detail": "Demo/free REST API uses api.coingecko.com; 30 calls/min and 10k/month; categories update about every 5 minutes.",
    },
    {
        "source": "defillama",
        "source_url": "https://defillama.com/docs/api",
        "detail": "Free unauthenticated API for protocols, TVL, fees/revenue; yields currently use yields.llama.fi.",
    },
    {
        "source": "yfinance",
        "source_url": "https://pypi.org/project/yfinance/",
        "detail": "Unofficial Yahoo Finance wrapper intended for research/education and personal use; cache/fallback required.",
    },
    {
        "source": "stooq",
        "source_url": "https://pydata.github.io/pandas-datareader/readers/stooq.html",
        "detail": "Available through pandas-datareader StooqDailyReader; website-backed, not a contracted API.",
    },
    {
        "source": "opencli",
        "source_url": "https://github.com/jackwener/opencli",
        "detail": "Local CLI adapter registry used read-only for research sources; Market allowlists commands through provider adapters.",
    },
    {
        "source": "tradingview_opencli",
        "source_url": "https://github.com/himself65/finance-skills/tree/main/opencli-plugins/tradingview",
        "detail": "Read-only TradingView desktop adapter for quotes, screeners, news, watchlists, alerts, chart state, and options chains.",
    },
]

MUNGERMODE_BENCHMARK_SOURCES = [
    {"source_name": "Material Events (8-K)", "content_type": "filing"},
    {"source_name": "Earnings Transcripts", "content_type": "transcript"},
    {"source_name": "Quarterly Reports (10-Q)", "content_type": "filing"},
    {"source_name": "Proxy Statements (DEF 14A)", "content_type": "filing"},
    {"source_name": "Odd Lots", "content_type": "podcast"},
    {"source_name": "Annual Reports (10-K)", "content_type": "filing"},
    {"source_name": "Stratechery", "content_type": "blog"},
    {"source_name": "a16z", "content_type": "podcast"},
    {"source_name": "ARK Invest", "content_type": "podcast"},
    {"source_name": "All-In", "content_type": "podcast"},
    {"source_name": "Sequoia Capital", "content_type": "podcast"},
    {"source_name": "Not Boring", "content_type": "blog"},
    {"source_name": "Peter Diamandis", "content_type": "podcast"},
    {"source_name": "In Good Company", "content_type": "podcast"},
    {"source_name": "Invest Like the Best", "content_type": "podcast"},
    {"source_name": "SemiAnalysis", "content_type": "blog"},
    {"source_name": "@balajis", "content_type": "tweet"},
    {"source_name": "No Priors", "content_type": "podcast"},
    {"source_name": "@karpathy", "content_type": "tweet"},
    {"source_name": "Chamath Palihapitiya", "content_type": "blog"},
    {"source_name": "Cheeky Pint", "content_type": "podcast"},
    {"source_name": "Dwarkesh Patel", "content_type": "podcast"},
    {"source_name": "Naval", "content_type": "podcast"},
    {"source_name": "Uncapped", "content_type": "podcast"},
    {"source_name": "@citrini", "content_type": "tweet"},
    {"source_name": "Citrini Research", "content_type": "blog"},
    {"source_name": "Foreign Reports (6-K)", "content_type": "filing"},
    {"source_name": "@BillAckman", "content_type": "tweet"},
    {"source_name": "Capital Wars", "content_type": "blog"},
    {"source_name": "Michael Burry", "content_type": "blog"},
    {"source_name": "AVC", "content_type": "blog"},
    {"source_name": "Lex Fridman", "content_type": "podcast"},
    {"source_name": "@dylan522p", "content_type": "tweet"},
    {"source_name": "Acquired", "content_type": "podcast"},
    {"source_name": "Benedict Evans", "content_type": "blog"},
    {"source_name": "Howard Marks", "content_type": "blog"},
    {"source_name": "@IncomeSharks", "content_type": "tweet"},
]

SOURCE_DEFINITIONS = [
    {
        "source_id": "sec_edgar",
        "source_name": "SEC EDGAR",
        "source_family": "filing",
        "source_kind": "sec_api",
        "origin": "market",
        "enabled": True,
        "ingestion_mode": "direct_api",
        "raw_access": "free_public",
        "source_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "notes": "Primary SEC company filings API; includes 8-K, 10-Q, 10-K, DEF 14A, 6-K, and Form 4 targets.",
        "config": {"aggregate_source": True},
    },
    {
        "source_id": "sec_material_events_8k",
        "source_name": "Material Events (8-K)",
        "source_family": "filing",
        "source_kind": "sec_filing",
        "origin": "mungermode_benchmark",
        "enabled": True,
        "ingestion_mode": "direct_api",
        "raw_access": "free_public",
        "source_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "notes": "SEC 8-K material event filings materialized from equity_fundamentals rows when present.",
        "config": {"sec_form_types": ["8-K"]},
    },
    {
        "source_id": "sec_quarterly_reports_10q",
        "source_name": "Quarterly Reports (10-Q)",
        "source_family": "filing",
        "source_kind": "sec_filing",
        "origin": "mungermode_benchmark",
        "enabled": True,
        "ingestion_mode": "direct_api",
        "raw_access": "free_public",
        "source_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "notes": "SEC 10-Q quarterly reports materialized from equity_fundamentals rows when present.",
        "config": {"sec_form_types": ["10-Q"]},
    },
    {
        "source_id": "sec_annual_reports_10k",
        "source_name": "Annual Reports (10-K)",
        "source_family": "filing",
        "source_kind": "sec_filing",
        "origin": "mungermode_benchmark",
        "enabled": True,
        "ingestion_mode": "direct_api",
        "raw_access": "free_public",
        "source_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "notes": "SEC 10-K annual reports materialized from equity_fundamentals rows when present.",
        "config": {"sec_form_types": ["10-K"]},
    },
    {
        "source_id": "sec_proxy_statements_def14a",
        "source_name": "Proxy Statements (DEF 14A)",
        "source_family": "filing",
        "source_kind": "sec_filing",
        "origin": "mungermode_benchmark",
        "enabled": True,
        "ingestion_mode": "direct_api",
        "raw_access": "free_public",
        "source_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "notes": "SEC DEF 14A proxy statements materialized from equity_fundamentals rows when present.",
        "config": {"sec_form_types": ["DEF 14A"]},
    },
    {
        "source_id": "sec_foreign_reports_6k",
        "source_name": "Foreign Reports (6-K)",
        "source_family": "filing",
        "source_kind": "sec_filing",
        "origin": "mungermode_benchmark",
        "enabled": True,
        "ingestion_mode": "direct_api",
        "raw_access": "free_public",
        "source_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "notes": "SEC 6-K foreign issuer reports materialized from equity_fundamentals rows when present.",
        "config": {"sec_form_types": ["6-K"]},
    },
    {
        "source_id": "sec_disclosures",
        "source_name": "SEC disclosures",
        "source_family": "filing",
        "source_kind": "disclosure",
        "origin": "market",
        "enabled": True,
        "ingestion_mode": "direct_api",
        "raw_access": "free_public",
        "source_url": "https://www.sec.gov/edgar/search/",
        "notes": "Canonical bucket for 13F/Form 4/PTR-style disclosure signals already stored in Market.",
    },
    {
        "source_id": "earnings_transcripts",
        "source_name": "Earnings transcripts",
        "source_family": "transcript",
        "source_kind": "transcript_provider",
        "origin": "provider_candidate",
        "enabled": False,
        "ingestion_mode": "provider_required",
        "raw_access": "rights_required",
        "source_url": "",
        "notes": "Provider contract is intentionally unresolved; store permitted artifact refs only.",
    },
    {
        "source_id": "arco_birdclaw",
        "source_name": "Arco / Birdclaw",
        "source_family": "private_graph",
        "source_kind": "arco_bridge",
        "origin": "market",
        "enabled": True,
        "ingestion_mode": "arco_birdclaw_bridge",
        "raw_access": "local_private",
        "source_url": "/Volumes/agent/brain/raw/sources/arco",
        "notes": "Market consumes summarized Arco/Birdclaw exports and source refs; it does not scrape X/Twitter.",
    },
    {
        "source_id": "odd_lots",
        "source_name": "Odd Lots",
        "source_family": "podcast",
        "source_kind": "rss",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.bloomberg.com/oddlots",
        "notes": "Podcast source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "stratechery",
        "source_name": "Stratechery",
        "source_family": "blog",
        "source_kind": "newsletter",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "permitted_feed_or_refs",
        "raw_access": "mixed_rights",
        "source_url": "https://stratechery.com/",
        "notes": "Store only permitted summaries/refs when content is paywalled.",
    },
    {
        "source_id": "a16z",
        "source_name": "a16z",
        "source_family": "podcast",
        "source_kind": "rss",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://a16z.com/podcasts/",
        "notes": "Podcast source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "ark_invest",
        "source_name": "ARK Invest",
        "source_family": "podcast",
        "source_kind": "rss_or_video",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_youtube_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.ark-invest.com/",
        "notes": "Podcast/video source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "peter_diamandis",
        "source_name": "Peter Diamandis",
        "source_family": "podcast",
        "source_kind": "rss_or_video",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_youtube_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.diamandis.com/",
        "notes": "Source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "sequoia_capital",
        "source_name": "Sequoia Capital",
        "source_family": "podcast",
        "source_kind": "rss_or_blog",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.sequoiacap.com/",
        "notes": "Source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "all_in",
        "source_name": "All-In",
        "source_family": "podcast",
        "source_kind": "rss_or_video",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_youtube_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.allinpodcast.co/",
        "notes": "Podcast source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "not_boring",
        "source_name": "Not Boring",
        "source_family": "blog",
        "source_kind": "newsletter",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "permitted_feed_or_refs",
        "raw_access": "mixed_rights",
        "source_url": "https://www.notboring.co/",
        "notes": "Store only permitted summaries/refs when content is paywalled.",
    },
    {
        "source_id": "in_good_company",
        "source_name": "In Good Company",
        "source_family": "podcast",
        "source_kind": "rss",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "",
        "notes": "Podcast source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "invest_like_the_best",
        "source_name": "Invest Like the Best",
        "source_family": "podcast",
        "source_kind": "rss",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://joincolossus.com/episodes",
        "notes": "Podcast source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "semianalysis",
        "source_name": "SemiAnalysis",
        "source_family": "blog",
        "source_kind": "newsletter",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "permitted_feed_or_refs",
        "raw_access": "mixed_rights",
        "source_url": "https://www.semianalysis.com/",
        "notes": "Store only permitted summaries/refs when content is paywalled.",
    },
    {
        "source_id": "no_priors",
        "source_name": "No Priors",
        "source_family": "podcast",
        "source_kind": "rss",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.nopriors.com/",
        "notes": "Podcast source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "dwarkesh_patel",
        "source_name": "Dwarkesh Patel",
        "source_family": "podcast",
        "source_kind": "rss_or_blog",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.dwarkeshpatel.com/",
        "notes": "Source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "uncapped",
        "source_name": "Uncapped",
        "source_family": "podcast",
        "source_kind": "rss_or_video",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_youtube_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.uncapped.media/",
        "notes": "Podcast/video source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "cheeky_pint",
        "source_name": "Cheeky Pint",
        "source_family": "podcast",
        "source_kind": "rss_or_video",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_youtube_or_feed",
        "raw_access": "public_feed",
        "source_url": "",
        "notes": "Source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "citrini_research",
        "source_name": "Citrini Research",
        "source_family": "blog",
        "source_kind": "newsletter",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "permitted_feed_or_refs",
        "raw_access": "mixed_rights",
        "source_url": "https://www.citriniresearch.com/",
        "notes": "Store only permitted summaries/refs when content is paywalled.",
    },
    {
        "source_id": "capital_wars",
        "source_name": "Capital Wars",
        "source_family": "blog",
        "source_kind": "newsletter",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "permitted_feed_or_refs",
        "raw_access": "mixed_rights",
        "source_url": "",
        "notes": "Source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "chamath_palihapitiya",
        "source_name": "Chamath Palihapitiya",
        "source_family": "blog",
        "source_kind": "blog_or_social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "permitted_feed_or_arco_bridge",
        "raw_access": "mixed_rights",
        "source_url": "",
        "notes": "Use public/permitted refs or Arco/Birdclaw summaries; do not scrape social content in Market.",
    },
    {
        "source_id": "michael_burry",
        "source_name": "Michael Burry",
        "source_family": "blog",
        "source_kind": "filing_or_social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "filings_or_arco_bridge",
        "raw_access": "mixed_rights",
        "source_url": "",
        "notes": "Use filings and permitted summaries/refs; do not scrape social content in Market.",
    },
    {
        "source_id": "naval",
        "source_name": "Naval",
        "source_family": "podcast",
        "source_kind": "rss_or_social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_arco_bridge",
        "raw_access": "mixed_rights",
        "source_url": "https://nav.al/",
        "notes": "Use feeds or Arco/Birdclaw summaries; do not scrape X/Twitter in Market.",
    },
    {
        "source_id": "avc",
        "source_name": "AVC",
        "source_family": "blog",
        "source_kind": "blog",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://avc.com/",
        "notes": "Blog source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "lex_fridman",
        "source_name": "Lex Fridman",
        "source_family": "podcast",
        "source_kind": "rss_or_video",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_youtube_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://lexfridman.com/podcast/",
        "notes": "Podcast source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "acquired",
        "source_name": "Acquired",
        "source_family": "podcast",
        "source_kind": "rss",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "rss_or_feed",
        "raw_access": "public_feed",
        "source_url": "https://www.acquired.fm/",
        "notes": "Podcast source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "benedict_evans",
        "source_name": "Benedict Evans",
        "source_family": "blog",
        "source_kind": "newsletter",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "permitted_feed_or_refs",
        "raw_access": "mixed_rights",
        "source_url": "https://www.ben-evans.com/",
        "notes": "Store only permitted summaries/refs when content is paywalled.",
    },
    {
        "source_id": "howard_marks",
        "source_name": "Howard Marks",
        "source_family": "blog",
        "source_kind": "memo",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "permitted_feed_or_refs",
        "raw_access": "mixed_rights",
        "source_url": "https://www.oaktreecapital.com/insights",
        "notes": "Memo source candidate from the MungerMode parity benchmark.",
    },
    {
        "source_id": "x_balajis",
        "source_name": "@balajis",
        "source_family": "private_graph",
        "source_kind": "social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "arco_birdclaw_bridge",
        "raw_access": "local_private_refs",
        "source_url": "/Volumes/agent/brain/raw/sources/arco",
        "notes": "Use only Arco/Birdclaw exported refs or permitted public references; do not scrape X/Twitter in Market.",
    },
    {
        "source_id": "x_karpathy",
        "source_name": "@karpathy",
        "source_family": "private_graph",
        "source_kind": "social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "arco_birdclaw_bridge",
        "raw_access": "local_private_refs",
        "source_url": "/Volumes/agent/brain/raw/sources/arco",
        "notes": "Use only Arco/Birdclaw exported refs or permitted public references; do not scrape X/Twitter in Market.",
    },
    {
        "source_id": "x_citrini",
        "source_name": "@citrini",
        "source_family": "private_graph",
        "source_kind": "social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "arco_birdclaw_bridge",
        "raw_access": "local_private_refs",
        "source_url": "/Volumes/agent/brain/raw/sources/arco",
        "notes": "Use only Arco/Birdclaw exported refs or permitted public references; do not scrape X/Twitter in Market.",
    },
    {
        "source_id": "x_billackman",
        "source_name": "@BillAckman",
        "source_family": "private_graph",
        "source_kind": "social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "arco_birdclaw_bridge",
        "raw_access": "local_private_refs",
        "source_url": "/Volumes/agent/brain/raw/sources/arco",
        "notes": "Use only Arco/Birdclaw exported refs or permitted public references; do not scrape X/Twitter in Market.",
    },
    {
        "source_id": "x_dylan522p",
        "source_name": "@dylan522p",
        "source_family": "private_graph",
        "source_kind": "social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "arco_birdclaw_bridge",
        "raw_access": "local_private_refs",
        "source_url": "/Volumes/agent/brain/raw/sources/arco",
        "notes": "Use only Arco/Birdclaw exported refs or permitted public references; do not scrape X/Twitter in Market.",
    },
    {
        "source_id": "x_incomesharks",
        "source_name": "@IncomeSharks",
        "source_family": "private_graph",
        "source_kind": "social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "arco_birdclaw_bridge",
        "raw_access": "local_private_refs",
        "source_url": "/Volumes/agent/brain/raw/sources/arco",
        "notes": "Use only Arco/Birdclaw exported refs or permitted public references; do not scrape X/Twitter in Market.",
    },
    {
        "source_id": "x_arco_watch_accounts",
        "source_name": "X accounts via Arco/Birdclaw",
        "source_family": "private_graph",
        "source_kind": "social_bridge",
        "origin": "mungermode_benchmark",
        "enabled": False,
        "ingestion_mode": "arco_birdclaw_bridge",
        "raw_access": "local_private_refs",
        "source_url": "/Volumes/agent/brain/raw/sources/arco",
        "notes": "Covers @balajis, @karpathy, @citrini, @BillAckman, and @dylan522p through Arco/Birdclaw exports only.",
    },
]
