"""Generate the frontend panel-table key contract from the backend owner."""

from __future__ import annotations

import argparse
from pathlib import Path

from investment_panel.core.panel import frontend_key_for_table, frontend_table_names


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontend" / "src" / "generated" / "panelContract.ts"


def rendered_contract() -> str:
    keys = sorted(frontend_key_for_table(name) for name in frontend_table_names())
    body = "\n".join(f'  "{key}",' for key in keys)
    return (
        "// Generated by scripts/generate_panel_contract.py. Do not edit by hand.\n"
        "export const PANEL_TABLE_KEYS = [\n"
        f"{body}\n"
        "] as const;\n\n"
        "export type PanelTableKey = (typeof PANEL_TABLE_KEYS)[number];\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = rendered_contract()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("frontend panel contract is stale; run scripts/generate_panel_contract.py")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
